= v1.1.2/v1.1.3/v1.2.0 から v1.2.1 へのアップグレード
:revdate: 2025-05-09
:page-revdate: {revdate}

== このバージョンに関する重要な変更

Harvester `v1.2.1` は `v1.2.0` で見つかったアップグレードの既知の問題を修正し、`v1.1.2`、`v1.1.3`、または `v1.2.0` クラスターを `v1.2.1` にアップグレードすることをお勧めします。`v1.2.0` で見つかった既知の問題は次のとおりです：

* xref:./v1-1-2-to-v1-2-0.adoc#_9_an_upgrade_is_stuck_in_the_post_draining_state[アップグレードがポストドレイン状態で停止しています]
* xref:./v1-1-2-to-v1-2-0.adoc#_10_an_upgrade_is_stuck_in_the_upgrading_system_service_state_due_to_the_customer_provided_ssl_certificate_without_ip_san_error_in_fleet_agent[アップグレードが、顧客が提供した SSL 証明書に IP SAN エラーがあるため、fleet-agent 内でシステムサービスのアップグレード状態に停止しています]

v1.2.0 に既にアップグレードされたクラスターについては、新しい変更のために https://github.com/harvester/harvester/releases/tag/v1.2.1[リリースノート] を参照してください。

== 一般情報

[TIP]
====
アップグレードを開始する前に、クラスターが安定した状態にあることを確認するために、事前チェック用スクリプトを実行できます。詳細については、この https://github.com/harvester/upgrade-helpers/tree/main/pre-check/v1.1.x[URL] を訪れてスクリプトをご覧ください。
====

アップグレード可能なバージョンがある場合、Harvester GUI ダッシュボードページにアップグレードボタンが表示されます。詳細については、xref:./upgrades.adoc#_start_an_upgrade[アップグレードを開始する] を参照してください。

エアギャップ環境のアップグレードについては、xref:./upgrades.adoc#_prepare_an_air_gapped_upgrade[エアギャップ(された)アップグレードの準備] を参照してください。

== 当バージョンの注意事項

v1.2.0 の xref:./v1-1-2-to-v1-2-0.adoc#_known_issues[既知の問題] を確認してください。
