= v1.3.2からv1.4.0にアップグレードする
:revdate: 2025-07-07
:page-revdate: {revdate}

== 一般情報

新しい{harvester-product-name}バージョンが利用可能になると、*ダッシュボード*画面に*アップグレード*ボタンが表示されます。詳細については、xref:./upgrades.adoc#_start_an_upgrade[アップグレードを開始する]を参照してください。

エアギャップ環境の場合は、xref:./upgrades.adoc#_prepare_an_air_gapped_upgrade[エアギャップアップグレードの準備]を参照してください。

=== アップグレード中の仮想マシンイメージの破損を防ぐ

[CAUTION]
====
アップグレードを開始する前に、`BackingImage` CRDが https://github.com/longhorn/longhorn/blob/v1.7.2/deploy/longhorn.yaml#L486-L690[{longhorn-product-name} *v1.7.2*バージョン]に更新されていることを確認してください。

CRDの更新をスキップすると、 https://github.com/longhorn/longhorn/issues/10644[問題 #10644]に記載されているように、バックイメージの破損が発生する可能性があります。
====

アップグレードを開始する前に、以下の手順を実行してください。

. 関連するエラーや警告を回避するために、*{harvester-product-name} ManagedChartオブジェクト*をパッチします。
+
[,shell]
----
kubectl patch managedchart harvester \
-n fleet-local \
--type='json' \
-p='[
  {
    "op":"add",
    "path":"/spec/diff/comparePatches/-",
    "value": {
      "apiVersion":"apiextensions.k8s.io/v1",
      "jsonPointers":["/spec","/metadata/annotations", "/metadata/labels", "/status"],
      "kind":"CustomResourceDefinition",
      "name":"backingimages.longhorn.io"
    }
  }
]'
----

. *{longhorn-product-name} v1.7.2* https://github.com/longhorn/longhorn/blob/v1.7.2/deploy/longhorn.yaml#L486-L690[`BackingImage` CRD]を適用します。
+
[,yaml]
----
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.15.0
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/version: v1.7.2
    longhorn-manager: ""
  name: backingimages.longhorn.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: longhorn-conversion-webhook
          namespace: longhorn-system
          path: /v1/webhook/conversion
          port: 9501
      conversionReviewVersions:
      - v1beta2
      - v1beta1
  group: longhorn.io
  names:
    kind: BackingImage
    listKind: BackingImageList
    plural: backingimages
    shortNames:
    - lhbi
    singular: backingimage
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: The backing image name
      jsonPath: .spec.image
      name: Image
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: BackingImage is where Longhorn stores backing image object.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            x-kubernetes-preserve-unknown-fields: true
          status:
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - additionalPrinterColumns:
    - description: The system generated UUID
      jsonPath: .status.uuid
      name: UUID
      type: string
    - description: The source of the backing image file data
      jsonPath: .spec.sourceType
      name: SourceType
      type: string
    - description: The backing image file size in each disk
      jsonPath: .status.size
      name: Size
      type: string
    - description: The virtual size of the image (may be larger than file size)
      jsonPath: .status.virtualSize
      name: VirtualSize
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1beta2
    schema:
      openAPIV3Schema:
        description: BackingImage is where Longhorn stores backing image object.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: BackingImageSpec defines the desired state of the Longhorn
              backing image
            properties:
              checksum:
                type: string
              diskFileSpecMap:
                additionalProperties:
                  properties:
                    evictionRequested:
                      type: boolean
                  type: object
                type: object
              diskSelector:
                items:
                  type: string
                type: array
              disks:
                additionalProperties:
                  type: string
                description: Deprecated. We are now using DiskFileSpecMap to assign
                  different spec to the file on different disks.
                type: object
              minNumberOfCopies:
                type: integer
              nodeSelector:
                items:
                  type: string
                type: array
              secret:
                type: string
              secretNamespace:
                type: string
              sourceParameters:
                additionalProperties:
                  type: string
                type: object
              sourceType:
                enum:
                - download
                - upload
                - export-from-volume
                - restore
                - clone
                type: string
            type: object
          status:
            description: BackingImageStatus defines the observed state of the Longhorn
              backing image status
            properties:
              checksum:
                type: string
              diskFileStatusMap:
                additionalProperties:
                  properties:
                    lastStateTransitionTime:
                      type: string
                    message:
                      type: string
                    progress:
                      type: integer
                    state:
                      type: string
                  type: object
                nullable: true
                type: object
              diskLastRefAtMap:
                additionalProperties:
                  type: string
                nullable: true
                type: object
              ownerID:
                type: string
              size:
                format: int64
                type: integer
              uuid:
                type: string
              virtualSize:
                description: Virtual size of image, which may be larger than physical
                  size. Will be zero until known (e.g. while a backing image is uploading)
                format: int64
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
----

== 既知の問題

=== 1.アップグレードが「プレドレイン」状態で停止しています

コンテナディスクを持つ仮想マシンは、ライブマイグレーション機能の制限により移行できません。これにより、アップグレードプロセスが「プレドレイン」状態で停止します。

[TIP]
====
アップグレードプロセスを続行するには、仮想マシンを手動で停止してください。
====

関連する問題: https://github.com/harvester/harvester/issues/7005[#7005]

=== 2.アップグレードがバンドル待機中で停止しています

この問題は、{fleet-product-name}エージェント（`fleet-agent`）が再デプロイされる際の競合状態によって引き起こされます。以下のエラーメッセージは、問題が存在することを示しています。

[,shell]
----
> kubectl get bundles -n fleet-local
NAME                                          BUNDLEDEPLOYMENTS-READY   STATUS
mcc-harvester                                 0/1                       ErrApplied(1) [Cluster fleet-local/local: encountered 2 deletion errors. First is: admission webhook "validator.harvesterhci.io" denied the request: Internal error occurred: no route match found for DELETE /v1, Kind=Secret harvester-system/sh.helm.release.v1.harvester.v2]
mcc-harvester-crd                             0/1                       ErrApplied(1) [Cluster fleet-local/local: admission webhook "validator.harvesterhci.io" denied the request: Internal error occurred: no route match found for DELETE /v1, Kind=Secret harvester-system/sh.helm.release.v1.harvester-crd.v1]
----

問題を修正するために、以下のスクリプトを実行できます。

[,shell]
----
#!/bin/bash

patch_fleet_bundle() {
  local bundleName=$1
  local generation=$(kubectl get -n fleet-local bundle ${bundleName} -o jsonpath='{.spec.forceSyncGeneration}')
  local new_generation=$((generation+1))
  patch_manifest="$(mktemp)"
  cat > "$patch_manifest" <<EOF
{
  "spec": {
    "forceSyncGeneration": $new_generation
  }
}
EOF
  echo "patch bundle to new generation: $new_generation"
  kubectl patch -n fleet-local bundle ${bundleName}  --type=merge --patch-file $patch_manifest
  rm -f $patch_manifest
}

echo "removing harvester validating webhook"
kubectl delete validatingwebhookconfiguration harvester-validator

for bundle in mcc-harvester-crd mcc-harvester
do
  patch_fleet_bundle ${bundle}
done

echo "removing longhorn services"
kubectl delete svc longhorn-engine-manager -n longhorn-system --ignore-not-found=true
kubectl delete svc longhorn-replica-manager -n longhorn-system --ignore-not-found=true
----

=== 3.アップグレードが{fleet-product-name}の待機中で停止しています

v1.3.2からv1.4.0にアップグレードする際、アップグレードプロセスが{fleet-product-name}の準備が整うのを待っている状態で停止する可能性があります。この問題は、{rancher-product-name}が再デプロイされる際の競合状態によって引き起こされます。

次の指標について{harvester-product-name}のログと{fleet-product-name}の履歴を確認してください：

* マニフェストポッドが`deployed`の状態で停止しています。
* アップグレードは、デプロイされたチャートバージョンで保留中です。

例:

[,shell]
----
> kubectl logs -n harvester-system -l harvesterhci.io/upgradeComponent=manifest
wait helm release cattle-fleet-system fleet fleet-104.0.2+up0.10.2 0.10.2 deployed

> helm history -n cattle-fleet-system fleet
REVISION    UPDATED                     STATUS             CHART                    APP VERSION    DESCRIPTION
26          Tue Dec 10 03:09:13 2024    superseded         fleet-103.1.5+up0.9.5    0.9.5          Upgrade complete
27          Sun Dec 15 09:26:54 2024    superseded         fleet-103.1.5+up0.9.5    0.9.5          Upgrade complete
28          Sun Dec 15 09:27:03 2024    superseded         fleet-103.1.5+up0.9.5    0.9.5          Upgrade complete
29          Mon Dec 16 05:57:03 2024    deployed           fleet-103.1.5+up0.9.5    0.9.5          Upgrade complete
30          Mon Dec 16 05:57:13 2024    pending-upgrade    fleet-103.1.5+up0.9.5    0.9.5          Preparing upgrade
----

次のコマンドを実行して問題を修正できます。

[,shell]
----
helm rollback fleet -n cattle-fleet-system <last-deployed-revision>
----

=== 4.「Dismiss it」ボタンがクリックされた後、アップグレードが予期せず再起動します。

{rancher-short-name}を使用して{harvester-product-name}をアップグレードすると、{rancher-short-name} UIに「Dismiss it」とラベル付けされたボタンがあるダイアログが表示されます。このボタンをクリックすると、次の問題が発生する可能性があります：

* `status` CRの`harvesterhci.io/v1beta1/upgrade`セクションがクリアされ、アップグレードに関するすべての重要な情報が失われます。
* アップグレードプロセスが予期せず再起動します。

この問題は、xref:../integrations/rancher/harvester-ui-extension.adoc#_support_matrix[Harvester UI Extension]のv1.0.2、v1.0.3、v1.0.4を使用している{rancher-short-name} v2.10.xに影響します。すべての{harvester-product-name} UIバージョンには影響しません。この問題は、Harvester UI Extension v1.0.5およびv1.5.0で修正されています。

この問題を回避するには、次のいずれかのアクションを実行してください：

* アップグレードには{harvester-product-name} UIを使用してください。{harvester-product-name} UIの「Dismiss it」ボタンをクリックしても、予期しない動作は発生しません。
* {rancher-short-name} UIのボタンをクリックする代わりに、クラスターに対して次のコマンドを実行してください：
+
[,shell]
----
kubectl -n harvester-system label upgrades -l harvesterhci.io/latestUpgrade=true harvesterhci.io/read-message=true
----

関連する問題： https://github.com/harvester/harvester/issues/7791[#7791]

=== 5.移行可能なRWXボリュームを使用する仮想マシンが予期せず再起動します。

マイグレーション可能なxref:integrations/rancher/csi-driver.adoc#_rwx_volumes_support[RWXボリューム]を使用する仮想マシンは、CSIプラグインポッドが再起動されると予期せず再起動します。この問題は、{harvester-product-name} v1.4.x、v1.5.0、およびv1.5.1に影響を与えます。

回避策は、アップグレードを開始する前に、{longhorn-product-name} UI で設定 https://documentation.suse.com/cloudnative/storage/1.8/en/longhorn-system/settings.html#_automatically_delete_workload_pod_when_the_volume_is_detached_unexpectedly[ボリュームが予期せず切り離されたときにワークロードポッドを自動的に削除する] を無効にすることです。アップグレードが完了したら、再度設定を有効にする必要があります。

この問題は、{longhorn-product-name} v1.8.3、v1.9.1、およびそれ以降のバージョンで修正されます。{harvester-product-name} v1.6.0 には {longhorn-product-name} v1.9.1 が含まれます。

関連する問題: https://github.com/harvester/harvester/issues/8534[#8534] および https://github.com/longhorn/longhorn/issues/11158[#11158]