= v1.5.0またはv1.5.1からv1.5.2にアップグレードします。
:revdate: 2025-11-11
:page-revdate: {revdate}

== 一般情報

新しい{harvester-product-name}バージョンにアップグレードできるようになると、*ダッシュボード*画面に*アップグレード*ボタンが表示されます。詳細については、xref:./upgrades.adoc#_start_an_upgrade[アップグレードを開始する]を参照してください。

エアギャップ(された)環境での{harvester-product-name}のアップグレードに関する情報は、xref:./upgrades.adoc#_prepare_an_air_gapped_upgrade[エアギャップ(された)アップグレードの準備]を参照してください。

=== {rancher-product-name} v2.11.0でHarvester UI拡張機能を更新します。

{rancher-short-name} v2.11.0で{harvester-product-name} v1.5.2クラスターをインポートするには、Harvester UI拡張機能の**v1.5.2**を使用する必要があります。

. {rancher-short-name} UIで、*ローカル->アプリ->リポジトリ*に移動します。

. *harvester*という名前のリポジトリを見つけて、*⋮ ->更新する*を選択します。

. *拡張機能*画面に移動します。

. *Harvester*という名前の拡張機能を見つけて、*更新*をクリックします。

. バージョン*1.5.2*を選択し、*更新*をクリックします。

. 拡張機能が更新されるまでしばらくお待ちいただき、画面を更新してください。

== 当バージョンの注意事項

=== 移行可能なRWXボリュームを使用する仮想マシンが予期せず再起動します。

CSIプラグインポッドが再起動されると、移行可能なxref:integrations/rancher/csi-driver.adoc#_rwx_volumes_support[RWXボリューム]を使用する仮想マシンが予期せず再起動します。この問題は{harvester-product-name} v1.4.x、v1.5.0、およびv1.5.1に影響します。

回避策は、アップグレードを開始する前に{longhorn-product-name} UIで設定 https://documentation.suse.com/cloudnative/storage/1.8/en/longhorn-system/settings.html#_automatically_delete_workload_pod_when_the_volume_is_detached_unexpectedly[ボリュームが予期せず切り離されたときにワークロードポッドを自動的に削除する]を無効にすることです。アップグレードが完了したら、設定を再度有効にする必要があります。

この問題は{longhorn-product-name} v1.8.3、v1.9.1、およびそれ以降のバージョンで修正されます。{harvester-product-name} v1.6.0には{longhorn-product-name} v1.9.1が含まれます。

関連する問題： https://github.com/harvester/harvester/issues/8534[#8534]および https://github.com/longhorn/longhorn/issues/11158[#11158]