= v1.7.xからv1.7.yにアップグレードする
:revdate: 2026-01-08
:page-revdate: {revdate}

== 一般情報

新しい{harvester-product-name}バージョンが利用可能になると、*ダッシュボード*画面に*アップグレード*ボタンが表示されます。詳細については、xref:upgrades/upgrades.adoc#_start_an_upgrade[アップグレードを開始する]を参照してください。

エアギャップ(された)環境での{harvester-product-name}のアップグレードに関する情報は、xref:upgrades/upgrades.adoc#_prepare_an_air_gapped_upgrade[エアギャップ(された)アップグレードの準備]を参照してください。

=== {rancher-product-name} v2.13でHarvester UI拡張機能を更新する

{rancher-short-name} v2.13で{harvester-product-name} v1.7.xクラスターをインポートするには、Harvester UI拡張機能の互換性のあるバージョン(v1.7.x)を使用する必要があります。

. {rancher-short-name} UIで、*ローカル -> アプリ -> リポジトリ*に移動します。

. *harvester*という名前のリポジトリを見つけて、*⋮ -> 更新*を選択します。

. *拡張機能*画面に移動します。

. *Harvester*という名前の拡張機能を見つけて、*更新*をクリックします。

. 互換性のあるバージョンを選択し、*更新*をクリックします。

. 拡張機能が更新されるまでしばらくお待ちいただき、画面を更新してください。

== 当バージョンの注意事項

=== アップグレードが「ポストドレイン」状態で停止しています

ノードのドレインプロセス中に、`upgrade-repo`デプロイメントがその{longhorn-product-name}ボリュームが「アタッチ中」状態のままになると停止することがあります。これにより、ポストドレインジョブが`upgrade-repo`デプロイメントが準備完了になるのを待つため、アップグレードフローが「ポストドレイン」フェーズで停止します。

回避策は、ドレインされたノードの`upgrade-repo`ボリュームの{longhorn-product-name}レプリカを削除することです。これにより、ボリュームがアタッチされ、アップグレードフローが続行されます。アップグレード中にドレインされているノードはこの問題に直面する可能性があるため、発生するたびにこの回避策を適用する必要があるかもしれません。

関連する問題: https://github.com/harvester/harvester/issues/9597[#9597]および https://github.com/longhorn/longhorn/issues/12226[#12226]