= Virtual Machines

You can create xref:create-vm.adoc[Linux virtual machines] using one of the following methods: 

- Harvester UI: On the *Virtual Machines* screen, click *Create* and configure the settings on each tab. 
- Kubernetes API: Create a `VirtualMachine` object. 
- xref:../integrations/terraform/terraform-provider.adoc[Harvester Terraform Provider]: Define a `harvester_virtualmachine` resource block. 

Creating xref:create-windows-vm.adoc[Windows virtual machines] on the Harvester UI involves slightly different steps. Harvester provides a virtual machine template named `windows-iso-image-base-template` that adds a volume with the Virtio drivers for Windows, which streamlines the configuration process. If you require Virtio devices but choose to not use the template, you must add your own Virtio drivers for Windows to enable correct hardware detection. 

== Supported Guest Operating Systems

The following operating systems have been validated to run in Harvester virtual machines:

|===
| Operating System | Harvester v1.3.0 | Harvester v1.3.1 | Harvester v1.3.2 | Harvester v1.4.0

| OpenSUSE Leap
| 15.4
| 15.4
| 15.5
| 15.6

| SLE Micro
| N/A
| N/A
| 6
| 6

| SLES
| 15 SP4, 15 SP5
| 15 SP4, 15 SP5
| 15 SP4, 15 SP6
| 15 SP4, 15 SP6

| RHEL
| N/A
| N/A
| 9.4
| 9.4

| Ubuntu
| 22.04, 23.04
| 22.04, 23.04
| 24.04
| 24.04

| Windows
| 11
| 11
| 11
| 11

| Windows Server
| 2022
| 2022
| 2022
| 2022
|===

[NOTE]
====
The list includes only tested operating systems and is not intended to be exhaustive. Other operating systems may also run in Harvester virtual machines. However, Harvester cannot be held responsible for any damage or loss of data that may occur through the use of untested operating systems.

The contents of this document may not reflect the most current situation and may change at any time without notice.
====