= NIC Hotplug
:revdate: 2026-01-02
:page-revdate: {revdate}

{harvester-product-name} unterstützt Hot-Plugging und Hot-Unplugging von Netzwerkschnittstellenkarten (NICs) für xref:virtual-machines/live-migration.adoc#_live_migratable_virtual_machines[live-migrierbare] virtuelle Maschinen. Dieses Feature ermöglicht es Ihnen, Netzwerkschnittstellen von einer laufenden virtuellen Maschine hinzuzufügen und zu entfernen, ohne einen Neustart durchführen zu müssen.

[NOTE]
====
Sie können kein NIC-Hot-Plugging bei virtuellen Maschinen durchführen, die in Clustern erstellt wurden, die {harvester-product-name} Versionen vor v1.7.0 verwenden, _wenn die MAC-Adresse der Netzwerkschnittstelle nicht explizit konfiguriert wurde_. Um dieses Feature zu aktivieren, müssen Sie diese virtuellen Maschinen neu starten. Ein Neustart ermöglicht es dem System, die beobachteten MAC-Adressen automatisch in der Konfiguration der virtuellen Maschine zu speichern.

Darüber hinaus unterstützen virtuelle Maschinen, die mit dem xref:integrations/rancher/node-driver/node-driver.adoc[Harvester Node Driver] und dem xref:integrations/terraform/terraform-provider.adoc[Harvester Terraform Provider] erstellt wurden, _NIC-Hot-Plugging und NIC-Hot-Unplugging_ nicht.
====

== Hotplug Netzwerkschnittstellenkarten (NICs) zu einer laufenden virtuellen Maschine

. Gehen Sie im {harvester-product-name} UI zum Bildschirm *Virtuelle Maschinen*.

. Suchen Sie die Ziel-virtuelle Maschine und wählen Sie dann *⋮ -> Netzwerkschnittstelle Hotplug* aus.

. Geben Sie einen Namen für die Netzwerkschnittstelle an und wählen Sie ein virtuelles Maschinennetzwerk aus.
+
Sie können ein xref:networking/vm-network.adoc#_vlan_network[VLAN-Netzwerk], ein xref:networking/vm-network.adoc#_untagged_network[untagged Netzwerk] oder ein xref:networking/vm-network.adoc#_vlan_trunk_network[VLAN-Trunk-Netzwerk] auswählen.

. Klicken Sie auf *Anwenden*.

{harvester-product-name} xref:virtual-machines/live-migration.adoc#_prerequisites[migriert die virtuelle Maschine] und die angegebene Netzwerkschnittstelle wird über Bridge-Bindung verbunden.

Für Informationen über Einschränkungen der Anzahl der hotplugged Netzwerkschnittstellen siehe https://kubevirt.io/user-guide/network/hotplug_interfaces/#virtio-limitations[Virtio-Einschränkungen] in der KubeVirt-Dokumentation.

== Hot-Unplug Netzwerkschnittstellenkarten (NICs) von einer laufenden virtuellen Maschine

[IMPORTANT]
====
Sie können diese Aktion nur durchführen, wenn die folgenden Bedingungen erfüllt sind:

* Die virtuelle Maschine hat mindestens zwei Netzwerkschnittstellen. Sie können die einzige verbleibende Netzwerkschnittstelle nicht hot-unpluggen.
* Die Ziel-Netzwerkschnittstelle ist über Bridge-Bindung verbunden.
====

. Gehen Sie im {harvester-product-name} UI zum Bildschirm *Virtuelle Maschinen*.

. Klicken Sie auf den Namen der Ziel-virtuellen Maschine und gehen Sie dann zum *Netzwerke*-Tab.

. Suchen Sie die Ziel-Netzwerkschnittstelle und klicken Sie dann auf *Netzwerkschnittstelle trennen*.

{harvester-product-name} xref:virtual-machines/live-migration.adoc#_prerequisites[migriert die virtuelle Maschine] und trennt die Netzwerkschnittstelle.