= Virtuelle Maschinen
:revdate: 2026-01-08
:page-revdate: {revdate}

Sie können xref:../virtual-machines/create-vm.adoc[virtuelle Linux-Maschinen] mit einer der folgenden Methoden erstellen: 

* {harvester-product-name} UI: Klicken Sie auf dem Bildschirm „*Virtuelle Maschinen*“ auf *Erstellen* und konfigurieren Sie die Einstellungen auf jeder Registerkarte. 
* Kubernetes API: Erstellen Sie ein `VirtualMachine`-Objekt. 
* xref:../integrations/terraform/terraform-provider.adoc[Harvester Terraform Provider]: Definieren Sie einen `harvester_virtualmachine`-Ressourcenblock. 

Das Erstellen von xref:../virtual-machines/create-windows-vm.adoc[virtuellen Windows-Maschinen] über die UI umfasst leicht unterschiedliche Schritte. {harvester-product-name} bietet eine virtuelle Maschinenvorlage namens `windows-iso-image-base-template`, die ein Volume mit den Virtio-Treibern für Windows hinzufügt, was den Konfigurationsprozess vereinfacht. Wenn Sie Virtio-Geräte benötigen, aber die Vorlage nicht verwenden möchten, müssen Sie Ihre eigenen Virtio-Treiber für Windows hinzufügen, um eine korrekte Hardwareerkennung zu ermöglichen. 

== Validierte Gastbetriebssysteme

Die folgenden Betriebssysteme wurden validiert, um in {harvester-product-name} virtuellen Maschinen zu laufen:

* SUSE Linux Enterprise Micro 6.0 und 6.1
* SUSE Linux Enterprise Server 15 SP6 und 15 SP7
* Red Hat Enterprise Linux 9 und 10
* Ubuntu 22.04 und 24.04
* Windows 11
* Windows Server 2025

[NOTE]
====
Die Liste umfasst nur getestete Betriebssysteme und ist nicht als vollständig zu betrachten. Andere Betriebssysteme können ebenfalls in {harvester-product-name} virtuellen Maschinen laufen. Gastbetriebssysteme müssen jedoch mit der Architektur der Hosts des {harvester-product-name}-Clusters übereinstimmen. Virtuelle AMD-Maschinen können nur auf AMD-Clustern und virtuelle ARM-Maschinen nur auf ARM-Clustern betrieben werden.

Sie sind verantwortlich für den Erwerb, die Aktivierung und die Verwaltung von Lizenzen für jede kommerzielle Software, die Sie verwenden möchten. {harvester-product-name} kann nicht für Schäden oder Datenverluste verantwortlich gemacht werden, die durch die Verwendung von ungetesteten, nicht gepatchten und veralteten Betriebssystemen entstehen können.

Der Inhalt dieses Dokuments spiegelt möglicherweise nicht die aktuellste Situation wider und kann jederzeit ohne vorherige Ankündigung geändert werden.
====