= 从 v1.5.0 或 v1.5.1 升级到 v1.5.2
:revdate: 2025-11-11
:page-revdate: {revdate}

== 一般信息

每当有新的 {harvester-product-name} 版本可供升级时，*升级* 按钮会出现在 *仪表板* 屏幕上。有关更多信息，请参见 xref:./upgrades.adoc#_start_an_upgrade[开始升级]。

有关在隔离的环境中升级 {harvester-product-name} 的信息，请参见 xref:./upgrades.adoc#_prepare_an_air_gapped_upgrade[准备隔离的升级]。

=== 在 {rancher-product-name} v2.11.0 上更新 Harvester UI 扩展

您必须在 {rancher-short-name} v2.11.0 上使用 **v1.5.2** 的 Harvester UI 扩展导入 {harvester-product-name} v1.5.2 集群。

. 在 {rancher-short-name} UI 上，转到 *本地 -> APP -> 储存库*。

. 找到名为 *harvester* 的储存库，然后选择 *⋮ -> 刷新*。

. 转到 *扩展* 屏幕。

. 找到名为 *Harvester* 的扩展，然后点击 *更新*。

. 选择版本 *1.5.2*，然后点击 *更新*。

. 请等待一段时间以更新扩展，然后刷新屏幕。

== 已知问题

=== 使用可迁移 RWX 卷的虚拟机意外重启

当 CSI 插件 Pod 被重启时，使用可迁移 xref:integrations/rancher/csi-driver.adoc#_rwx_volumes_support[RWX 卷] 的虚拟机会意外重启。此问题影响 {harvester-product-name} v1.4.x、v1.5.0 和 v1.5.1。

解决方法是在开始升级之前，在 {longhorn-product-name} UI 上禁用设置 https://documentation.suse.com/cloudnative/storage/1.8/en/longhorn-system/settings.html#_automatically_delete_workload_pod_when_the_volume_is_detached_unexpectedly[意外分离卷时自动删除工作负载 Pod]。升级完成后，您必须再次启用该设置。

该问题将在 {longhorn-product-name} v1.8.3、v1.9.1 及更高版本中修复。{harvester-product-name} v1.6.0 将包含 {longhorn-product-name} v1.9.1。

相关问题： https://github.com/harvester/harvester/issues/8534[#8534] 和 https://github.com/longhorn/longhorn/issues/11158[#11158]