= 从 v1.7.x 升级到 v1.7.y
:revdate: 2026-01-08
:page-revdate: {revdate}

== 一般信息

每当有新的 {harvester-product-name} 版本可供升级时，*升级* 按钮会出现在 *仪表板* 屏幕上。有关更多信息，请参见 xref:upgrades/upgrades.adoc#_start_an_upgrade[开始升级]。

有关在隔离的环境中升级 {harvester-product-name} 的信息，请参见 xref:upgrades/upgrades.adoc#_prepare_an_air_gapped_upgrade[准备隔离的升级]。

=== 在 {rancher-product-name} v2.13 上更新 Harvester UI 扩展

您必须使用兼容版本 (v1.7.x) 的 Harvester UI 扩展来导入 {harvester-product-name} v1.7.x 集群到 {rancher-short-name} v2.13。

. 在 {rancher-short-name} UI 上，转到 *本地 -> APP -> 储存库*。

. 找到名为 *harvester* 的储存库，然后选择 *⋮ -> 刷新*。

. 转到 *扩展* 屏幕。

. 找到名为 *Harvester* 的扩展，然后点击 *更新*。

. 选择一个兼容版本，然后点击 *更新*。

. 请等待一段时间以更新扩展，然后刷新屏幕。

== 已知问题

=== 升级卡在 "后排空" 状态

在节点排空过程中，当 `upgrade-repo` 部署的 {longhorn-product-name} 卷保持在 "附加中" 状态时，可能会卡住。这导致升级流程在 "后排空" 阶段停滞，因为后排作业在继续之前等待 `upgrade-repo` 部署准备就绪。

解决方法是删除排空节点上 `upgrade-repo` 卷的 {longhorn-product-name} 副本。这允许卷附加并继续升级流程。请注意，在升级过程中，任何正在排空的节点可能会遇到此问题，因此每当发生此问题时，可能需要应用此解决方法。

相关问题： https://github.com/harvester/harvester/issues/9597[#9597] 和 https://github.com/longhorn/longhorn/issues/12226[#12226]