= Guia de Desenvolvimento de Complementos
:revdate: 2025-06-17
:page-revdate: {revdate}

{harvester-product-name} Complementos permitem que você ative e desative componentes específicos de produtos e de terceiros com base em suas necessidades. Complementos funcionam como um agrupador para a https://documentation.suse.com/cloudnative/rke2/latest/en/helm.html#_using_the_helm_crd[{rke2-product-name} definição de recurso HelmChart (CRD)].

== Pré-requisitos

* Um cluster {harvester-product-name} existente

== Especificações de Complementos

O `Addon` CRD suporta os seguintes campos:

[,yaml]
----
apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  name: example-add-on           # Name of add-on
  namespace: example-namespace  # Namespace where the add-on CRD is deployed and where the associated Kubernetes components will be deployed
  labels:                       # Optional add-on labels
    Add-on.harvesterhci.io/experimental: "true" # Predefined label used on the UI to identify add-ons with the "experimental" maturity level
spec:
  enabled: false                # Boolean indicating if an add-on should be enabled or disabled on definition
  repo: https://chartsrepo.com  # Helm chart repository containing the Helm chart managed by the add-on
  version: "v0.19.0"            # Version of the Helm chart to be installed
  chart: mychart                # Name of the Helm chart in the Helm chart repository
  valuesContent: |-             # File (values.yaml) that must be passed to the Helm chart
    contents of values.yaml
    that need to be passed
    to the chart
----

[NOTE]
====
Complementos experimentais não estão diretamente empacotados em {harvester-product-name}. Um exemplo é o https://github.com/harvester/experimental-addons/blob/main/rancher-vcluster/rancher-vcluster.yaml[`rancher-vcluster`] complemento.
====

== Instalação

[,bash]
----
kubectl apply -f /path/to/add-on.yaml
----

== Uso

Após criar um `Addon` CRD, você pode alternar o campo `enabled` para ativar e desativar o gráfico Helm associado.

== Upgrade

Mudanças nos campos `repo`, `version`, `chart` ou `valueContent` irão acionar um `helm upgrade`, que força o fazer upgrade do gráfico Helm existente.

== Desinstalação

[,bash]
----
kubectl delete -f /path/to/Add-on.yaml
----
