= Add-Ons
:revdate: 2025-12-30
:page-revdate: {revdate}

{harvester-product-name} bietet optionale Funktionen als Add-ons an, um einen minimalen Installations-Fußabdruck beizubehalten. Dieses Design ermöglicht es Ihnen, Funktionen basierend auf Ihrem Anwendungsfall und Ihren Anforderungen zu aktivieren oder zu deaktivieren. Sie können die Einstellungen jedes Add-ons anpassen, wobei der Grad der Anpassung von der zugrunde liegenden Software abhängt.

Die folgenden Add-ons sind in dieser Version verfügbar:

* xref:add-ons/lvm-local-storage.adoc[csi-driver-lvm] (Experimentell)
* xref:add-ons/kubeovn-operator.adoc[kubeovn-operator] (Experimentell)
* xref:add-ons/nvidia-driver-toolkit.adoc[nvidia-driver-toolkit]
* xref:add-ons/pcidevices-controller.adoc[pcidevices-controller]
* xref:observability/logging.adoc[rancher-logging]
* xref:observability/monitoring.adoc[rancher-monitoring]
* xref:add-ons/rancher-vcluster.adoc[rancher-vcluster] (Experimentell)
* xref:add-ons/harvester-seeder.adoc[seeder] (Experimentell)
* xref:add-ons/vm-dhcp-controller.adoc[vm-dhcp-controller] (Experimental)
* xref:add-ons/vm-import-controller.adoc[vm-import-controller]

Sie können Add-ons auf dem *Add-ons* Bildschirm der {harvester-product-name} Benutzeroberfläche aktivieren und deaktivieren.

|===
| Aktion | Aktion | Neuer Zustand

| Aktivierung eines Add-ons
| Wählen Sie das Add-on aus und dann *⋮ -> Aktivieren*.
| **DeploySuccessful**

| Deaktivierung eines Add-ons
| Wählen Sie das Add-on aus und dann *⋮ -> Deaktivieren*.
| *Deaktiviert*
|===

[NOTE]
====
{harvester-product-name} speichert die Konfigurationsdaten von deaktivierten Add-ons, sodass sie bei der Wiederaktivierung sofort wiederverwendet werden können.
====