= NIC Hotplug
:revdate: 2026-01-02
:page-revdate: {revdate}

{harvester-product-name} suporta hotplugging e hotunplugging de placas de interface de rede (NICs) para máquinas virtuais xref:virtual-machines/live-migration.adoc#_live_migratable_virtual_machines[migráveis ao vivo]. Esse recurso permite que você adicione e remova interfaces de rede de uma máquina virtual em execução sem precisar reiniciar.

[NOTE]
====
Você não pode realizar hotplugging de NIC em máquinas virtuais criadas em clusters que executam versões {harvester-product-name} anteriores à v1.7.0 _se o endereço MAC da interface de rede não foi configurado explicitamente_. Para habilitar esse recurso, você deve reiniciar essas máquinas virtuais. Reiniciar permite que o sistema salve automaticamente os endereços MAC observados na configuração da máquina virtual.

Além disso, máquinas virtuais criadas usando o xref:integrations/rancher/node-driver/node-driver.adoc[Driver de Nó Harvester] e o xref:integrations/terraform/terraform-provider.adoc[Provedor Terraform Harvester] _não suportam_ hotplugging e hotunplugging de NIC.
====

== Hotplug de NICs em uma máquina virtual em execução

. Na interface do {harvester-product-name}, vá para a tela *Máquinas Virtuais*.

. Localize a máquina virtual alvo e, em seguida, selecione *⋮ -> Hotplug de Interface de Rede*.

. Especifique um nome para a interface de rede e selecione uma rede de máquina virtual.
+
Você pode selecionar uma xref:networking/vm-network.adoc#_vlan_network[rede VLAN], uma xref:networking/vm-network.adoc#_untagged_network[rede sem tag] ou uma xref:networking/vm-network.adoc#_vlan_trunk_network[rede trunk VLAN].

. Clique em *Aplicar*.

{harvester-product-name} xref:virtual-machines/live-migration.adoc#_prerequisites[migra a máquina virtual] e a interface especificada é conectada através de ligação de ponte.

Para informações sobre limitações ao número de interfaces hotplugadas, consulte https://kubevirt.io/user-guide/network/hotplug_interfaces/#virtio-limitations[Limitações do Virtio] na documentação do KubeVirt.

== Hotunplug de NICs de uma máquina virtual em execução

[IMPORTANT]
====
Você pode realizar essa ação apenas quando as seguintes condições forem atendidas:

* A máquina virtual tem pelo menos duas interfaces de rede. Você não pode hotunplug a única interface restante.
* A interface alvo está conectada através de ligação de ponte.
====

. Na interface do {harvester-product-name}, vá para a tela *Máquinas Virtuais*.

. Clique no nome da máquina virtual de destino e, em seguida, vá para a aba *Redes*.

. Localize a interface de destino e, em seguida, clique em *Desanexar Interface de Rede*.

{harvester-product-name} xref:virtual-machines/live-migration.adoc#_prerequisites[migra a máquina virtual] e desanexa a interface.