= Máquinas virtuais
:revdate: 2026-01-08
:page-revdate: {revdate}

Você pode criar xref:../virtual-machines/create-vm.adoc[máquinas virtuais Linux] usando um dos seguintes métodos: 

* {harvester-product-name} UI: Na tela *Máquinas Virtuais*, clique em *Criar* e configure as configurações em cada aba. 
* Kubernetes API: Crie um objeto `VirtualMachine`. 
* xref:../integrations/terraform/terraform-provider.adoc[Provedor Terraform Harvester]: Defina um bloco de recurso `harvester_virtualmachine`. 

Criar xref:../virtual-machines/create-windows-vm.adoc[máquinas virtuais Windows] na UI envolve etapas ligeiramente diferentes. {harvester-product-name} fornece um modelo de máquina virtual chamado `windows-iso-image-base-template` que adiciona um volume com os drivers Virtio para Windows, o que simplifica o processo de configuração. Se você precisar de dispositivos Virtio, mas optar por não usar o modelo, deve adicionar seus próprios drivers Virtio para Windows para habilitar a detecção correta de hardware. 

== Sistemas Operacionais Convidados Validados

Os seguintes sistemas operacionais foram validados para rodar em {harvester-product-name} máquinas virtuais:

* SUSE Linux Enterprise Micro 6.0 e 6.1
* SUSE Linux Enterprise Server 15 SP6 e 15 SP7
* Red Hat Enterprise Linux 9 e 10
* Ubuntu 22.04 e 24.04
* Windows 11
* Windows Server 2025

[NOTE]
====
A lista inclui apenas sistemas operacionais testados e não se destina a ser exaustiva. Outros sistemas operacionais também podem rodar em {harvester-product-name} máquinas virtuais. No entanto, os sistemas operacionais convidados devem corresponder à arquitetura dos hosts do {harvester-product-name} cluster. Máquinas virtuais AMD podem ser executadas apenas em clusters AMD, e máquinas virtuais ARM podem ser executadas apenas em clusters ARM.

Você é responsável por obter, ativar e gerenciar licenças para qualquer software comercial que decidir usar. {harvester-product-name} não pode ser responsabilizado por danos ou perda de dados que possam ocorrer devido ao uso de sistemas operacionais não testados, sem correções e desatualizados.

O conteúdo deste documento pode não refletir a situação mais atual e pode mudar a qualquer momento sem aviso prévio.
====