= Netzinstallations-ISO
:revdate: 2025-05-09
:page-revdate: {revdate}

Das Netzinstallations-ISO ist ein minimales Installationsabbild, das nur die grundlegenden Betriebssystemkomponenten enthält, sodass der Installer booten und das Betriebssystem auf einer Festplatte installieren kann. Nach Abschluss der Installation lädt das Betriebssystem alle erforderlichen Containerabbilder aus dem Internet (hauptsächlich von Docker Hub).

Sie können das Netzinstallations-ISO in den folgenden Situationen verwenden:

* Die Implementierung der virtuellen Medien auf einem Server ist fehlerhaft oder langsam. Einige Benutzer haben berichtet, dass die ISO-Umleitung zu langsam ist, um alle Abbilder auf ein System vorzuladen. Für weitere Informationen siehe https://github.com/harvester/harvester/issues/2651[Issue 2651].
* Sie haben ein privates Container-Repository, das alle {harvester-product-name} Abbilder enthält, sowie das Wissen und die Erfahrung, um Abbildspiegel für containerd zu konfigurieren.

[CAUTION]
====
*Sie müssen immer das vollständige ISO verwenden, um ein {harvester-product-name} Cluster neu zu starten* (mit anderen Worten, verwenden Sie das ISO ohne das `-net-install` Suffix). Das vollständige ISO enthält alle erforderlichen Abbilder, und der Installer lädt diese Abbilder während der Installation vor. Sie können leicht das https://docs.docker.com/docker-hub/download-rate-limit/[Docker Hub Rate Limit] erreichen, wenn Sie ein Netzinstallations-ISO verwenden, um das Cluster neu zu starten.
====

== Verwendung

Laden Sie das Netzinstallations-ISO von der GitHub https://github.com/harvester/harvester/releases[Releases] Seite herunter und booten Sie dann das ISO, um {harvester-product-name} zu installieren. Netzinstallations-ISO-Dateinamen haben das Suffix `net-install` (zum Beispiel, https://releases.rancher.com/harvester/v1.3.0/harvester-v1.3.0-amd64-net-install.iso).

== PXE-Installation

Wenn Sie sich entscheiden, das Netzinstallations-ISO als PXE-Installationsquelle zu verwenden, fügen Sie beim Booten des Kernels den folgenden Parameter hinzu:

----
harvester.install.with_net_images=true
----

Für weitere Informationen siehe xref:../../installation-setup/methods/pxe-boot-install.adoc[PXE Boot Installation].
