= Virtual Machines

You can create xref:../virtual-machines/create-vm.adoc[Linux virtual machines] using one of the following methods: 

* {harvester-product-name} UI: On the *Virtual Machines* screen, click *Create* and configure the settings on each tab. 
* Kubernetes API: Create a `VirtualMachine` object. 
* xref:../integrations/terraform/terraform-provider.adoc[Harvester Terraform Provider]: Define a `harvester_virtualmachine` resource block. 

Creating xref:../virtual-machines/create-windows-vm.adoc[Windows virtual machines] on the UI involves slightly different steps. {harvester-product-name} provides a virtual machine template named `windows-iso-image-base-template` that adds a volume with the Virtio drivers for Windows, which streamlines the configuration process. If you require Virtio devices but choose to not use the template, you must add your own Virtio drivers for Windows to enable correct hardware detection. 

== Validated Guest Operating Systems

The following operating systems have been validated to run in {harvester-product-name} virtual machines:

* SUSE Linux Enterprise Micro 6
* SUSE Linux Enterprise Server 15 SP6
* Red Hat Enterprise Linux 9.5
* Ubuntu 24.04
* Windows 11
* Windows Server 2025

[NOTE]
====
The list includes only tested operating systems and is not intended to be exhaustive. Other operating systems may also run in {harvester-product-name} virtual machines. However, guest operating systems must match the architecture of the {harvester-product-name} cluster's hosts. AMD virtual machines can run only on AMD clusters, and ARM virtual machines can run only on ARM clusters.

You are responsible for obtaining, activating, and managing licenses for any commercial software that you decide to use. {harvester-product-name} cannot be held responsible for damage or loss of data that may occur through the use of untested, unpatched, and outdated operating systems.

The contents of this document may not reflect the most current situation and may change at any time without notice.
====