= Conventions de documents
:revdate: 2025-07-16
:page-revdate: {revdate}

== Types de versions

Les termes "Communauté" et "Prime" sont utilisés pour différencier les versions destinées aux utilisateurs de la communauté et aux clients de SUSE. "Prime" fait référence à https://www.suse.com/products/rancher[SUSE Rancher Prime], qui est la plate-forme de gestion de conteneurs d'entreprise de SUSE.

|===
| Type de version | Convention de versionnage | Par exemple : | Cycle de vie du support

| Communauté
| x.y.z
| v1.5.0
| Le support pour chaque version communautaire prend fin lorsque la version x.(y+1).1 est publiée.

| Prime
| x.y.[1-z]
| v1.5.1
| Les versions Prime reçoivent 6 mois de support actif. Cela est suivi de 12 mois de support de maintenance, qui couvre les problèmes critiques liés à la sécurité.
|===

== Étiquettes de version

La documentation {harvester-product-name} utilise les étiquettes suivantes pour décrire les versions du logiciel.

* *Dev*{nbsp}: Le logiciel est en cours de développement actif et n'a pas été testé de manière approfondie. La mise à niveau depuis des versions antérieures ou vers des versions ultérieures n'est pas supportée. Les versions "Dev" se produisent généralement à la fin d'un sprint et peuvent se produire lorsque d'autres définitions de terminé sont respectées.
* *Dernier*{nbsp}: Le logiciel a passé toutes les étapes de vérification et de test. Tous les problèmes connus restants sont considérés comme acceptables.
* *EOL*{nbsp}: Le logiciel a atteint la fin de sa durée de vie utile et aucun entretien au niveau du code n'est fourni. Vous pouvez continuer à utiliser le logiciel dans les termes de l'accord de licence.

== Étiquettes de fonctionnalités :

Les fonctionnalités étiquetées *Expérimental* et *Avant-première technique* offrent un aperçu des innovations à venir et offrent des opportunités de tester de nouvelles technologies dans votre environnement.

* *Expérimental*: La fonctionnalité est incomplète mais son fonctionnement essentiel est opérationnel. Des tests dans un environnement contrôlé ont montré qu'elle peut coexister avec des fonctionnalités stables existantes. En raison des composants manquants et/ou de la fonctionnalité en évolution, la fonctionnalité n'est pas recommandée pour une utilisation dans des environnements de production.
* *Avant-première technique*: La fonctionnalité est presque complète et son fonctionnement ne devrait pas changer de manière significative. Des tests dans un environnement contrôlé ont montré qu'elle peut coexister avec des fonctionnalités stables existantes. Explorez la fonctionnalité en profondeur avant de l'utiliser dans des environnements de production.

Ces fonctionnalités ont les limitations suivantes :

* Encore en développement et peuvent être fonctionnellement incomplètes, instables ou d'une autre manière inadaptées à une utilisation en production.
* Non prise en charge.
* Peut être disponible uniquement pour des architectures matérielles spécifiques. Les détails et la fonctionnalité sont susceptibles de changer. Il en résulte que la mise à niveau vers des versions ultérieures peut être impossible et peut nécessiter une nouvelle installation.
* Peut être supprimé du produit à tout moment. Cela peut se produire, par exemple, si nous découvrons que la fonctionnalité ne répond pas aux besoins des clients ou du marché, ou ne respecte pas les normes de l'entreprise.

[NOTE]
====
Les fonctionnalités *Expérimental* et *Avant-première technique* sont généralement désactivées par défaut. La documentation fournit des informations sur la manière dont vous pouvez activer et configurer de telles fonctionnalités.
====

== Avertissements :

Les admonitions sont des blocs de texte qui fournissent des informations supplémentaires ou importantes. Chaque bloc de texte est marqué par une étiquette et une icône spéciales. La documentation {harvester-product-name} utilise les conventions suivantes pour vous aider à interpréter les informations.

* *Remarque*: Informations supplémentaires qui sont utiles mais non critiques.
* *Important*: Informations qui nécessitent une attention particulière, telles que des changements dans le comportement du produit.
* *Conseil*: Conseils et suggestions utiles, tels que des méthodes alternatives pour accomplir une tâche.
* *Attention*: Informations à prendre en compte avant de procéder à des actions spécifiques, telles que des erreurs qui peuvent survenir.
* *Avertissement*: Informations critiques sur des conséquences nuisibles, telles que des dommages irréversibles et la perte de données.