= Glossaire
:revdate: 2026-01-27
:page-revdate: {revdate}

== *réseau de cluster*

Chemin de transmission isolé pour le trafic réseau dans le {harvester-product-name} cluster.

== *cluster invité* / *cluster Kubernetes invité*

Groupe de machines virtuelles intégrées qui fonctionnent sur un {harvester-product-name} cluster.

Vous pouvez créer des clusters invités RKE2 et K3s en utilisant les interfaces {harvester-product-name} et {rancher-product-name}. La création de clusters invités implique de récupérer des images soit depuis Internet, soit à partir d'un registre privé.

Les clusters invités forment l'infrastructure principale pour exécuter des charges de travail de conteneurs. Certaines versions de {harvester-product-name} et {rancher-product-name} vous permettent de déployer des charges de travail de conteneurs xref:integrations/rancher/rancher-integration.adoc#_bare_metal_container_workload_support_experimental[directement sur des {harvester-product-name} clusters] (avec certaines limitations).

== *nœud invité* / *nœud de cluster invité*

Machine virtuelle qui utilise les ressources du {harvester-product-name} cluster pour exécuter des charges de travail de conteneurs.

Les nœuds invités sont gérés par un plan de contrôle qui contrôle l'activité liée aux pods et maintient l'état souhaité du cluster.

== *{harvester-product-name} cluster*

Groupe de serveurs physiques intégrés (hôtes) sur lesquels l'hyperviseur {harvester-product-name} est installé. Ces serveurs gèrent collectivement les ressources de calcul, de mémoire et de stockage pour fournir un environnement d'exécution pour les machines virtuelles.

Un cluster à trois nœuds est nécessaire pour réaliser pleinement les fonctionnalités multi-nœuds de {harvester-product-name}, en particulier la haute disponibilité. Les dernières versions vous permettent de créer des clusters avec deux nœuds de gestion et un xref:hosts/witness-node.adoc[nœud témoin] (et éventuellement, un ou plusieurs nœuds de travail). Vous pouvez également créer des xref:installation-setup/single-node-clusters.adoc[clusters à nœud unique] qui prennent en charge la plupart des fonctionnalités (à l'exception de la haute disponibilité, du support multi-répliques et de la migration en direct).

Les {harvester-product-name} clusters peuvent être importés et gérés par {rancher-product-name}. Dans ce contexte, un {harvester-product-name} cluster importé est connu sous le nom de "cluster géré" ou "cluster utilisateur en aval" (souvent abrégé en "cluster en aval"). Le terme fait référence à tout cluster Kubernetes qui est connecté à un {rancher-product-name} serveur.

Certaines versions de {harvester-product-name} et {rancher-product-name} vous permettent de déployer des charges de travail de conteneurs directement sur des {harvester-product-name} clusters (avec certaines limitations). Lorsque cette xref:integrations/rancher/rancher-integration.adoc#_bare_metal_container_workload_support_experimental[fonctionnalité expérimentale] est activée, les charges de travail de conteneurs interagissent sans problème avec les charges de travail de machines virtuelles.

== *{harvester-product-name} hyperviseur*

Système d'exploitation spécialisé et xref:introduction/overview.adoc#_architecture[pile logicielle] qui fonctionne sur un seul serveur physique.

== *{harvester-product-name} ISO*

Image d'installation qui contient les composants principaux du système d'exploitation et toutes les images de conteneurs requises, qui sont préchargées lors de l'installation.

== *{harvester-product-name} nœud*

Serveur physique sur lequel l'hyperviseur {harvester-product-name} est installé.

Chaque nœud qui rejoint un {harvester-product-name} cluster doit se voir attribuer un xref:hosts/hosts.adoc#_role_management[rôle] qui détermine les fonctions que le nœud peut effectuer au sein du cluster. Tous les {harvester-product-name} nœuds traitent les données, mais tous ne peuvent pas stocker les données.

== *Fournisseur de Cloud Harvester*

Composant qui permet à un cluster {harvester-product-name} géré par {rancher-short-name} de fonctionner comme un xref:integrations/rancher/cloud-provider.adoc[backend cloud natif pour les clusters Kubernetes invités]. Le Fournisseur de Cloud Harvester intègre le gestionnaire de contrôleur cloud Kubernetes (CCM) et le pilote d'interface de stockage de conteneur (CSI), permettant aux clusters invités de demander et de gérer dynamiquement des ressources {harvester-product-name} natives (équilibreur de charge et stockage) sans intervention manuelle.

== *Pilote CSI Harvester*

Pilote qui xref:integrations/rancher/csi-driver.adoc[fournit une interface de stockage de conteneur standard (CSI) pour les clusters Kubernetes invités], permettant aux charges de travail de conteneur d'utiliser la solution de stockage intégrée au {harvester-product-name} cluster sous-jacent. Ce composant permet la connexion à chaud des volumes aux machines virtuelles pour fournir des performances de stockage natives.

== *Pilote de Nœud Harvester*

Pilote que {rancher-product-name} utilise pour xref:integrations/rancher/node-driver/node-driver.adoc[provisionner des machines virtuelles dans un {harvester-product-name} cluster], et pour lancer et gérer des clusters Kubernetes invités sur ces machines virtuelles.

== *migration en direct*

Processus de xref:virtual-machines/live-migration.adoc[déplacement d'une machine virtuelle en cours d'exécution vers un autre nœud] au sein du même {harvester-product-name} cluster sans interrompre le système d'exploitation invité et provoquer un temps d'arrêt de la charge de travail. La migration en direct ne peut se produire que lorsque les xref:virtual-machines/live-migration.adoc#_prerequisites[prérequis] sont remplis et lorsque les machines virtuelles concernées sont xref:virtual-machines/live-migration.adoc#_live_migratable_virtual_machines[migrables en direct].

== *gestion*

Réseau de cluster xref:networking/cluster-network.adoc#_built_in_cluster_network[créé automatiquement] lors du déploiement du {harvester-product-name} cluster et toujours activé sur tous les hôtes. Le {harvester-product-name} utilise `mgmt` pour les communications intra-cluster et les tâches de gestion du cluster.

== *ISO d'installation réseau*

Image d'installation qui contient uniquement les xref:installation-setup/media/net-install.adoc[composants noyau {harvester-product-name} du système d'exploitation], permettant à l'installateur de démarrer puis d'installer le système d'exploitation sur un disque. Après l'installation, le système d'exploitation récupère toutes les images de conteneur requises depuis Internet.

== *configuration réseau*

Définition de la manière dont un ensemble de nœuds de cluster avec des spécifications réseau uniformes se connecte à un réseau de cluster spécifique.

== *réseau de superposition*

Réseau virtuel représentant un commutateur virtuel de couche 2 qui xref:networking/vm-network.adoc#_overlay_network_experimental[encapsule et transfère le trafic entre les machines virtuelles]. Les réseaux de superposition prennent en charge des capacités avancées de mise en réseau définie par logiciel (SDN) telles que les clouds privés virtuels (VPC) et les sous-réseaux pour les charges de travail des machines virtuelles.

== *réseau de stockage*

Réseau pour xref:networking/storage-network.adoc[isoler le trafic de réplication Longhorn] du trafic intra-cluster sur `mgmt` et d'autres charges de travail à l'échelle du cluster.

== *réseau de tronc VLAN*

Réseau virtuel qui fournit à une machine virtuelle une seule interface réseau pouvant transporter le trafic pour xref:networking/vm-network.adoc#_vlan_trunk_network[plusieurs plages d'ID VLAN qui se chevauchent] simultanément. Lorsqu'une machine virtuelle est connectée à un réseau de tronc VLAN, le système d'exploitation invité et les applications peuvent envoyer et recevoir des paquets étiquetés avec n'importe quel ID VLAN dans la plage spécifiée.

== *réseau de migration de VM*

Réseau pour xref:networking/vm-migration-network.adoc[isoler le trafic de migration de machine virtuelle] du trafic intra-cluster sur `mgmt` et d'autres charges de travail à l'échelle du cluster.

== *réseau de VM*

Réseau virtuel lié à un réseau de cluster spécifique qui permet la communication entre les machines virtuelles et le réseau externe.

== *nœud témoin*

xref:hosts/witness-node.adoc[Nœud non informatique] utilisé uniquement pour maintenir le consensus du cluster. Il garantit que le système peut atteindre une décision majoritaire (quorum) sur les mises à jour du cluster même si un nœud de gestion devient indisponible ou qu'une défaillance réseau se produit.

Les nœuds témoins ne gèrent pas de charges de travail et ne stockent pas de données. Chaque {harvester-product-name} cluster ne peut avoir qu'un seul nœud témoin.