= Présentation
:revdate: 2025-07-16
:page-revdate: {revdate}

{harvester-product-name-tm} est une solution d'infrastructure hyperconvergée (HCI) moderne, ouverte, interopérable et https://en.wikipedia.org/wiki/Hyper-converged_infrastructure[basée sur Kubernetes.] C'est une alternative Open Source conçue pour les opérateurs recherchant une solution HCI https://about.gitlab.com/topics/cloud-native/[natif Cloud]. {harvester-product-name} fonctionne sur des serveurs de matériel sans système d'exploitation et fournit des capacités de virtualisation intégrée et de stockage distribué. En plus des machines virtuelles (VM) traditionnelles, {harvester-product-name} prend en charge les environnements conteneurisés automatiquement grâce à l'intégration avec https://documentation.suse.com/cloudnative/rancher-manager/v2.11/en/integrations/harvester/harvester.html[{rancher-product-name-tm}]. Il offre une solution qui unifie l'infrastructure virtualisée existante, tout en permettant l'adoption de conteneurs à partir tant d'emplacements centraux que d'emplacements périphériques.

== Architecture

L'architecture se compose de technologies Open Source de pointe{nbsp}:

* *Le système d'exploitation Linux.* https://documentation.suse.com/cloudnative/os-manager/[{elemental-product-name}] pour SUSE Linux Enterprise Micro est au cœur de {harvester-product-name} et est une distribution Linux immuable conçue pour supprimer au maximum la maintenance du système d'exploitation dans un cluster Kubernetes.
* *Construit sur Kubernetes.* https://kubernetes.io/[Kubernetes] est devenu le langage d'infrastructure prédominant sur tous les facteurs de forme, et {harvester-product-name} est une solution HCI avec Kubernetes en arrière-plan.
* *Gestion de la virtualisation avec KubeVirt.* https://kubevirt.io/[KubeVirt] fournit une gestion de la virtualisation utilisant KVM sur Kubernetes.
* *Gestion du stockage avec {longhorn-product-name}.* https://documentation.suse.com/cloudnative/storage/1.8/en/longhorn-documentation.html[{longhorn-product-name}] fournit un stockage de blocs distribué et un tiering.
* *Observabilité avec Grafana et Prometheus.* https://grafana.com/[Grafana] et https://prometheus.io/[Prometheus] fournissent une surveillance et une journalisation robustes.

image::architecture.svg[]

== Fonctions

{harvester-product-name} est une plateforme d'infrastructure prête pour l'entreprise et facile à utiliser qui exploite le stockage local, directement attaché, au lieu de SAN externes complexes. Elle utilise l'API Kubernetes comme un langage d'automatisation unifié pour les charges de travail de conteneurs et de VM. Certaines fonctionnalités clés incluent{nbsp}:

* *Facile à prendre en main.* Puisque {harvester-product-name} est livré sous forme d'image d'appliance amorçable, vous pouvez l'installer directement sur un serveur de matériel sans système d'exploitation avec l'https://github.com/harvester/harvester/releases[image ISO] ou l'installer automatiquement en utilisant des scripts xref:../installation-setup/methods/pxe-boot-install.adoc[iPXE].
* *Gestion du cycle de vie des VM.* Créez, modifiez, clonez et supprimez facilement des VM, y compris l'injection de clés SSH, cloud-init, et les consoles graphique et port série.
* *Migration à chaud des VM.* Déplacez une VM vers un autre hôte ou nœud sans temps d'arrêt.
* *Sauvegarde, instantané et restauration des VM.* Sauvegardez vos VM depuis des serveurs NFS, S3 ou des dispositifs NAS. Utilisez votre sauvegarde pour restaurer une VM défaillante ou créer une nouvelle VM sur un autre cluster.
* *Gestion du stockage.* {harvester-product-name} prend en charge le stockage de blocs distribué et le tiering. Les volumes représentent le stockage{nbsp}; vous pouvez facilement créer, modifier, cloner ou exporter un volume.
* *Gestion des réseaux.* Prend en charge l'utilisation d'une adresse IP virtuelle (VIP) et de plusieurs cartes d'interface réseau (NIC). Si vos VMs doivent se connecter au réseau externe, créez un VLAN ou un réseau non étiqueté.
* *Intégration avec {rancher-product-name}.* Accédez à {harvester-product-name} directement via la page de gestion de la virtualisation de {rancher-product-name} et gérez vos charges de travail VM aux côtés de vos clusters Kubernetes.

== Interface utilisateur

{harvester-product-name} fournit une interface web puissante et facile à utiliser pour visualiser et gérer votre infrastructure. Une fois installé, vous pouvez accéder à l'adresse IP de l'interface utilisateur depuis le terminal du nœud.

+++++++++<iframe width="99%" height="450" src="https://www.youtube.com/embed/Ngsk7m6NYf4" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">[]++++++</iframe>+++++++++
