= NIC 热插拔
:revdate: 2026-01-02
:page-revdate: {revdate}

{harvester-product-name} 支持 xref:virtual-machines/live-migration.adoc#_live_migratable_virtual_machines[实时迁移] 虚拟机的网络接口卡 (NIC) 的热插拔和热拔插。此功能允许您在不需要重启的情况下，向正在运行的虚拟机添加和去除网络接口。

[NOTE]
====
_如果网络接口的 MAC 地址未被明确配置_，则不能在运行 {harvester-product-name} 版本早于 v1.7.0 的集群中创建的虚拟机上执行 NIC 热插拔。要启用此功能，您必须重启这些虚拟机。重启允许系统自动将观察到的 MAC 地址保存到虚拟机的配置中。

此外，使用 xref:integrations/rancher/node-driver/node-driver.adoc[Harvester Node Driver] 和 xref:integrations/terraform/terraform-provider.adoc[Harvester Terraform Provider] 创建的虚拟机 _不支持_ NIC 热插拔和热拔插。
====

== 在正在运行的虚拟机上进行 NIC 的热插拔操作。

. 在 {harvester-product-name} 界面上，转到 *虚拟机* 屏幕。

. 找到目标虚拟机，然后选择 *⋮ -> 热插拔网络接口*。

. 为网络接口指定一个名称，并选择一个虚拟机网络。
+
您可以选择 xref:networking/vm-network.adoc#_vlan_network[VLAN 网络]、xref:networking/vm-network.adoc#_untagged_network[无标签网络] 或 xref:networking/vm-network.adoc#_vlan_trunk_network[VLAN 干线网络]。

. 单击 *应用*。

{harvester-product-name} xref:virtual-machines/live-migration.adoc#_prerequisites[迁移虚拟机]，并通过桥接绑定连接指定的接口。

有关热插拔接口数量限制的信息，请参见 KubeVirt 文档中的 https://kubevirt.io/user-guide/network/hotplug_interfaces/#virtio-limitations[Virtio 限制]。

== 在正在运行的虚拟机上进行 NIC 的热拔插操作。

[IMPORTANT]
====
您只能在满足以下条件时执行此操作：

* 虚拟机至少有两个网络接口。您不能热拔插唯一剩余的接口。
* 目标接口通过桥接绑定连接。
====

. 在 {harvester-product-name} 界面上，转到 *虚拟机* 屏幕。

. 点击目标虚拟机的名称，然后转到 *网络* 选项卡。

. 找到目标接口，然后点击 *分离网络接口*。

{harvester-product-name} xref:virtual-machines/live-migration.adoc#_prerequisites[迁移虚拟机]并分离接口。