= 虚拟机
:revdate: 2026-01-08
:page-revdate: {revdate}

您可以使用以下方法创建 xref:../virtual-machines/create-vm.adoc[Linux 虚拟机]：

* {harvester-product-name} UI：在 *虚拟机* 屏幕上，点击 *创建* 并配置每个选项卡上的设置。
* Kubernetes API：创建一个 `VirtualMachine` 对象。
* xref:../integrations/terraform/terraform-provider.adoc[Harvester Terraform 提供者]：定义一个 `harvester_virtualmachine` 资源块。

在 UI 上创建 xref:../virtual-machines/create-windows-vm.adoc[Windows 虚拟机] 涉及稍微不同的步骤。{harvester-product-name} 提供了一个名为 `windows-iso-image-base-template` 的虚拟机模板，该模板添加了带有 Virtio 驱动程序的卷，以简化配置过程。如果您需要 Virtio 设备但选择不使用模板，则必须为 Windows 添加自己的 Virtio 驱动程序，以启用正确的硬件检测。

== 已验证的来宾操作系统

以下操作系统已验证可以在 {harvester-product-name} 虚拟机中运行：

* SUSE Linux Enterprise Micro 6.0 和 6.1
* SUSE Linux Enterprise Server 15 SP6 和 15 SP7
* Red Hat Enterprise Linux 9 和 10
* Ubuntu 22.04 和 24.04
* Windows 11
* Windows Server 2025

[NOTE]
====
该列表仅包括经过测试的操作系统，并不打算详尽无遗。其他操作系统也可能在 {harvester-product-name} 虚拟机中运行。但是，来宾操作系统必须与 {harvester-product-name} 集群主机的架构匹配。AMD 虚拟机只能在 AMD 集群上运行，Arm 虚拟机只能在 Arm 集群上运行。

您有责任获取、激活和管理您决定使用的任何商业软件的许可证。{harvester-product-name} 对因使用未经测试、未修补和过时的操作系统而可能发生的数据损坏或丢失不承担责任。

本文件的内容可能不反映最新情况，并可能随时在不通知的情况下更改。
====