= Glossar
:revdate: 2026-01-27
:page-revdate: {revdate}

== *Cluster-Netzwerk*

Verkehrsisolierter Weiterleitungsweg für die Übertragung von Netzwerkverkehr im {harvester-product-name} Cluster.

== *Gast-Cluster* / *Gast-Kubernetes-Cluster*

Gruppe integrierter virtueller Maschinen, die auf einem {harvester-product-name} Cluster laufen.

Sie können RKE2- und K3s-Gast-Cluster über die {harvester-product-name} und {rancher-product-name} Schnittstellen erstellen. Die Erstellung von Gast-Clustern umfasst das Abrufen von Images aus dem Internet oder einer privaten Registry.

Gast-Cluster bilden die Hauptinfrastruktur für das Ausführen von Container-Workloads. Bestimmte Versionen von {harvester-product-name} und {rancher-product-name} ermöglichen es Ihnen, Container-Workloads xref:integrations/rancher/rancher-integration.adoc#_bare_metal_container_workload_support_experimental[direkt auf {harvester-product-name} Clustern] bereitzustellen (mit einigen Einschränkungen).

== *Gast-Knoten* / *Gast-Cluster-Knoten*

Virtuelle Maschine, die die Ressourcen des {harvester-product-name} Clusters nutzt, um Container-Workloads auszuführen.

Gast-Knoten werden über eine Steuerungsebene verwaltet, die die podbezogene Aktivität steuert und den gewünschten Clusterzustand aufrechterhält.

== *{harvester-product-name} Cluster*

Gruppe integrierter physischer Server (Hosts), auf denen der {harvester-product-name} Hypervisor installiert ist. Diese Server verwalten gemeinsam Rechenressourcen, Arbeitsspeicher und Speicherressourcen, um eine Umgebung für den Betrieb virtueller Maschinen bereitzustellen.

Ein Cluster mit drei Knoten ist erforderlich, um die Multi-Node-Funktionen von {harvester-product-name} vollständig zu realisieren, insbesondere die hohe Verfügbarkeit. Die neuesten Versionen ermöglichen es Ihnen, Cluster mit zwei Verwaltungsknoten und einem xref:hosts/witness-node.adoc[Zeugenknoten] zu erstellen (und optional einen oder mehrere Arbeitsknoten). Sie können auch xref:installation-setup/single-node-clusters.adoc[Einzelknoten-Cluster] erstellen, die die meisten Funktionen unterstützen (außer hoher Verfügbarkeit, Multi-Replikat-Unterstützung und Live-Migration).

{harvester-product-name} Cluster können in {rancher-product-name} importiert und verwaltet werden. In diesem Kontext wird ein importierter {harvester-product-name} Cluster als "verwalteter Cluster" oder "Downstream-Benutzer-Cluster" bezeichnet (häufig abgekürzt als "Downstream-Cluster"). Der Begriff bezieht sich auf jeden Kubernetes-Cluster, der mit einem {rancher-product-name} Server verbunden ist.

Bestimmte Versionen von {harvester-product-name} und {rancher-product-name} ermöglichen es Ihnen, Container-Workloads direkt auf {harvester-product-name} Clustern bereitzustellen (mit einigen Einschränkungen). Wenn dieses xref:integrations/rancher/rancher-integration.adoc#_bare_metal_container_workload_support_experimental[experimentelles Feature] aktiviert ist, interagieren Container-Workloads nahtlos mit virtuellen Maschinen-Workloads.

== *{harvester-product-name} Hypervisor*

Spezialisiertes Betriebssystem und xref:introduction/overview.adoc#_architecture[Software-Stack], das auf einem einzelnen physischen Server läuft.

== *{harvester-product-name} ISO*

Installationsimage, das die Kernkomponenten des Betriebssystems und alle erforderlichen Container-Images enthält, die während der Installation vorab geladen werden.

== *{harvester-product-name} Knoten*

Physischer Server, auf dem der {harvester-product-name} Hypervisor installiert ist.

Jeder Knoten, der einem {harvester-product-name} Cluster beitritt, muss eine xref:hosts/hosts.adoc#_role_management[Rolle] zugewiesen bekommen, die die Funktionen bestimmt, die der Knoten innerhalb des Clusters ausführen kann. Alle {harvester-product-name} Knoten verarbeiten Daten, aber nicht alle können Daten speichern.

== *Harvester Cloud Provider*

Komponente, die es einem {rancher-short-name}-verwalteten {harvester-product-name} Cluster ermöglicht, als xref:integrations/rancher/cloud-provider.adoc[native Cloud-Backend für Gast-Kubernetes-Cluster] zu fungieren. Der Harvester Cloud Provider integriert den Kubernetes Cloud Controller Manager (CCM) und den Container Storage Interface (CSI) Treiber, sodass Gast-Cluster dynamisch {harvester-product-name}-native Ressourcen (Lastenausgleich und Speicher) anfordern und verwalten können, ohne manuelles Eingreifen.

== *Harvester CSI Treiber*

Treiber, der xref:integrations/rancher/csi-driver.adoc[eine standardisierte Container Storage Interface (CSI) für Gast-Kubernetes-Cluster bereitstellt], sodass Container-Workloads die Speicherlösung nutzen können, die mit dem zugrunde liegenden {harvester-product-name} Cluster integriert ist. Diese Komponente ermöglicht das Hot-Plugging von Volumes zu den virtuellen Maschinen, um native Speicherleistung bereitzustellen.

== *Harvester Node Treiber*

Treiber, den {rancher-product-name} verwendet, um xref:integrations/rancher/node-driver/node-driver.adoc[virtuelle Maschinen in einem {harvester-product-name} Cluster bereitzustellen] und um Gast-Kubernetes-Cluster auf diesen virtuellen Maschinen zu starten und zu verwalten.

== *Live-Migration*

Prozess des xref:virtual-machines/live-migration.adoc[Verschiebens einer laufenden virtuellen Maschine zu einem anderen Knoten] innerhalb desselben {harvester-product-name} Clusters, ohne das Gastbetriebssystem zu unterbrechen und Ausfallzeiten der Workloads zu verursachen. Live-Migration kann nur erfolgen, wenn die xref:virtual-machines/live-migration.adoc#_prerequisites[Voraussetzungen] erfüllt sind und wenn die betroffenen virtuellen Maschinen xref:virtual-machines/live-migration.adoc#_live_migratable_virtual_machines[live-migrierbar] sind.

== *mgmt*

Cluster-Netzwerk, das während der {harvester-product-name} Cluster-Bereitstellung xref:networking/cluster-network.adoc#_built_in_cluster_network[automatisch erstellt] wird und auf allen Hosts immer aktiviert ist. {harvester-product-name} verwendet `mgmt` für die Kommunikation innerhalb des Clusters und für Cluster-Management-Aufgaben.

== *Netzinstallations-ISO*

Installationsabbild, das nur die xref:installation-setup/media/net-install.adoc[Kern {harvester-product-name} Betriebssystemkomponenten] enthält, sodass der Installer booten und dann das Betriebssystem auf einer Festplatte installieren kann. Nach Abschluss der Installation zieht das Betriebssystem alle erforderlichen Container-Images aus dem Internet.

== *Netzwerkkonfiguration*

Definition, wie eine Gruppe von Clusterknoten mit einheitlichen Netzwerkspezifikationen sich mit einem bestimmten Cluster-Netzwerk verbindet.

== *Overlay-Netzwerk*

Virtuelles Netzwerk, das einen virtuellen Layer-2-Switch darstellt, der xref:networking/vm-network.adoc#_overlay_network_experimental[Verkehr zwischen virtuellen Maschinen kapselt und weiterleitet]. Overlay-Netzwerke unterstützen fortschrittliche Software-Defined Networking (SDN) Funktionen wie virtuelle private Clouds (VPCs) und Subnetze für Arbeitslasten von virtuellen Maschinen.

== *Speichernetzwerk*

Netzwerk zur xref:networking/storage-network.adoc[Isolierung des Longhorn-Replikationstraffics] vom Intra-Cluster-Traffic auf `mgmt` und anderen clusterweiten Arbeitslasten.

== *VLAN-Trunk-Netzwerk*

Virtuelles Netzwerk, das einer virtuellen Maschine eine einzelne Netzwerkschnittstelle bereitstellt, die gleichzeitig Verkehr für xref:networking/vm-network.adoc#_vlan_trunk_network[mehrere, sich überschneidende VLAN-ID-Bereiche] transportieren kann. Wenn eine virtuelle Maschine an ein VLAN-Trunk-Netzwerk angeschlossen ist, dürfen das Gastbetriebssystem und die Anwendungen Pakete senden und empfangen, die mit einer der VLAN-IDs innerhalb des angegebenen Bereichs gekennzeichnet sind.

== *VM-Migrationsnetzwerk*

Netzwerk zur xref:networking/vm-migration-network.adoc[Isolierung des Verkehrs für die Migration virtueller Maschinen] vom Intra-Cluster-Traffic auf `mgmt` und anderen clusterweiten Arbeitslasten.

== *VM-Netzwerk*

Virtuelles Netzwerk, das mit einem bestimmten Cluster-Netzwerk verbunden ist und die Kommunikation zwischen virtuellen Maschinen und dem externen Netzwerk ermöglicht.

== *Zeugenknoten*

xref:hosts/witness-node.adoc[Nicht-rechnender Knoten] wird ausschließlich zur Aufrechterhaltung des Cluster-Konsenses verwendet. Es stellt sicher, dass das System eine Mehrheitsentscheidung (Quorum) über Cluster-Updates treffen kann, selbst wenn ein Verwaltungs-Knoten nicht verfügbar wird oder ein Netzwerkfehler auftritt.

Zeugenknoten führen keine Arbeitslasten aus und speichern keine Daten. Jeder {harvester-product-name} Cluster kann nur einen Zeugenknoten haben.