= Übersicht
:revdate: 2025-07-16
:page-revdate: {revdate}

{harvester-product-name-tm} ist eine moderne, offene, interoperable, https://en.wikipedia.org/wiki/Hyper-converged_infrastructure[hyperkonvergente Infrastruktur (HCI)] Lösung, die auf Kubernetes basiert. Es ist eine Open-Source-Alternative, die für Betreiber entwickelt wurde, die eine https://about.gitlab.com/topics/cloud-native/[cloudnativ] HCI-Lösung suchen. {harvester-product-name} läuft auf Bare-Metal-Servern und bietet integrierte Virtualisierungs- und verteilte Speicherfähigkeiten. Zusätzlich zu herkömmlichen virtuellen Maschinen (VMs) unterstützt {harvester-product-name} automatisch containerisierte Umgebungen durch die Integration mit https://documentation.suse.com/cloudnative/rancher-manager/v2.11/en/integrations/harvester/harvester.html[{rancher-product-name-tm}]. Es bietet eine Lösung, die die bestehende virtualisierte Infrastruktur vereinheitlicht und gleichzeitig die Einführung von Containern vom Kern bis zu den Randstandorten ermöglicht.

== Architektur

Die Architektur besteht aus modernsten Open-Source-Technologien:

* *Linux-OS.* https://documentation.suse.com/cloudnative/os-manager/[{elemental-product-name}] für SUSE Linux Enterprise Micro steht im Mittelpunkt von {harvester-product-name} und ist eine unveränderliche Linux-Distribution, die darauf ausgelegt ist, so viel OS-Wartung wie möglich in einem Kubernetes-Cluster zu entfernen.
* *Auf Kubernetes aufgebaut.* https://kubernetes.io/[Kubernetes] ist zur vorherrschenden Infrastruktur-Sprache über alle Formfaktoren hinweg geworden, und {harvester-product-name} ist eine HCI-Lösung mit Kubernetes im Hintergrund.
* *Virtualisierungsmanagement mit KubeVirt.* https://kubevirt.io/[KubeVirt] bietet Virtualisierungsmanagement mit KVM auf Kubernetes.
* *Speicherverwaltung mit {longhorn-product-name}.* https://documentation.suse.com/cloudnative/storage/1.8/en/longhorn-documentation.html[{longhorn-product-name}] bietet verteilten Blockspeicher und Tiering.
* *Einblick mit Grafana und Prometheus.* https://grafana.com/[Grafana] und https://prometheus.io/[Prometheus] bieten robustes Monitoring und Logging.

image::architecture.svg[]

== Funktionen

{harvester-product-name} ist eine unternehmensbereite, benutzerfreundliche Infrastrukturplattform, die lokalen, direkt angeschlossenen Speicher anstelle komplexer externer SANs nutzt. Es nutzt die Kubernetes-API als einheitliche Automatisierungssprache für Container- und VM-Workloads. Einige wichtige Funktionen sind:

* *Einfach zu starten.* Da {harvester-product-name} als bootfähiges Appliance-Image geliefert wird, können Sie es direkt auf einem Bare-Metal-Server mit dem https://github.com/harvester/harvester/releases[ISO-Image] installieren oder automatisch mit xref:../installation-setup/methods/pxe-boot-install.adoc[iPXE]-Skripte installieren.
* *VM-Lebenszyklusmanagement.* Ermöglicht das einfache Erstellen, Bearbeiten, Klonen und Löschen von VMs – inklusive SSH-Key-Injektion, cloud-init sowie grafischer und serieller Portkonsole.
* *VM-Live-Migration.* Verschieben Sie eine VM zu einem anderen Host oder Knoten ohne Ausfallzeit.
* *VM-Backup, Snapshot und Wiederherstellung.* Sichern Sie Ihre VMs von NFS-, S3-Servern oder NAS-Geräten. Verwenden Sie Ihr Backup, um eine fehlgeschlagene VM wiederherzustellen oder eine neue VM in einem anderen Cluster zu erstellen.
* *Speicherverwaltung.* {harvester-product-name} unterstützt verteilten Blockspeicher und Tiering. Volumes repräsentieren Speicher; Sie können ganz einfach ein Volume erstellen, bearbeiten, klonen oder exportieren.
* *Netzwerkverwaltung.* Unterstützt die Verwendung einer virtuellen IP (VIP) und mehrerer Netzwerkschnittstellen (NICs). Wenn Ihre VMs eine Verbindung zum externen Netzwerk benötigen, erstellen Sie ein VLAN oder ein untagged Netzwerk.
* *Integration mit {rancher-product-name}.* Greifen Sie direkt über die Virtualisierungsverwaltungsseite von {rancher-product-name} auf {harvester-product-name} zu und verwalten Sie Ihre VM-Workloads neben Ihren Kubernetes-Clustern.

== User Interface

{harvester-product-name} bietet eine leistungsstarke und benutzerfreundliche webbasierte Schnittstelle zur Visualisierung und Verwaltung Ihrer Infrastruktur. Nach der Installation können Sie die IP-Adresse für die Benutzeroberfläche über das Terminal des Knotens aufrufen.

+++++++++<iframe width="99%" height="450" src="https://www.youtube.com/embed/Ngsk7m6NYf4" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">[]++++++</iframe>+++++++++
