= Conexión en caliente de NIC
:revdate: 2026-01-02
:page-revdate: {revdate}

{harvester-product-name} admite la conexión y desconexión en caliente de controladores de interfaz de red (NIC) para máquinas virtuales xref:virtual-machines/live-migration.adoc#_live_migratable_virtual_machines[migrables en vivo]. Esta función permite añadir y eliminar interfaces de red de una máquina virtual en ejecución sin necesidad de reiniciar.

[NOTE]
====
No se puede realizar la conexión en caliente de NIC en máquinas virtuales creadas en clústeres que ejecutan versiones de {harvester-product-name} anteriores a v1.7.0 _si la dirección MAC de la interfaz de red no fue configurada explícitamente_. Para habilitar esta función, debes reiniciar esas máquinas virtuales. Reiniciar permite al sistema guardar automáticamente las direcciones MAC observadas en la configuración de la máquina virtual.

Además, las máquinas virtuales creadas utilizando el xref:integrations/rancher/node-driver/node-driver.adoc[Harvester Node Driver] y el xref:integrations/terraform/terraform-provider.adoc[Harvester Terraform Provider] _no admiten_ la conexión y desconexión en caliente de NIC.
====

== Conectar NIC en caliente a una máquina virtual en ejecución

. En la interfaz de usuario de {harvester-product-name}, ve a la pantalla de *Máquinas Virtuales*.

. Localiza la máquina virtual objetivo y luego selecciona *⋮ -> Conectar Interfaz de Red en Caliente*.

. Especifica un nombre para la interfaz de red y selecciona una red de máquina virtual.
+
Puedes seleccionar una xref:networking/vm-network.adoc#_vlan_network[red VLAN], una xref:networking/vm-network.adoc#_untagged_network[red sin etiquetar] o una xref:networking/vm-network.adoc#_vlan_trunk_network[red troncal VLAN].

. Haz clic en *Aplicar*.

{harvester-product-name} xref:virtual-machines/live-migration.adoc#_prerequisites[migra la máquina virtual] y la interfaz especificada se conecta a través de enlace de puente.

Para información sobre las limitaciones en el número de interfaces conectadas en caliente, consulta https://kubevirt.io/user-guide/network/hotplug_interfaces/#virtio-limitations[Limitaciones de Virtio] en la documentación de KubeVirt.

== Desconectar NIC en caliente de una máquina virtual en ejecución

[IMPORTANT]
====
Puedes realizar esta acción solo cuando se cumplan las siguientes condiciones:

* La máquina virtual tiene al menos dos interfaces de red. No puedes desconectar en caliente la única interfaz restante.
* La interfaz objetivo está conectada a través de enlace de puente.
====

. En la interfaz de usuario de {harvester-product-name}, ve a la pantalla de *Máquinas Virtuales*.

. Haz clic en el nombre de la máquina virtual de destino y luego ve a la pestaña *Redes*.

. Localiza la interfaz de destino y luego haz clic en *Desvincular interfaz de red*.

{harvester-product-name} xref:virtual-machines/live-migration.adoc#_prerequisites[migra la máquina virtual] y desvincula la interfaz.