= Máquinas virtuales
:revdate: 2026-01-08
:page-revdate: {revdate}

Puedes crear xref:../virtual-machines/create-vm.adoc[máquinas virtuales Linux] utilizando uno de los siguientes métodos: 

* {harvester-product-name} Interfaz de usuario: En la pantalla *Máquinas Virtuales*, haz clic en *Crear* y configura los ajustes en cada pestaña. 
* Kubernetes API: Crea un objeto `VirtualMachine`. 
* xref:../integrations/terraform/terraform-provider.adoc[Proveedor de Terraform Harvester]: Define un bloque de recursos `harvester_virtualmachine`. 

Crear xref:../virtual-machines/create-windows-vm.adoc[máquinas virtuales Windows] en la interfaz de usuario implica pasos ligeramente diferentes. {harvester-product-name} proporciona una plantilla de máquina virtual llamada `windows-iso-image-base-template` que añade un volumen con los controladores Virtio para Windows, lo que agiliza el proceso de configuración. Si necesitas dispositivos Virtio pero decides no usar la plantilla, debes añadir tus propios controladores Virtio para Windows para habilitar la detección correcta del hardware. 

== Sistemas Operativos Invitados Validados

Los siguientes sistemas operativos han sido validados para funcionar en {harvester-product-name} máquinas virtuales:

* SUSE Linux Enterprise Micro 6.0 y 6.1
* SUSE Linux Enterprise Server 15 SP6 y 15 SP7
* Red Hat Enterprise Linux 9 y 10
* Ubuntu 22.04 y 24.04
* Windows 11
* Windows Server 2025

[NOTE]
====
La lista incluye solo sistemas operativos probados y no pretende ser exhaustiva. Otros sistemas operativos también pueden funcionar en {harvester-product-name} máquinas virtuales. Sin embargo, los sistemas operativos invitados deben coincidir con la arquitectura de los {harvester-product-name} hosts del clúster. Las máquinas virtuales AMD solo pueden ejecutarse en clústeres AMD, y las máquinas virtuales ARM solo pueden ejecutarse en clústeres ARM.

Usted es responsable de obtener, activar y gestionar las licencias de cualquier software comercial que decida utilizar. {harvester-product-name} no puede ser considerado responsable por daños o pérdida de datos que puedan ocurrir debido al uso de sistemas operativos no probados, sin parches y obsoletos.

El contenido de este documento puede no reflejar la situación más actual y puede cambiar en cualquier momento sin previo aviso.
====