= {harvester-product-name} v1.7.1 Release Notes
:revdate: 2026-07-30
:page-revdate: {revdate}

This release introduces several features, enhancements, and bug fixes that improve system quality and the overall user experience. The documentation is available at https://documentation.suse.com/cloudnative/virtualization/v1.7/en/introduction/overview.html.

== Downloads

=== AMD64

==== Full ISO

* https://releases.rancher.com/harvester/v1.7.1/harvester-v1.7.1-amd64.iso
* https://releases.rancher.com/harvester/v1.7.1/harvester-v1.7.1-vmlinuz-amd64
* https://releases.rancher.com/harvester/v1.7.1/harvester-v1.7.1-initrd-amd64
* https://releases.rancher.com/harvester/v1.7.1/harvester-v1.7.1-rootfs-amd64.squashfs
* https://releases.rancher.com/harvester/v1.7.1/harvester-v1.7.1-amd64.sha512
* https://releases.rancher.com/harvester/v1.7.1/version.yaml

==== Net install ISO

* https://releases.rancher.com/harvester/v1.7.1/harvester-v1.7.1-amd64-net-install.iso

=== ARM64

* https://releases.rancher.com/harvester/v1.7.1/harvester-v1.7.1-arm64.iso
* https://releases.rancher.com/harvester/v1.7.1/harvester-v1.7.1-vmlinuz-arm64
* https://releases.rancher.com/harvester/v1.7.1/harvester-v1.7.1-initrd-arm64
* https://releases.rancher.com/harvester/v1.7.1/harvester-v1.7.1-rootfs-arm64.squashfs
* https://releases.rancher.com/harvester/v1.7.1/harvester-v1.7.1-arm64.sha512
* https://releases.rancher.com/harvester/v1.7.1/version-arm64.yaml

== Installation

{harvester-product-name} can be installed using the https://documentation.suse.com/cloudnative/virtualization/v1.7/en/installation-setup/methods/iso-install.html[ISO image], a https://documentation.suse.com/cloudnative/virtualization/v1.7/en/installation-setup/methods/usb-install.html[bootable USB drive], and https://documentation.suse.com/cloudnative/virtualization/v1.7/en/installation-setup/methods/pxe-boot-install.html[PXE boot]. For more information, see the https://documentation.suse.com/cloudnative/virtualization/v1.7/en/installation-setup/requirements.html[Installation] section of the documentation.

[IMPORTANT]
====
The {harvester-product-name} installer checks if the hardware meets the https://documentation.suse.com/cloudnative/virtualization/v1.7/en/installation-setup/requirements.html#_hardware_requirements[minimum requirements] for production use. If any of the checks fail, installation is stopped and warnings are printed to the system console. You can disable this behavior during iPXE installation (for testing purposes) by adding the kernel parameter https://documentation.suse.com/cloudnative/virtualization/v1.7/en/installation-setup/methods/pxe-boot-install.html#_harvester_install_skipcheckstrue[`harvester.install.skipchecks=true`] when you boot the system.

Starting with v1.7, the installation process includes a mandatory step for configuring the login password for the default `rancher` user account.
====

== Upgrades

{harvester-product-name} only allows upgrades from supported versions. For more information about upgrade paths and procedures, see https://documentation.suse.com/cloudnative/virtualization/v1.7/en/upgrades/upgrades.html[Upgrades].

[IMPORTANT]
====
{harvester-product-name} v1.7 transitions from wicked to NetworkManager for network management. If the management interface configuration was modified after installation, manual steps are required before upgrading to prevent errors. For more information, see https://documentation.suse.com/cloudnative/virtualization/v1.7/en/upgrades/v1-6-x-to-v1-7-x.html#_migration_wicked_to_networkmanager[Migration from wicked to NetworkManager].
====

== Highlights

=== Experimental features

==== Automatic virtual machine workload rebalancing

The *Virtual Machine Auto Balance* add-on allows {harvester-product-name} to leverage the Kubernetes Descheduler for rebalancing of virtual machine workloads. When enabled on a multi-node cluster, the add-on deploys the Descheduler and a related configuration. The Descheduler evicts pods that are not optimally placed according to administrator-defined policies, enhancing resource utilization and improving cluster performance.

https://youtu.be/LF_df4GYUxg[Demo] | https://documentation.suse.com/cloudnative/virtualization/v1.7/en/add-ons/virtual-machine-auto-balance.html[Documentation] | https://github.com/harvester/harvester/issues/2311[GitHub issue]

=== Fully supported features

==== MIG-backed vGPU device support

{harvester-product-name} automatically detects GPUs that support Multi-Instance GPU (MIG)-based partitioning. In v1.7, virtual machines can share vGPU devices backed by NVIDIA GPUs with this capability (such as the A100, H100, and H200). To leverage this feature, you must define the MIG profiles for your GPU, enable the MIG configuration, and enable the vGPU device associated with the MIG configuration.

https://youtu.be/lWdVT8SOfPs[Demo] | https://documentation.suse.com/cloudnative/virtualization/v1.7/en/hosts/vgpu-support.html#_mig_backed_vgpu_devices[Documentation] | https://github.com/harvester/harvester/issues/8652[GitHub issue]

==== Multipath device recognition and management

Starting with v1.7, {harvester-product-name} supports external storage devices that use multipath I/O (MPIO) to provide redundant data paths while preventing device identification conflicts. Through the `os.externalStorageConfig` setting, you can define the precise configuration (including device blacklisting and whitelisting) that the multipath daemon uses to manage devices and ensure storage stability.

https://youtu.be/CQFf9vbcqX0[Demo] | https://documentation.suse.com/cloudnative/virtualization/v1.7/en/installation-setup/config/configuration-file.html#_os_externalstorageconfig[Documentation] | https://github.com/harvester/harvester/issues/6975[GitHub issue]

==== NIC hotplugging and hotunplugging

{harvester-product-name} v1.7 allows you to add and remove network interface controllers (NICs) from running live-migratable virtual machines without downtime. When you hotplug a NIC, {harvester-product-name} migrates the virtual machine and connects the specified interface through bridge binding. Virtual machines that were created using the Harvester Node Driver and the Harvester Terraform Provider _do not support_ this feature.

https://youtu.be/x3QA_Bj8lJc[Demo] | https://documentation.suse.com/cloudnative/virtualization/v1.7/en/virtual-machines/nic-hotplug.html[Documentation] | https://github.com/harvester/harvester/issues/7042[GitHub issue]

==== Open Virtual Format (OVF) support

In {harvester-product-name} v1.7, you can use the *VM Import Controller* add-on to import virtual machines using Open Virtual Appliance (OVA) files, which are a single-file version of OVF packages. {harvester-product-name} supports downloading these OVA files via both HTTP and HTTPS. For endpoints that use HTTPS, you can configure a secret that includes basic authentication credentials for the URL and a CA certificate.

https://youtu.be/bJ7Ti1-GsU0[Demo] | https://documentation.suse.com/cloudnative/virtualization/v1.7/en/add-ons/vm-import-controller.html[Documentation] | https://github.com/harvester/harvester/issues/4742[GitHub issue]

==== Pausable node upgrades

{harvester-product-name} v1.7 introduces a new option to the `upgrade-config` setting that enables pausing of automatic node upgrades for all or specific cluster nodes. This capability is essential for scenarios requiring manual maintenance or verification on the nodes before the upgrade continues. Once these tasks are completed, you must then explicitly instruct {harvester-product-name} to resume the upgrade process on the target nodes.

https://youtu.be/h4t6WNlaNtw[Demo] | https://documentation.suse.com/cloudnative/virtualization/v1.7/en/upgrades/upgrades.html#_pausing_node_upgrades[Documentation] | https://github.com/harvester/harvester/issues/8980[GitHub issue]

==== Transparent hugepages configuration

Hugepages allow the Linux kernel to allocate memory in chunks larger than the default size. In {harvester-product-name} v1.7, you can configure transparent hugepage settings for each node to increase the overall system performance. Additionally, you can monitor memory allocation for both anonymous (transparent) and persistent (static) hugepages on the {harvester-product-name} UI.

https://youtu.be/KqGcbfCoLgo[Demo] | https://documentation.suse.com/cloudnative/virtualization/v1.7/en/hosts/hosts.html#_hugepages[Documentation] | https://github.com/harvester/harvester/issues/5006[GitHub issue]

==== Virtual machine VLAN trunking

{harvester-product-name} v1.7 allows you to create VLAN trunk networks with multiple, overlapping VLAN ID ranges. When a virtual machine is attached to a VLAN trunk network, the guest operating system and applications are allowed to send and receive packets tagged with any of the VLAN IDs within the specified range.

https://youtu.be/3Gn095RxE-M[Demo] | https://documentation.suse.com/cloudnative/virtualization/v1.7/en/networking/vm-network.html#_vlan_trunk_network[Documentation] | https://github.com/harvester/harvester/issues/766[GitHub issue]

==== Volume snapshots in guest clusters

v0.1.25 of the Harvester CSI Driver supports volume snapshots, providing point-in-time snapshots and restoration for guest cluster workloads. You can create, list, and delete snapshots of persistent volumes, and create new volumes from existing snapshots. To use this feature, you must ensure that the CSI snapshot controller and the required manifests are deployed on the guest cluster.

Harvester CSI Driver v0.1.25 is used in the following {rke2-product-name} versions:

* https://github.com/rancher/rke2/blob/v1.31.14%2Brke2r1/charts/chart_versions.yaml[v1.31.14+rke2r1]
* https://github.com/rancher/rke2/blob/v1.32.10%2Brke2r1/charts/chart_versions.yaml[v1.32.10+rke2r1]
* https://github.com/rancher/rke2/blob/v1.33.6%2Brke2r1/charts/chart_versions.yaml[v1.33.6+rke2r1]
* https://github.com/rancher/rke2/blob/v1.34.2%2Brke2r1/charts/chart_versions.yaml[v1.34.2+rke2r1]

https://youtu.be/VLY-YCIgHsE[Demo] | https://documentation.suse.com/cloudnative/virtualization/v1.7/en/integrations/rancher/csi-driver.html#_volume_snapshots[Documentation] | https://github.com/harvester/harvester/issues/3778[GitHub issue]

== Security fixes

The interactive installer now allows you to reset the operating system's default login password before proceeding to other configuration screens, ensuring the password is updated before remote network access to the host is enabled. This prevents attackers from gaining unauthorized network access to the host via a remote shell (SSH) in environments that are exposed to untrusted locations. For more information, see the security advisory for https://github.com/harvester/harvester/security/advisories/GHSA-6g8q-hp2j-gvwv[CVE-2025-62877].

== Deprecations and removals 

=== Legacy BIOS booting

Support for legacy BIOS booting is deprecated in v1.7 and will be removed in a later release. Existing {harvester-product-name} clusters that use this boot mode will continue to function, but upgrading to later versions may require re-installation in UEFI mode. To avoid issues and disruptions, use UEFI in new installations.

== Bug fixes

* https://github.com/harvester/harvester/issues/10012[#10012] [BUG] Can't restore from snapshot replace existing
* https://github.com/harvester/harvester/issues/9979[#9979] [backport v1.7] [BUG] Upgrading from v1.6.x to v1.7.0 stuck due to the incomplete kubeovn-operator upgrade
* https://github.com/harvester/harvester/issues/9976[#9976] [BUG] Addon managed DHCP is not working on Harvester 1.7.1-rc2
* https://github.com/harvester/harvester/issues/9965[#9965] [backport v1.7] [BUG] upgrade stuck due to the mismatch instance-manager checksum
* https://github.com/harvester/harvester/issues/9947[#9947] [backport v1.7] [BUG] Upgrading to v1.7.1-rc1 is stuck due to longhorn-manager image handle mismatch
* https://github.com/harvester/harvester/issues/9931[#9931] [BUG] Failed to upload Harvester ISO to create upgrade image in server-version setting
* https://github.com/harvester/harvester/issues/9926[#9926] [backport v1.7] [BUG] Not able to create VirtualMachines with persistent vTPM and UEFI on Harvester 1.7.0 version 
* https://github.com/harvester/harvester/issues/9872[#9872] [backport v1.7] [GUI] [BUG] Raw image upload breaks when using external storage
* https://github.com/harvester/harvester/issues/9869[#9869] [backport v1.7] [BUG] Raw image upload breaks when using external storage
* https://github.com/harvester/harvester/issues/9861[#9861] [backport v1.7] [BUG] Failed upgrade from 1.6.1 to 1.7.0
* https://github.com/harvester/harvester/issues/9830[#9830] [backport v1.7] [BUG] VMs cannot get IPs from vm-dhcp-controller when names differ in IPPool and NAD
* https://github.com/harvester/harvester/issues/9789[#9789] [backport v1.7] [BUG] VMs created from a template which is generated from another VM cannot boot after shutdown 
* https://github.com/harvester/harvester/issues/9787[#9787] [backport v1.7] [BUG] Fail to enable the kubeovn-operator add-on in Harvester v1.7.0
* https://github.com/harvester/harvester/issues/9783[#9783] [backport v1.7] [BUG] fine tune UI logic to not inject maxSockets on arm clusters
* https://github.com/harvester/harvester/issues/9781[#9781] [backport v1.7] [BUG] Upgrade from v1.6.x to v1.7.x may result in host IP address change when using DHCP
* https://github.com/harvester/harvester/issues/9758[#9758] [BUG] All VMs was Off after migrate from v1.6.0 to v1.7.0-rc7 caused by vm migration failed
* https://github.com/harvester/harvester/issues/9722[#9722] [backport v1.7] [BUG] Can't completely delete airgapped upgrade image when clicking delete button, prompt error message
* https://github.com/harvester/harvester/issues/9707[#9707] [backport v1.7] [BUG] Click `View in API` of resource always direct to empty page
* https://github.com/harvester/harvester/issues/9675[#9675] [backport v1.7] [BUG] Add bridged virtio NIC to VM via Edit Config triggers live migration on single node cluster
* https://github.com/harvester/harvester/issues/9635[#9635] [backport v1.7] [BUG] Can not hot-plugging on a VM has management network with bridge-bond and virtio
* https://github.com/harvester/harvester/issues/9634[#9634] [backport v1.7] [BUG] Add Network via Edit Config triggers hotplug NIC before user choosing on popup box
* https://github.com/harvester/harvester/issues/9591[#9591] [backport v1.7] [BUG] terraform apply same logic storage-network setting cannot pass
* https://github.com/harvester/harvester/issues/9542[#9542] [backport v1.7] [BUG] Clone VM, but the cloned one stuck in starting
* https://github.com/harvester/harvester/issues/5186[#5186] [BUG] Cannot create Image from URL with query string
* https://github.com/harvester/harvester/issues/9760[#9760] [backport v1.7] [BUG] Node status shows Cordoned when the node is powered off
* https://github.com/harvester/harvester/issues/9756[#9756] [backport v1.7] [BUG] Enable/DisableCPUManager return 500 not 400 when Enable/DisableCPUManager on node already enable/disable

== Known issues

This section includes only issues identified before the release date. For information about all issues associated with v1.7.1, see https://github.com/harvester/harvester/issues?q=is:issue%20label:known-issue-v1.7.1[this page].

* https://github.com/harvester/harvester/issues/9399[#9399] [BUG] PCI vGPU USB device failed to pass through due to . in the hostDevices.name
* https://github.com/harvester/harvester/issues/9597[#9597] [BUG] Upgrade v1.7.0 stuck in node post-draining
* https://github.com/harvester/harvester/issues/9619[#9619] [BUG] Add Network via Edit Config triggers hotplug NIC before user choosing on popup box
* https://github.com/harvester/harvester/issues/9660[#9660] [BUG] Add bridged virtio NIC to VM via Edit Config triggers live migration on single node cluster
* https://github.com/harvester/harvester/issues/9714[#9714] [BUG] LH v2 Snapshot Stuck in Deletion
* https://github.com/harvester/harvester/issues/9738[#9738] [BUG] Upgrade stuck indefinitely at the apply-manifest phase due to the pending-upgrade fleet
* https://github.com/harvester/harvester/issues/9751[#9751] [BUG] After upgrade from v1.6.1 to v1.7.0-rc6, Running VM show message "Restart action is required ..."
* https://github.com/harvester/harvester/issues/9990[#9990] [BUG] When upgrade, wrong ISO checksum doest not detect and report by the system

== Components

|===
| Component | Version

| CDI
| https://github.com/kubevirt/containerized-data-importer/releases/tag/v1.62.0[v1.62.0]

| Kube-OVN
| https://github.com/kubeovn/kube-ovn/releases/tag/v1.14.10[v1.14.10]

| KubeVirt
| https://github.com/kubevirt/kubevirt/releases/tag/v1.6.3[v1.6.3]

| {longhorn-product-name-tm}
| https://github.com/longhorn/longhorn/releases/tag/v1.10.2[v1.10.2]

| {rancher-product-name-tm} (embedded)
| https://github.com/rancher/rancher/releases/tag/v2.13.1[v2.13.1]

| {rke2-product-name}
| https://github.com/rancher/rke2/releases/tag/v1.34.3%2Brke2r3[v1.34.3+rke2r3]

| SUSE Linux Micro
| https://github.com/harvester/os2/releases/tag/v1.7-20260209[6.1]
|===
