= Upgrade from v1.1.2/v1.1.3/v1.2.0 to v1.2.1

== Important changes to this version

Harvester `v1.2.1` fixes upgrade known issues found in `v1.2.0`, we suggest upgrading `v1.1.2`, `v1.1.3`, or `v1.2.0` clusters to `v1.2.1`. The known issues found in `v1.2.0` are:

* xref:./v1-1-2-to-v1-2-0.adoc#_9_an_upgrade_is_stuck_in_the_post_draining_state[An Upgrade is stuck in the Post-draining state]
* xref:./v1-1-2-to-v1-2-0.adoc#_10_an_upgrade_is_stuck_in_the_upgrading_system_service_state_due_to_the_customer_provided_ssl_certificate_without_ip_san_error_in_fleet_agent[An upgrade is stuck in the Upgrading System Service state due to the customer provided SSL certificate without IP SAN error in fleet-agent]

For clusters already upgraded to v1.2.0, please refer to the https://github.com/harvester/harvester/releases/tag/v1.2.1[release note] for new changes.

== General information

[TIP]
====
Before you start an upgrade, you can run the pre-check script to make sure the cluster is in a stable state. For more details, please visit this https://github.com/harvester/upgrade-helpers/tree/main/pre-check/v1.1.x[URL] for the script.
====

Once there is an upgradable version, the Harvester GUI Dashboard page will show an upgrade button. For more details, please refer to xref:./automatic.adoc#_start_an_upgrade[start an upgrade].

For the air-gap env upgrade, please refer to xref:./automatic.adoc#_prepare_an_air_gapped_upgrade[prepare an air-gapped upgrade].

== Known issues

Please check v1.2.0 xref:./v1-1-2-to-v1-2-0.adoc#_known_issues[known issues].
