= ISO de instalación por red
:revdate: 2025-05-09
:page-revdate: {revdate}

La ISO de instalación por red es una imagen de instalación mínima que contiene solo el núcleo del sistema operativo, permitiendo que el instalador arranque y luego instale el sistema operativo en un disco. Una vez completada la instalación, el sistema operativo descarga todas las imágenes de contenedor requeridas de internet (principalmente de Docker Hub).

Puedes utilizar la ISO de instalación por red en las siguientes situaciones:

* La implementación de medios virtuales en un servidor es defectuosa o lenta. Algunos usuarios han informado que la redirección de ISO es demasiado lenta para precargar todas las imágenes en un sistema. Para obtener más información, consulta https://github.com/harvester/harvester/issues/2651[Problema 2651].
* Tienes un registro privado que contiene todas {harvester-product-name} las imágenes, así como el conocimiento y la experiencia necesarios para configurar espejos de imágenes para containerd.

[CAUTION]
====
*Siempre debes utilizar la ISO completa para iniciar un clúster {harvester-product-name}* (en otras palabras, utiliza la ISO sin el sufijo `-net-install`). La ISO completa contiene todas las imágenes requeridas, y el instalador precarga esas imágenes durante la instalación. Puedes alcanzar fácilmente el https://docs.docker.com/docker-hub/download-rate-limit/[Límite de tasa de Docker Hub] al utilizar una ISO de instalación por red para iniciar el clúster.
====

== Uso

Descarga la ISO de instalación por red desde la página de https://github.com/harvester/harvester/releases[Versiones] de GitHub, y luego arranca la ISO para instalar {harvester-product-name}. Los nombres de archivo de la ISO de instalación por red tienen el sufijo `net-install` (por ejemplo, https://releases.rancher.com/harvester/v1.3.0/harvester-v1.3.0-amd64-net-install.iso).

== Instalación PXE

Si decides utilizar la ISO de instalación por red como origen de instalación PXE, añade el siguiente parámetro al arrancar el núcleo:

----
harvester.install.with_net_images=true
----

Para obtener más información, consulta xref:../../installation-setup/methods/pxe-boot-install.adoc[Instalación de arranque PXE].
