= Mise à niveau de v1.1.2/v1.1.3/v1.2.0 à v1.2.1
:revdate: 2025-05-09
:page-revdate: {revdate}

== Changements importants dans cette version

Le Harvester `v1.2.1` corrige les problèmes connus de mise à niveau trouvés dans `v1.2.0`, nous vous suggérons de mettre à niveau les clusters `v1.1.2`, `v1.1.3` ou `v1.2.0` vers `v1.2.1`. Les problèmes connus trouvés dans `v1.2.0` sont{nbsp}:

* xref:./v1-1-2-to-v1-2-0.adoc#_9_an_upgrade_is_stuck_in_the_post_draining_state[Une mise à niveau est bloquée dans l'état Post-draining]
* xref:./v1-1-2-to-v1-2-0.adoc#_10_an_upgrade_is_stuck_in_the_upgrading_system_service_state_due_to_the_customer_provided_ssl_certificate_without_ip_san_error_in_fleet_agent[Une mise à niveau est bloquée dans l'état de mise à niveau du service système en raison de l'erreur du certificat SSL fourni par le client, lequel ne comporte pas d'IP SAN, dans le fleet-agent]

Pour les clusters déjà mis à niveau vers v1.2.0, veuillez vous référer à la https://github.com/harvester/harvester/releases/tag/v1.2.1[note de version] pour les nouveaux changements.

== informations générales

[TIP]
====
Avant de commencer une mise à niveau, vous pouvez exécuter le script de pré-vérification pour vous assurer que le cluster est dans un état stable. Pour plus de détails, veuillez visiter ce https://github.com/harvester/upgrade-helpers/tree/main/pre-check/v1.1.x[URL] pour le script.
====

Une fois qu'il y a une version pouvant être mise à niveau, la page du tableau de bord GUI du Harvester affichera un bouton de mise à niveau. Pour plus de détails, veuillez vous référer à xref:./upgrades.adoc#_start_an_upgrade[démarrer une mise à niveau].

Pour la mise à niveau de l'environnement à isolation physique, veuillez vous référer à xref:./upgrades.adoc#_prepare_an_air_gapped_upgrade[préparer une mise à niveau isolée physiquement].

== Problèmes connus

Veuillez vérifier les xref:./v1-1-2-to-v1-2-0.adoc#_known_issues[problèmes connus] de v1.2.0.
