= Mettez à niveau de v1.5.0 ou v1.5.1 à v1.5.2
:revdate: 2025-11-11
:page-revdate: {revdate}

== informations générales

Un bouton *Mettre à niveau* apparaît sur l'écran *Tableau de bord* chaque fois qu'une nouvelle version {harvester-product-name} à laquelle vous pouvez mettre à niveau devient disponible. Pour plus d'informations, voir xref:./upgrades.adoc#_start_an_upgrade[Démarrer une mise à niveau].

Pour des informations sur la mise à niveau de {harvester-product-name} dans des environnements isolés physiquement, voir xref:./upgrades.adoc#_prepare_an_air_gapped_upgrade[Préparer une mise à niveau isolée physiquement].

=== Mettez à jour l'extension UI Harvester sur {rancher-product-name} v2.11.0

Vous devez utiliser **v1.5.2** de l'extension UI Harvester pour importer des clusters {harvester-product-name} v1.5.2 sur {rancher-short-name} v2.11.0.

. Sur l'interface {rancher-short-name} UI, allez à *local -> Applications -> Dépôts*.

. Localisez le dépôt nommé *harvester*, puis sélectionnez *⋮ -> Actualiser*.

. Allez à l'écran *Extensions*.

. Localisez l'extension nommée *Harvester*, puis cliquez sur *Mettre à jour*.

. Sélectionnez la version *1.5.2*, puis cliquez sur *Mettre à jour*.

. Laissez un peu de temps pour que l'extension soit mise à jour, puis actualisez l'écran.

== Problèmes connus

=== Les machines virtuelles qui utilisent des volumes RWX migrables redémarrent de manière inattendue

Les machines virtuelles qui utilisent des xref:integrations/rancher/csi-driver.adoc#_rwx_volumes_support[volumes RWX] migrables redémarrent de manière inattendue lorsque les pods du plugin CSI sont redémarrés. Ce problème affecte {harvester-product-name} v1.4.x, v1.5.0 et v1.5.1.

La solution de contournement consiste à désactiver le paramètre https://documentation.suse.com/cloudnative/storage/1.8/en/longhorn-system/settings.html#_automatically_delete_workload_pod_when_the_volume_is_detached_unexpectedly[Supprimer automatiquement le pod de charge de travail lorsque le volume est détaché de manière inattendue] sur l'interface {longhorn-product-name} avant de commencer la mise à niveau. Vous devez réactiver le paramètre une fois la mise à niveau terminée.

Le problème sera corrigé dans {longhorn-product-name} v1.8.3, v1.9.1 et les versions ultérieures. {harvester-product-name} v1.6.0 inclura {longhorn-product-name} v1.9.1. 

Problèmes connexes{nbsp}: https://github.com/harvester/harvester/issues/8534[#8534] et https://github.com/longhorn/longhorn/issues/11158[#11158]