= Mise à niveau de v1.7.x vers v1.7.y
:revdate: 2026-01-08
:page-revdate: {revdate}

== informations générales

Un bouton *Mise à niveau* apparaît sur l'écran *Tableau de bord* dès qu'une nouvelle version {harvester-product-name} vers laquelle vous pouvez mettre à niveau est disponible. Pour plus d'informations, consultez xref:upgrades/upgrades.adoc#_start_an_upgrade[Démarrer une mise à niveau].

Pour des informations sur la mise à niveau de {harvester-product-name} dans des environnements isolés physiquement, consultez xref:upgrades/upgrades.adoc#_prepare_an_air_gapped_upgrade[Préparer une mise à niveau isolée physiquement].

=== Mettez à jour l'extension UI Harvester sur {rancher-product-name} v2.13

Vous devez utiliser une version compatible (v1.7.x) de l'extension UI Harvester pour importer des clusters {harvester-product-name} v1.7.x sur {rancher-short-name} v2.13.

. Sur l'interface {rancher-short-name}, allez à *local -> appli -> Dépôts*.

. Localisez le dépôt nommé *harvester*, puis sélectionnez *⋮ -> Actualiser*.

. Allez à l'écran *Extensions*.

. Localisez l'extension nommée *Harvester*, puis cliquez sur *Mise à jour*.

. Sélectionnez une version compatible, puis cliquez sur *Mise à jour*.

. Laissez un certain temps pour que l'extension soit mise à jour, puis actualisez l'écran.

== Problèmes connus

=== La mise à niveau est bloquée dans l'état "Post-drainage"

Pendant le processus de drainage des nœuds, le déploiement `upgrade-repo` peut se bloquer lorsque son volume {longhorn-product-name} reste dans l'état "Attachement". Cela provoque un blocage du flux de mise à niveau dans la phase "Post-drainage", car les tâches post-drainage attendent que le déploiement `upgrade-repo` soit prêt avant de continuer.

La solution de contournement consiste à supprimer la réplique {longhorn-product-name} du volume `upgrade-repo` sur le nœud drainé. Cela permet au volume de s'attacher et au flux de mise à niveau de continuer. Notez que tout nœud étant drainé pendant la mise à niveau peut rencontrer ce problème, donc cette solution de contournement peut devoir être appliquée chaque fois qu'elle se produit.

Problèmes connexes{nbsp}: https://github.com/harvester/harvester/issues/9597[#9597] et https://github.com/longhorn/longhorn/issues/12226[#12226]