= ネットインストールISO
:revdate: 2025-05-09
:page-revdate: {revdate}

ネットインストールISOは、コアオペレーティングシステムコンポーネントのみを含む最小限のインストールイメージであり、インストーラーが起動してからディスクにオペレーティングシステムをインストールできるようにします。インストールが完了すると、オペレーティングシステムはインターネットから必要なすべてのコンテナイメージを取得します（主にDocker Hubから）。

次の状況でネットインストールISOを使用できます：

* サーバー上の仮想メディア実装に不具合があるか、動作が遅い。一部のユーザーは、ISOリダイレクションがシステムにすべてのイメージをプリロードするには遅すぎると報告しています。詳細については、 https://github.com/harvester/harvester/issues/2651[問題2651]を参照してください。
* すべての{harvester-product-name}イメージを含むプライベートレジストリがあり、containerdのイメージミラーを構成するために必要な知識と経験を持っています。

[CAUTION]
====
*常にフルISOを使用して{harvester-product-name}クラスターを起動する必要があります*（言い換えれば、`-net-install`サフィックスなしでISOを使用します）。フルISOには必要なすべてのイメージが含まれており、インストーラーはインストール中にそれらのイメージをプリロードします。ネットインストールISOを使用してクラスターを起動すると、 https://docs.docker.com/docker-hub/download-rate-limit/[Docker Hubのレート制限]に簡単に達することができます。
====

== 使用方法

GitHubの https://github.com/harvester/harvester/releases[リリース]ページからネットインストールISOをダウンロードし、ISOを起動して{harvester-product-name}をインストールします。ネットインストールISOファイル名には`net-install`のサフィックスがあります（例えば、 https://releases.rancher.com/harvester/v1.3.0/harvester-v1.3.0-amd64-net-install.iso).）

== PXEインストール

ネットインストールISOをPXEインストールソースとして使用することに決めた場合、カーネルを起動する際に次のパラメータを追加してください：

----
harvester.install.with_net_images=true
----

詳細については、xref:../../installation-setup/methods/pxe-boot-install.adoc[PXEブートインストール]を参照してください。
