= Fazer upgrade da v1.1.2/v1.1.3/v1.2.0 para v1.2.1
:revdate: 2025-05-09
:page-revdate: {revdate}

== Mudanças importantes nesta versão

O Harvester `v1.2.1` corrige problemas conhecidos durante o upgrade encontrados em `v1.2.0`; sugerimos fazer upgrade dos clusters `v1.1.2`, `v1.1.3` ou `v1.2.0` para `v1.2.1`. Os problemas conhecidos encontrados em `v1.2.0` são:

* xref:./v1-1-2-to-v1-2-0.adoc#_9_an_upgrade_is_stuck_in_the_post_draining_state[Um upgrade está preso no estado de pós-drenagem]
* xref:./v1-1-2-to-v1-2-0.adoc#_10_an_upgrade_is_stuck_in_the_upgrading_system_service_state_due_to_the_customer_provided_ssl_certificate_without_ip_san_error_in_fleet_agent[Um upgrade está preso no estado de atualização do Serviço do Sistema devido ao erro do certificado SSL fornecido pelo cliente, que não possui IP SAN, no Fleet agent]

Para clusters já atualizados para v1.2.0, consulte a https://github.com/harvester/harvester/releases/tag/v1.2.1[nota de lançamento] para novas mudanças.

== Informações gerais

[TIP]
====
Antes de iniciar um upgrade, você pode executar o script de pré-verificação para garantir que o cluster esteja em um estado estável. Para mais detalhes, visite este https://github.com/harvester/upgrade-helpers/tree/main/pre-check/v1.1.x[URL] para o script.
====

Assim que houver uma versão com possibilidade de fazer upgrade, a página do Painel do Harvester GUI mostrará um botão de fazer upgrade. Para mais detalhes, consulte xref:./upgrades.adoc#_start_an_upgrade[iniciar um upgrade].

Para o upgrade em ambiente air-gapped, consulte xref:./upgrades.adoc#_prepare_an_air_gapped_upgrade[preparar um upgrade em ambiente air-gapped].

== Problemas conhecidos

Por favor, verifique os xref:./v1-1-2-to-v1-2-0.adoc#_known_issues[problemas conhecidos] da v1.2.0.
