= Atualize da v1.5.0 ou da v1.5.1 para v1.5.2
:revdate: 2025-11-11
:page-revdate: {revdate}

== Informações gerais

Um *botão de Upgrade* aparece na tela *Dashboard* sempre que uma nova {harvester-product-name} versão para a qual você pode fazer upgrade se torna disponível. Para mais informações, veja xref:./upgrades.adoc#_start_an_upgrade[Iniciar um upgrade].

Para informações sobre como fazer upgrade do {harvester-product-name} em ambientes air-gapped, veja xref:./upgrades.adoc#_prepare_an_air_gapped_upgrade[Preparar um upgrade em ambientes air-gapped].

=== Atualize a extensão da UI do Harvester na {rancher-product-name} v2.11.0

Você deve usar a versão **v1.5.2** da extensão da UI do Harvester para importar clusters {harvester-product-name} v1.5.2 na v2.11.0.

. Na UI do {rancher-short-name}, vá para *local -> Apps -> Repositórios*.

. Localize o repositório chamado *harvester*, e então selecione *⋮ -> Atualizar*.

. Vá para a tela *Extensões*.

. Localize a extensão chamada *Harvester*, e então clique em *Atualizar*.

. Selecione a versão *1.5.2*, e então clique em *Atualizar*.

. Aguarde um tempo para que a extensão seja atualizada, e então atualize a tela.

== Problemas conhecidos

=== Máquinas virtuais que usam volumes RWX migráveis reiniciam inesperadamente

Máquinas virtuais que usam xref:integrations/rancher/csi-driver.adoc#_rwx_volumes_support[volumes RWX] migráveis reiniciam inesperadamente quando os pods do plugin CSI são reiniciados. Esse problema afeta {harvester-product-name} v1.4.x, v1.5.0 e v1.5.1.

A solução alternativa é desativar a configuração https://documentation.suse.com/cloudnative/storage/1.8/en/longhorn-system/settings.html#_automatically_delete_workload_pod_when_the_volume_is_detached_unexpectedly[Excluir automaticamente o pod de carga de trabalho quando o volume for desconectado inesperadamente] na UI do {longhorn-product-name} antes de iniciar o upgrade. Você deve habilitar a configuração novamente uma vez que o upgrade esteja concluído.

O problema será corrigido em {longhorn-product-name} v1.8.3, v1.9.1 e versões posteriores. {harvester-product-name} v1.6.0 incluirá {longhorn-product-name} v1.9.1. 

Problemas relacionados: https://github.com/harvester/harvester/issues/8534[#8534] e https://github.com/longhorn/longhorn/issues/11158[#11158]