= Faça o upgrade de v1.5.0 para v1.5.1
:revdate: 2025-07-07
:page-revdate: {revdate}

== Informações gerais

Um botão *Upgrade* aparece na tela *Dashboard* sempre que uma nova versão {harvester-product-name} para a qual você pode fazer upgrade se torna disponível. Para mais informações, veja xref:./upgrades.adoc#_start_an_upgrade[Iniciar um upgrade].

Para informações sobre como fazer upgrade do {harvester-product-name} em ambientes air-gapped, veja xref:./upgrades.adoc#_prepare_an_air_gapped_upgrade[Preparar um upgrade em ambientes air-gapped].

=== Atualize a Extensão da UI do Harvester no {rancher-product-name} v2.11.0

Você deve usar a versão **v1.5.1** da Extensão da UI do Harvester para importar clusters {harvester-product-name} v1.5.1 no {rancher-short-name} v2.11.0.

. Na UI do {rancher-short-name}, vá para *local -> Apps -> Repositórios*.

. Localize o repositório chamado *harvester*, e então selecione *⋮ -> Atualizar*.

. Vá para a tela de *Extensões*.

. Localize a extensão chamada *Harvester*, e então clique em *Atualizar*.

. Selecione a versão *1.5.1*, e então clique em *Atualizar*.

. Permita algum tempo para que a extensão seja atualizada, e então atualize a tela.

== Problemas conhecidos

=== 1. Máquinas virtuais que usam volumes RWX migráveis reiniciam inesperadamente

Máquinas virtuais que usam xref:integrations/rancher/csi-driver.adoc#_rwx_volumes_support[volumes RWX] migráveis reiniciam inesperadamente quando os pods do plugin CSI são reiniciados. Esse problema afeta {harvester-product-name} v1.4.x, v1.5.0 e v1.5.1.

A solução alternativa é desativar a configuração https://documentation.suse.com/cloudnative/storage/1.8/en/longhorn-system/settings.html#_automatically_delete_workload_pod_when_the_volume_is_detached_unexpectedly[Excluir automaticamente o pod de carga de trabalho quando o volume for desconectado inesperadamente] na UI do {longhorn-product-name} antes de iniciar o upgrade. Você deve habilitar a configuração novamente assim que o upgrade for concluído.

O problema será corrigido na versão {longhorn-product-name} v1.8.3, v1.9.1 e versões posteriores. A versão {harvester-product-name} v1.6.0 incluirá {longhorn-product-name} v1.9.1. 

Problemas relacionados: https://github.com/harvester/harvester/issues/8534[#8534] e https://github.com/longhorn/longhorn/issues/11158[#11158]