= Faça upgrade da versão v1.6.x para v1.7.x
:revdate: 2026-02-02
:page-revdate: {revdate}

== Informações gerais

Um *botão de fazer upgrade* aparece na tela *Dashboard* sempre que uma nova {harvester-product-name} versão para a qual você pode fazer upgrade se torna disponível. Para mais informações, veja xref:upgrades/upgrades.adoc#_start_an_upgrade[Iniciar um upgrade].

Clusters executando v1.6.x podem fazer upgrade diretamente para v1.7.x porque {harvester-product-name} permite um máximo de um upgrade de versão menor para componentes subjacentes. v1.6.0 e v1.6.1 usam a mesma versão menor do RKE2 (v1.33), enquanto {harvester-product-name} v1.7.0 e v1.7.1 usam a próxima versão menor (v1.34). Para mais informações, veja xref:upgrades/upgrades.adoc#_upgrade_paths[Caminhos de upgrade].

Para informações sobre como fazer upgrade {harvester-product-name} em ambientes air-gapped, veja xref:upgrades/upgrades.adoc#_prepare_an_air_gapped_upgrade[Preparar um upgrade em ambiente air-gapped].

[CAUTION]
====
v1.7.x usa o NetworkManager em vez do wicked, que era usado em versões anteriores de {harvester-product-name}. Se você modificou a configuração da interface de gerenciamento após a instalação inicial, deve realizar etapas manuais adicionais para evitar problemas durante o upgrade. Para obter mais informações, consulte <<Migration from wicked to NetworkManager>>.

Além disso, <<Persistent names of certain network interfaces may change during upgrade,nomes persistentes de certas interfaces de rede Intel podem mudar>> durante os upgrades. Isso quebra a conectividade no host e requer etapas manuais de remediação.
====

[IMPORTANT]
====
Endereços IP do host configurados via DHCP podem mudar durante os upgrades. Isso impede que o cluster inicie corretamente e requer etapas manuais de recuperação. Para obter mais informações, consulte <<Host IP address may change during upgrade when using DHCP>>. 
====

=== Atualize a Extensão da UI do Harvester na {rancher-product-name} v2.13

Você deve usar uma versão compatível (v1.7.x) da Extensão da UI do Harvester para importar clusters {harvester-product-name} v1.7.x na {rancher-short-name} v2.13.

. Na UI do {rancher-short-name}, vá para *local -> Apps -> Repositórios*.

. Localize o repositório chamado *harvester*, e então selecione *⋮ -> Atualizar*.

. Vá para a tela *Extensões*.

. Localize a extensão chamada *Harvester*, e então clique em *Atualizar*.

. Selecione uma versão compatível, e então clique em *Atualizar*.

. Aguarde um tempo para que a extensão seja atualizada, e então atualize a tela.

=== Migração do wicked para o NetworkManager

{harvester-product-name} v1.7.x faz a transição do wicked para o NetworkManager para gerenciamento de rede. Como não há um mapeamento direto 1:1 entre os arquivos legados `ifcfg` e os perfis de conexão do NetworkManager, uma migração in-loco da configuração de rede existente não é possível.

Durante os upgrades, {harvester-product-name} gera novos perfis de conexão do NetworkManager usando as configurações de instalação originais armazenadas em `/oem/harvester.config`. Os arquivos legados `ifcfg` em `/oem/90_custom.yaml` permanecem no sistema, mas o NetworkManager ignora esses arquivos e, em vez disso, armazena sua configuração em `/etc/NetworkManager`.

|===
| Cenário | Ação Necessária

| Você instalou a versão v1.1 ou posterior e nunca modificou manualmente a interface de gerenciamento ou a configuração de DNS.
| Nenhuma

| Você modificou manualmente a configuração da interface de gerenciamento editando o arquivo `/oem/90_custom.yaml` ou adicionando recursos do CloudInit aos arquivos `ifcfg`.
| **Necessário** (A configuração personalizada será ignorada após o upgrade para v1.7.0.)
|===

Se a ação for necessária, escolha um dos seguintes métodos:

* Pré-atualização (Recomendado): Edite o arquivo `/oem/harvester.config` em cada nó. Configure as configurações de rede relevantes, particularmente `os.dns_nameservers` e `install.management_interface`. Para mais informações, consulte xref:installation-setup/config/configuration-file.adoc[Arquivo de Configuração].
+
[NOTE]
====
Se você instalou inicialmente a v1.0, certifique-se de que `install.management_interface` siga o esquema atualizado exigido pelas versões posteriores de {harvester-product-name}.
====

* Pós-atualização: Use a ferramenta `nmcli` para reaplicar manualmente sua configuração personalizada aos novos perfis de conexão do NetworkManager.

Se você encontrar algum problema durante o upgrade, pode realizar as seguintes soluções alternativas:

|===
| Cenário | Solução | Resultado

| Um nó fica preso no estado "Aguardando Reinicialização".
| Faça login via console e verifique a configuração de rede usando a ferramenta `nmcli`. Se necessário, corrija manualmente a configuração e reinicie o nó.
| O upgrade retoma automaticamente.

| Erros ocorrem quando você altera manualmente a configuração.
| Se você quiser reverter para os perfis de conexão do NetworkManager gerados automaticamente, execute o comando `harvester-installer generate-network-config`.
| Os perfis de conexão do NetworkManager em `/etc/NetworkManager/system-connections/` são recriados com base na configuração especificada em `/oem/harvester.config`.
|===

== Problemas conhecidos

=== O endereço IP do host pode mudar durante o upgrade ao usar DHCP.

v1.7.x usa o NetworkManager em vez do wicked, que era usado em versões anteriores de {harvester-product-name}. Essas duas pilhas de rede têm padrões diferentes para gerar IDs de cliente DHCP. 

Se os endereços IP dos hosts estiverem configurados usando DHCP, um upgrade {harvester-product-name} e o reinício subsequente podem fazer com que o servidor DHCP atribua endereços IP diferentes dos que os hosts usaram anteriormente. Consequentemente, os hosts afetados não conseguem ingressar no cluster na inicialização devido à mudança de endereço IP.

Esse problema geralmente ocorre quando o servidor DHCP aloca endereços IP com base apenas no ID do cliente DHCP. É improvável que você encontre esse problema quando o servidor DHCP estiver configurado para alocar endereços IP fixos com base no endereço MAC (como demonstrado nos https://github.com/harvester/ipxe-examples[Exemplos de iPXE]).

O impacto desse problema varia de acordo com o tamanho do cluster:

* Clusters de nó único: {harvester-product-name} falha ao iniciar após reiniciar porque o endereço IP mudou.
* Clusters de múltiplos nós: Os nós de gerenciamento ficam presos no estado "Aguardando Reinício".

Para resolver o problema, execute os seguintes passos:

[IMPORTANT]
====
Você deve realizar os passos para cada nó afetado _após_ a conclusão do upgrade e a mudança do endereço IP.
====

. Faça login no nó afetado. Você pode acessar o nó via SSH em seu novo endereço IP ou usar o console.

. No diretório `/var/lib/wicked`, verifique o arquivo XML de locação (nome semelhante a `/var/lib/wicked/lease-mgmt-br-dhcp-ipv4.xml`).
+
Se você estiver usando uma VLAN, o nome de arquivo inclui o ID da VLAN (por exemplo, `/var/lib/wicked/lease-mgmt-br.2017-dhcp-ipv4.xml`).

. Visualize o arquivo e identifique o ID do cliente DHCP.
+
[,shell]
----
$ cat /var/lib/wicked/lease-mgmt-br-dhcp-ipv4.xml
<lease>
  ...
  <ipv4:dhcp>
    <client-id>ff:00:dd:c7:05:00:01:00:01:30:ae:a0:d3:52:54:00:dd:c7:05</client-id>
    ...
  </ipv4:dhcp>
</lease>
----

. Use o comando `nmcli` para definir o ID do cliente DHCP para o perfil de conexão do NetworkManager apropriado.
+
O perfil de conexão que você precisa modificar depende se seu nó usa uma VLAN.
+
* VLAN utilizada: Adicione o ID do cliente DHCP ao perfil de conexão `vlan-mgmt`.
* Sem VLAN: Adicione o ID do cliente DHCP ao perfil de conexão `bridge-mgmt`.
+
Exemplo (sem VLAN):
+
[,shell]
----
$ nmcli con modify bridge-mgmt \
    ipv4.dhcp-client-id \
    ff:00:dd:c7:05:00:01:00:01:30:ae:a0:d3:52:54:00:dd:c7:05
----
+
Você deve substituir o ID do cliente no exemplo pelo ID do cliente real do seu arquivo de lease do wicked.

. Reinicie o nó.

O servidor DHCP deve retornar o endereço IP original e o nó afetado deve ser capaz de ingressar no cluster.

[NOTE]
====
A propagação do ID do cliente DHCP do wicked para o NetworkManager ocorre automaticamente durante o upgrade de v1.6.x para v1.7.1. Esta solução alternativa é necessária apenas ao upgrade para v1.7.0.
====

Problemas relacionados: https://github.com/harvester/harvester/issues/9260[#9260] e https://github.com/harvester/harvester/issues/3418[#3418]

=== O upgrade está preso em "Atualizando Serviço do Sistema".

O processo de upgrade pode ficar preso na fase "Atualizando Serviço do Sistema". Este problema está provavelmente relacionado ao trabalho `apply-manifest` e a dois problemas conhecidos relacionados ao upgrade {fleet-product-name}.

Você pode encontrar mensagens de log semelhantes às seguintes:

[,console]
----
...
Happy Containering!
Wait for Rancher dependencies helm releases...
wait helm release cattle-fleet-system fleet fleet-108.0.0+up0.14.0 0.14.0 deployed
wait helm release cattle-fleet-system fleet-crd fleet-crd-108.0.0+up0.14.0 0.14.0 deployed
----

Verifique o histórico do Helm para determinar a causa e a solução alternativa relacionada.

* Cenário 1: O status do upgrade {fleet-product-name} é `pending-upgrade` mesmo após o upgrade ter sido concluído.
+
[,console]
----
$ helm history fleet -n cattle-fleet-system
REVISION        UPDATED                         STATUS          CHART                   APP VERSION     DESCRIPTION
6               Tue Nov  4 06:22:34 2025        superseded      fleet-105.0.2+up0.11.2  0.11.2          Upgrade complete
7               Tue Nov  4 06:22:49 2025        superseded      fleet-105.0.2+up0.11.2  0.11.2          Upgrade complete
8               Mon Dec  8 07:10:43 2025        superseded      fleet-106.1.1+up0.12.3  0.12.3          Upgrade complete
9               Mon Dec  8 07:26:49 2025        deployed        fleet-106.1.1+up0.12.3  0.12.3          Upgrade complete
10              Mon Dec  8 07:27:10 2025        pending-upgrade fleet-106.1.1+up0.12.3  0.12.3          Preparing upgrade
----
+
Para resolver o problema, execute a seguinte solução alternativa:
+
.. Execute o comando `$ helm rollback fleet -n cattle-fleet-system`.
+
.. Aguarde o Rancher embutido reconciliar o CRD `ClusterRepo` e acionar o upgrade do gráfico Helm. Para acelerar o processo, você pode reiniciar os pods do Rancher embutido.

* Cenário 2: O upgrade está preso em uma versão candidata de lançamento (RC). 
+
Isso não deve ocorrer, a menos que você esteja fazendo upgrade de uma versão RC para uma versão estável, o que não é suportado. Para assistência, crie um [problema no GitHub](https://github.com/harvester/harvester/issues).
+
[,console]
----
# helm history fleet -n cattle-fleet-system
REVISION        UPDATED                         STATUS          CHART                           APP VERSION     DESCRIPTION
2               Mon Dec  8 10:43:42 2025        superseded      fleet-108.0.0+up0.14.0-rc.1     0.14.0-rc.1     Upgrade complete
3               Mon Dec  8 10:49:51 2025        superseded      fleet-108.0.0+up0.14.0-rc.1     0.14.0-rc.1     Upgrade complete
4               Mon Dec  8 10:50:04 2025        superseded      fleet-108.0.0+up0.14.0-rc.1     0.14.0-rc.1     Upgrade complete
5               Mon Dec  8 10:56:30 2025        superseded      fleet-108.0.0+up0.14.0-rc.1     0.14.0-rc.1     Upgrade complete
6               Mon Dec  8 10:56:42 2025        deployed        fleet-108.0.0+up0.14.0-rc.1     0.14.0-rc.1     Upgrade complete
----

Problemas relacionados: https://github.com/harvester/harvester/issues/9738[#9738] e https://github.com/harvester/harvester/issues/9680[#9680]

=== Nomes persistentes de certas interfaces de rede podem mudar durante o upgrade.

{harvester-product-name} v1.7.x usa versões mais recentes dos drivers de rede `i40e` e `ice` do kernel Linux, fazendo com que um número de porta seja adicionado ao nome de certas interfaces de rede Intel, como a X710. Por exemplo, uma interface chamada `enp6s0f0` na {harvester-product-name} v1.6.x é renomeada para `enp6s0f0np0` durante o upgrade para v1.7.0. Isso quebra a conectividade no host porque as configurações de rede existentes ainda fazem referência ao nome original.

Para resolver esse problema, aplique argumentos do kernel que restauram os nomes originais das interfaces afetadas.

. Recupere a lista de argumentos do kernel não padrão (`third_party_kernel_args`) no nó.
+
[,console]
----
$ grub2-editenv /oem/grubenv list
third_party_kernel_args=multipath=off
----

. Adicione `ifname=nicName:macAddress` para cada interface de rede no nó para restaurar os nomes originais.
+
Certifique-se de que `third_party_kernel_args` esteja incluído ao adicionar os argumentos `ifname=`.
+
Exemplo:
+
[,console]
----
$ grub2-editenv /oem/grubenv set \
    third_party_kernel_args="multipath=off ifname=enp6s0f0:d4:c9:ef:ce:30:68 ifname=enp6s0f1:d4:c9:ef:ce:30:69"
----

. Reinicie o nó.

[NOTE]
====
Essa solução alternativa é necessária apenas ao atualizar para v1.7.0. Nas versões v1.7.1 e posteriores, esses argumentos `ifname=` são adicionados automaticamente para evitar interrupções na rede durante as atualizações do driver.
====

Problemas relacionados: https://github.com/harvester/harvester/issues/9815[#9815] e https://github.com/harvester/harvester/issues/9802[#9802]