= Faça upgrade da versão v1.7.x para v1.7.y
:revdate: 2026-01-08
:page-revdate: {revdate}

== Informações gerais

Um botão *Fazer upgrade* aparece na tela *Dashboard* sempre que uma nova versão {harvester-product-name} para a qual você pode fazer upgrade estiver disponível. Para mais informações, veja xref:upgrades/upgrades.adoc#_start_an_upgrade[Iniciar um upgrade].

Para informações sobre como fazer upgrade {harvester-product-name} em ambientes air-gapped, veja xref:upgrades/upgrades.adoc#_prepare_an_air_gapped_upgrade[Preparar um upgrade em ambiente air-gapped].

=== Atualize a extensão da UI do Harvester na versão {rancher-product-name} v2.13

Você deve usar uma versão compatível (v1.7.x) da extensão da UI do Harvester para importar clusters {harvester-product-name} v1.7.x na versão {rancher-short-name} v2.13.

. Na UI do {rancher-short-name}, vá para *local -> Apps -> Repositórios*.

. Localize o repositório chamado *harvester*, e então selecione *⋮ -> Atualizar*.

. Vá para a tela *Extensões*.

. Localize a extensão chamada *Harvester*, e então clique em *Atualizar*.

. Selecione uma versão compatível e, em seguida, clique em *Atualizar*.

. Permita algum tempo para que a extensão seja atualizada e, em seguida, atualize a tela.

== Problemas conhecidos

=== O upgrade está preso no estado "Pós-drenagem"

Durante o processo de drenagem do nó, a implantação `upgrade-repo` pode ficar presa quando seu volume {longhorn-product-name} permanece no estado "Anexando". Isso faz com que o fluxo de upgrade pare na fase "Pós-drenagem", uma vez que os trabalhos pós-drenagem aguardam a implantação `upgrade-repo` ficar pronta antes de prosseguir.

A solução alternativa é excluir a réplica {longhorn-product-name} do volume `upgrade-repo` no nó drenado. Isso permite que o volume se anexe e o fluxo de upgrade continue. Observe que qualquer nó sendo drenado durante o upgrade pode encontrar esse problema, portanto, essa solução alternativa pode precisar ser aplicada sempre que ocorrer.

Problemas relacionados: https://github.com/harvester/harvester/issues/9597[#9597] e https://github.com/longhorn/longhorn/issues/12226[#12226]