= Ajout à chaud de NIC
:revdate: 2026-01-02
:page-revdate: {revdate}

{harvester-product-name} prend en charge la connexion à chaud et la déconnexion à chaud des contrôleurs d'interface réseau (NIC) pour des machines virtuelles xref:virtual-machines/live-migration.adoc#_live_migratable_virtual_machines[migrables en direct]. Cette fonctionnalité vous permet d'ajouter et de supprimer des interfaces réseau d'une machine virtuelle en cours d'exécution sans nécessiter un redémarrage.

[NOTE]
====
Vous ne pouvez pas effectuer la connexion à chaud de NIC sur des machines virtuelles créées dans des clusters exécutant des versions {harvester-product-name} antérieures à v1.7.0 _si l'adresse MAC de l'interface réseau n'a pas été explicitement configurée_. Pour activer cette fonctionnalité, vous devez redémarrer ces machines virtuelles. Le redémarrage permet au système de sauvegarder automatiquement les adresses MAC observées dans la configuration de la machine virtuelle.

De plus, les machines virtuelles créées en utilisant le xref:integrations/rancher/node-driver/node-driver.adoc[Harvester Node Driver] et le xref:integrations/terraform/terraform-provider.adoc[Harvester Terraform Provider] _ne prennent pas en charge_ la connexion à chaud et la déconnexion à chaud des NIC.
====

== Ajoutez à chaud des NIC à une machine virtuelle en cours d'exécution.

. Dans l'interface {harvester-product-name}, allez à l'écran *Machines Virtuelles*.

. Localisez la machine virtuelle cible, puis sélectionnez *⋮ -> Ajouter à chaud une interface réseau*.

. Spécifiez un nom pour l'interface réseau et sélectionnez un réseau de machine virtuelle.
+
Vous pouvez sélectionner un xref:networking/vm-network.adoc#_vlan_network[réseau VLAN], un xref:networking/vm-network.adoc#_untagged_network[réseau non étiqueté], ou un xref:networking/vm-network.adoc#_vlan_trunk_network[réseau de tronc VLAN].

. Cliquez sur *Appliquer*.

{harvester-product-name} xref:virtual-machines/live-migration.adoc#_prerequisites[migre la machine virtuelle] et l'interface spécifiée est connectée par liaison de pont.

Pour des informations sur les limitations concernant le nombre d'interfaces ajoutées à chaud, voir https://kubevirt.io/user-guide/network/hotplug_interfaces/#virtio-limitations[Limitations Virtio] dans la documentation KubeVirt.

== Déconnectez à chaud des NIC d'une machine virtuelle en cours d'exécution.

[IMPORTANT]
====
Vous ne pouvez effectuer cette action que lorsque les conditions suivantes sont remplies{nbsp}:

* La machine virtuelle a au moins deux interfaces réseau. Vous ne pouvez pas déconnecter à chaud la seule interface restante.
* L'interface cible est connectée par liaison de pont.
====

. Dans l'interface {harvester-product-name}, allez à l'écran *Machines Virtuelles*.

. Cliquez sur le nom de la machine virtuelle cible, puis allez à l'onglet *Réseaux*.

. Localisez l'interface cible, puis cliquez sur *Détacher l'interface réseau*.

{harvester-product-name} xref:virtual-machines/live-migration.adoc#_prerequisites[migre la machine virtuelle] et détache l'interface.