= Machines virtuelles
:revdate: 2026-01-08
:page-revdate: {revdate}

Vous pouvez créer des xref:../virtual-machines/create-vm.adoc[machines virtuelles Linux] en utilisant l'une des méthodes suivantes : 

* {harvester-product-name} Interface utilisateur : Sur l'écran *machines virtuelles*, cliquez sur *Créer* et configurez les paramètres sur chaque onglet. 
* API Kubernetes : Créez un objet `VirtualMachine`. 
* xref:../integrations/terraform/terraform-provider.adoc[Fournisseur Terraform Harvester] : Définissez un bloc de ressources `harvester_virtualmachine`. 

Créer des xref:../virtual-machines/create-windows-vm.adoc[machines virtuelles Windows] dans l'interface utilisateur implique des étapes légèrement différentes. {harvester-product-name} fournit un modèle de machine virtuelle nommé `windows-iso-image-base-template` qui ajoute un volume avec les pilotes Virtio pour Windows, ce qui simplifie le processus de configuration. Si vous avez besoin de périphériques Virtio mais choisissez de ne pas utiliser le modèle, vous devez ajouter vos propres pilotes Virtio pour Windows afin d'activer la détection correcte du matériel. 

== Systèmes d'exploitation invités validés

Les systèmes d'exploitation suivants ont été validés pour fonctionner dans des {harvester-product-name} machines virtuelles:

* SUSE Linux Enterprise Micro 6.0 et 6.1
* SUSE Linux Enterprise Server 15 SP6 et 15 SP7
* Red Hat Enterprise Linux 9 et 10
* Ubuntu 22.04 et 24.04
* Windows 11
* Windows Server 2025

[NOTE]
====
La liste comprend uniquement des systèmes d'exploitation testés et n'est pas destinée à être exhaustive. D'autres systèmes d'exploitation peuvent également fonctionner dans des {harvester-product-name} machines virtuelles. Cependant, les systèmes d'exploitation invités doivent correspondre à l'architecture des {harvester-product-name} hôtes du cluster. Les machines virtuelles AMD ne peuvent fonctionner que sur des clusters AMD, et les machines virtuelles ARM ne peuvent fonctionner que sur des clusters ARM.

Vous êtes responsable de l'obtention, de l'activation et de la gestion des licences pour tout logiciel commercial que vous décidez d'utiliser. {harvester-product-name} ne peut être tenu responsable des dommages ou de la perte de données pouvant survenir en raison de l'utilisation de systèmes d'exploitation non testés, non corrigés et obsolètes.

Le contenu de ce document peut ne pas refléter la situation la plus actuelle et peut changer à tout moment sans préavis.
====