= Entwicklungsleitfaden für Add-ons
:revdate: 2025-06-17
:page-revdate: {revdate}

{harvester-product-name} Add-ons ermöglichen es Ihnen, spezifische Produkt- und Drittanbieterkomponenten basierend auf Ihren Anforderungen zu aktivieren und zu deaktivieren. Add-ons fungieren als Wrapper für die https://documentation.suse.com/cloudnative/rke2/latest/en/helm.html#_using_the_helm_crd[{rke2-product-name} HelmChart-Ressourcendefinition (CRD)].

== Voraussetzungen

* Ein bestehender {harvester-product-name} Cluster

== Spezifikationen für Add-ons

Die `Addon` CRD unterstützt die folgenden Felder:

[,yaml]
----
apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  name: example-add-on           # Name of add-on
  namespace: example-namespace  # Namespace where the add-on CRD is deployed and where the associated Kubernetes components will be deployed
  labels:                       # Optional add-on labels
    Add-on.harvesterhci.io/experimental: "true" # Predefined label used on the UI to identify add-ons with the "experimental" maturity level
spec:
  enabled: false                # Boolean indicating if an add-on should be enabled or disabled on definition
  repo: https://chartsrepo.com  # Helm chart repository containing the Helm chart managed by the add-on
  version: "v0.19.0"            # Version of the Helm chart to be installed
  chart: mychart                # Name of the Helm chart in the Helm chart repository
  valuesContent: |-             # File (values.yaml) that must be passed to the Helm chart
    contents of values.yaml
    that need to be passed
    to the chart
----

[NOTE]
====
Experimentelle Add-ons sind nicht direkt in {harvester-product-name} verpackt. Ein Beispiel ist das https://github.com/harvester/experimental-addons/blob/main/rancher-vcluster/rancher-vcluster.yaml[`rancher-vcluster`] Add-on.
====

== Installation

[,bash]
----
kubectl apply -f /path/to/add-on.yaml
----

== Verwendung

Nach der Erstellung einer `Addon` CRD können Sie das `enabled` Feld umschalten, um das zugehörige Helm-Chart zu aktivieren und zu deaktivieren.

== Aufrüsten

Änderungen an den Feldern `repo`, `version`, `chart` oder `valueContent` lösen ein `helm upgrade` aus, das ein Upgrade des bestehenden Helm-Charts erzwingt.

== Deinstallation

[,bash]
----
kubectl delete -f /path/to/Add-on.yaml
----
