= Modules complémentaires
:revdate: 2025-12-30
:page-revdate: {revdate}

{harvester-product-name} fournit des fonctionnalités optionnelles en tant que produits complémentaires pour maintenir une empreinte d'installation minimale. Ce design vous permet d'activer ou de désactiver des fonctionnalités en fonction de votre cas d'utilisation et de vos exigences. Vous pouvez personnaliser les paramètres de chaque produit complémentaire, bien que le niveau de personnalisation dépende du logiciel sous-jacent.

Les produits complémentaires suivants sont disponibles dans cette version{nbsp}:

* xref:add-ons/lvm-local-storage.adoc[csi-driver-lvm] (Expérimental)
* xref:add-ons/kubeovn-operator.adoc[kubeovn-operator] (Expérimental)
* xref:add-ons/nvidia-driver-toolkit.adoc[nvidia-driver-toolkit]
* xref:add-ons/pcidevices-controller.adoc[pcidevices-controller]
* xref:observability/logging.adoc[rancher-logging]
* xref:observability/monitoring.adoc[rancher-monitoring]
* xref:add-ons/rancher-vcluster.adoc[rancher-vcluster] (Expérimental)
* xref:add-ons/harvester-seeder.adoc[seeder] (Expérimental)
* xref:add-ons/vm-dhcp-controller.adoc[vm-dhcp-controller] (Expérimental)
* xref:add-ons/vm-import-controller.adoc[vm-import-controller]

Vous pouvez activer et désactiver les produits complémentaires sur l'écran *Add-ons* de l'interface {harvester-product-name}.

|===
| Opération | Opération | Nouvel État

| Activation d'un produit complémentaire
| Sélectionnez le produit complémentaire, puis sélectionnez *⋮ -> Activer*.
| **DeploySuccessful**

| Désactivation d'un produit complémentaire
| Sélectionnez le produit complémentaire, puis sélectionnez *⋮ -> Désactiver*.
| *Désactivé*
|===

[NOTE]
====
{harvester-product-name} stocke les données de configuration des produits complémentaires désactivés, permettant une réutilisation immédiate lors de la réactivation.
====