= Actualiza de v1.1.2/v1.1.3/v1.2.0 a v1.2.1
:revdate: 2025-05-09
:page-revdate: {revdate}

== Cambios importantes en esta versión

El Harvester `v1.2.1` corrige problemas conocidos de la actualización encontrados en `v1.2.0`, sugerimos actualizar los clústeres `v1.1.2`, `v1.1.3` o `v1.2.0` a `v1.2.1`. Los problemas conocidos encontrados en `v1.2.0` son:

* xref:./v1-1-2-to-v1-2-0.adoc#_9_an_upgrade_is_stuck_in_the_post_draining_state[Una actualización está atascada en el estado de Post-draining]
* xref:./v1-1-2-to-v1-2-0.adoc#_10_an_upgrade_is_stuck_in_the_upgrading_system_service_state_due_to_the_customer_provided_ssl_certificate_without_ip_san_error_in_fleet_agent[Una actualización está atascada en el estado Upgrading System Service debido al certificado SSL proporcionado por el cliente sin error de IP SAN en el Fleet agent]

Para clústeres que ya se han actualizado a v1.2.0, por favor consulta la https://github.com/harvester/harvester/releases/tag/v1.2.1[nota de lanzamiento] para los nuevos cambios.

== Información general

[TIP]
====
Antes de comenzar a actualizar versión, puedes ejecutar el script de pre-verificación para asegurarte de que el clúster esté en un estado estable. Para más detalles, por favor visita este https://github.com/harvester/upgrade-helpers/tree/main/pre-check/v1.1.x[URL] para el script.
====

Una vez que haya una versión actualizable, la página del panel de control de Harvester GUI mostrará un botón de actualización. Para más detalles, por favor consulta xref:./upgrades.adoc#_start_an_upgrade[iniciar una actualización].

Para la actualización de versión en un entorno aislado, por favor consulta xref:./upgrades.adoc#_prepare_an_air_gapped_upgrade[preparar una actualización de versión en un entorno aislado].

== Problemas conocidos

Por favor, revisa los xref:./v1-1-2-to-v1-2-0.adoc#_known_issues[problemas conocidos] de v1.2.0.
