= Actualiza versión de v1.5.0 o v1.5.1 a v1.5.2
:revdate: 2025-11-11
:page-revdate: {revdate}

== Información general

Un botón de *Actualizar versión* aparece en la pantalla del *Tablero* siempre que una nueva versión {harvester-product-name} a la que puedes actualizar esté disponible. Para más información, consulta xref:./upgrades.adoc#_start_an_upgrade[Iniciar la actualización].

Para obtener información sobre cómo actualizar la versión {harvester-product-name} en entornos aislados, consulta xref:./upgrades.adoc#_prepare_an_air_gapped_upgrade[Preparar una actualización en entorno aislado].

=== Actualiza la Extensión de UI de Harvester en {rancher-product-name} v2.11.0

Debes usar **v1.5.2** de la Extensión de UI de Harvester para importar clústeres {harvester-product-name} v1.5.2 en {rancher-short-name} v2.11.0.

. En la UI de {rancher-short-name}, ve a *local -> Apps -> Repositorios*.

. Localiza el repositorio llamado *harvester*, y luego selecciona *⋮ -> Refrescar*.

. Ve a la pantalla de *Extensiones*.

. Localiza la extensión llamada *Harvester*, y luego haz clic en *Actualizar*.

. Selecciona la versión *1.5.2*, y luego haz clic en *Actualizar*.

. Permite un tiempo para que la extensión se actualice, y luego refresca la pantalla.

== Problemas conocidos

=== Las máquinas virtuales que utilizan volúmenes RWX migrables se reinician inesperadamente

Las máquinas virtuales que utilizan xref:integrations/rancher/csi-driver.adoc#_rwx_volumes_support[volúmenes RWX] migrables se reinician inesperadamente cuando se reinician los pods del plugin CSI. Este problema afecta a {harvester-product-name} v1.4.x, v1.5.0 y v1.5.1.

La solución alternativa es desactivar la configuración https://documentation.suse.com/cloudnative/storage/1.8/en/longhorn-system/settings.html#_automatically_delete_workload_pod_when_the_volume_is_detached_unexpectedly[Eliminar automáticamente el pod de carga de trabajo cuando el volumen se desmonte inesperadamente] en la UI de {longhorn-product-name} antes de iniciar la actualización. Debes habilitar la configuración nuevamente una vez que la actualización se haya completado.

El problema se solucionará en {longhorn-product-name} v1.8.3, v1.9.1 y versiones posteriores. {harvester-product-name} v1.6.0 incluirá {longhorn-product-name} v1.9.1. 

Problemas relacionados: https://github.com/harvester/harvester/issues/8534[#8534] y https://github.com/longhorn/longhorn/issues/11158[#11158]