= Upgrade von v1.1.2/v1.1.3/v1.2.0 auf v1.2.1
:revdate: 2025-05-09
:page-revdate: {revdate}

== Wichtige Änderungen in dieser Version

Der Harvester `v1.2.1` behebt bekannte Upgrade-Probleme, die in `v1.2.0` gefunden wurden. Wir empfehlen, die Cluster `v1.1.2`, `v1.1.3` oder `v1.2.0` auf `v1.2.1` zu aktualisieren. Die bekannten Probleme, die in `v1.2.0` gefunden wurden, sind:

* xref:./v1-1-2-to-v1-2-0.adoc#_9_an_upgrade_is_stuck_in_the_post_draining_state[Ein Upgrade steckt im Post-Drain-Zustand fest]
* xref:./v1-1-2-to-v1-2-0.adoc#_10_an_upgrade_is_stuck_in_the_upgrading_system_service_state_due_to_the_customer_provided_ssl_certificate_without_ip_san_error_in_fleet_agent[Ein Upgrade steckt im Zustand "Systemdienst wird aktualisiert" fest, aufgrund des vom Kunden bereitgestellten SSL-Zertifikats ohne IP SAN-Fehler im Fleet agent]

Für Cluster, die bereits auf v1.2.0 aktualisiert wurden, beachten Sie bitte die https://github.com/harvester/harvester/releases/tag/v1.2.1[Versionshinweise] für neue Änderungen.

== Allgemeine Informationen

[TIP]
====
Bevor Sie ein Upgrade starten, können Sie das Pre-Check-Skript ausführen, um sicherzustellen, dass der Cluster in einem stabilen Zustand ist. Für weitere Details besuchen Sie bitte diese https://github.com/harvester/upgrade-helpers/tree/main/pre-check/v1.1.x[URL] für das Skript.
====

Sobald eine aktualisierbare Version verfügbar ist, wird auf der Harvester GUI-Dashboard-Seite eine Upgrade-Schaltfläche angezeigt. Für weitere Details beachten Sie bitte xref:./upgrades.adoc#_start_an_upgrade[Upgrade starten].

Für das Air Gap-Umgebungs-Upgrade beachten Sie bitte xref:./upgrades.adoc#_prepare_an_air_gapped_upgrade[ein Air-Gapped-Upgrade vorbereiten].

== Bekannte Probleme

Bitte überprüfen Sie die v1.2.0 xref:./v1-1-2-to-v1-2-0.adoc#_known_issues[bekannten Probleme].
