= Upgrade von v1.5.0 oder v1.5.1 auf v1.5.2
:revdate: 2025-11-11
:page-revdate: {revdate}

== Allgemeine Informationen

Ein *Upgrade*-Button erscheint auf dem *Dashboard*-Bildschirm, wann immer eine neue {harvester-product-name} Version verfügbar wird, auf die Sie upgraden können. Für weitere Informationen siehe xref:./upgrades.adoc#_start_an_upgrade[Starten Sie ein Upgrade].

Für Informationen zum Upgrade von {harvester-product-name} in Air-Gapped-Umgebungen siehe xref:./upgrades.adoc#_prepare_an_air_gapped_upgrade[Bereite ein Air-Gapped-Upgrade vor].

=== Aktualisieren Sie die Harvester UI-Erweiterung auf {rancher-product-name} v2.11.0

Sie müssen **v1.5.2** der Harvester UI-Erweiterung verwenden, um {harvester-product-name} v1.5.2 Cluster auf {rancher-short-name} v2.11.0 zu importieren.

. Gehen Sie auf der {rancher-short-name} UI zu *lokalen -> Apps -> Repositories*.

. Suchen Sie das Repository mit dem Namen *harvester* und wählen Sie dann *⋮ -> Aktualisieren*.

. Gehen Sie zum *Erweiterungen*-Bildschirm.

. Suchen Sie die Erweiterung mit dem Namen *Harvester* und klicken Sie dann auf *Aktualisieren*.

. Wählen Sie die Version *1.5.2* und klicken Sie dann auf *Aktualisieren*.

. Lassen Sie etwas Zeit, damit die Erweiterung aktualisiert wird, und aktualisieren Sie dann den Bildschirm.

== Bekannte Probleme

=== Virtuelle Maschinen, die migrierbare RWX-Volumes verwenden, starten unerwartet neu

Virtuelle Maschinen, die migrierbare xref:integrations/rancher/csi-driver.adoc#_rwx_volumes_support[RWX-Volumes] verwenden, starten unerwartet neu, wenn die CSI-Plugin-Pods neu gestartet werden. Dieses Problem betrifft {harvester-product-name} v1.4.x, v1.5.0 und v1.5.1.

Die Lösung besteht darin, die Einstellung https://documentation.suse.com/cloudnative/storage/1.8/en/longhorn-system/settings.html#_automatically_delete_workload_pod_when_the_volume_is_detached_unexpectedly[Arbeitslast-Pod automatisch löschen, wenn das Volume unerwartet getrennt wird] in der {longhorn-product-name} UI vor dem Start des Upgrades zu deaktivieren. Sie müssen die Einstellung erneut aktivieren, sobald das Upgrade abgeschlossen ist.

Das Problem wird in {longhorn-product-name} v1.8.3, v1.9.1 und späteren Versionen behoben. {harvester-product-name} v1.6.0 wird {longhorn-product-name} v1.9.1 enthalten. 

Verwandte Probleme: https://github.com/harvester/harvester/issues/8534[#8534] und https://github.com/longhorn/longhorn/issues/11158[#11158]