= Upgrade von v1.7.x auf v1.7.y
:revdate: 2026-01-08
:page-revdate: {revdate}

== Allgemeine Informationen

Ein *Upgrade*-Button erscheint auf dem *Dashboard*-Bildschirm, wann immer eine neue {harvester-product-name} Version verfügbar wird, auf die Sie upgraden können. Für weitere Informationen siehe xref:upgrades/upgrades.adoc#_start_an_upgrade[Starten eines Upgrades].

Für Informationen zum Upgrade von {harvester-product-name} in Air-Gapped-Umgebungen siehe xref:upgrades/upgrades.adoc#_prepare_an_air_gapped_upgrade[Vorbereiten eines Air-Gapped-Upgrades].

=== Aktualisieren Sie die Harvester UI-Erweiterung auf {rancher-product-name} v2.13

Sie müssen eine kompatible Version (v1.7.x) der Harvester UI-Erweiterung verwenden, um {harvester-product-name} v1.7.x Cluster auf {rancher-short-name} v2.13 zu importieren.

. Gehen Sie in der {rancher-short-name} UI zu *lokalen -> Apps -> Repositories*.

. Suchen Sie das Repository mit dem Namen *harvester* und wählen Sie dann *⋮ -> Aktualisieren* aus.

. Gehen Sie zum *Erweiterungen*-Bildschirm.

. Suchen Sie die Erweiterung mit dem Namen *Harvester* und klicken Sie dann auf *Aktualisieren*.

. Wählen Sie eine kompatible Version aus und klicken Sie dann auf *Aktualisieren*.

. Lassen Sie etwas Zeit, damit die Erweiterung aktualisiert wird, und aktualisieren Sie dann den Bildschirm.

== Bekannte Probleme

=== Upgrade steckt im "Post-Draining"-Zustand fest

Während des Entleerungsprozesses des Knotens kann die `upgrade-repo` Implementierung stecken bleiben, wenn ihr {longhorn-product-name} Volume im "Attaching"-Zustand bleibt. Dies führt dazu, dass der Upgrade-Prozess in der "Post-Draining"-Phase ins Stocken gerät, da die Post-Draining-Jobs darauf warten, dass die `upgrade-repo` Implementierung bereit wird, bevor sie fortfahren.

Die Umgehungslösung besteht darin, die {longhorn-product-name} Replica des `upgrade-repo` Volumes auf dem entleerten Knoten zu löschen. Dies ermöglicht es dem Volume, sich anzufügen und den Upgrade-Prozess fortzusetzen. Beachten Sie, dass jeder Knoten, der während des Upgrades entleert wird, auf dieses Problem stoßen kann, sodass diese Umgehungslösung angewendet werden muss, wann immer es auftritt.

Verwandte Probleme: https://github.com/harvester/harvester/issues/9597[#9597] und https://github.com/longhorn/longhorn/issues/12226[#12226]