= Cluster Pod Security Standards
:description: Apply Kubernetes Pod Security Standards cluster-wide to enforce policies that restrict workload execution and prevent privilege escalation
:revdate: 2026-10-01
:page-revdate: {revdate}

Starting with v1.8.0, {harvester-product-name} enables cluster administrators to apply https://kubernetes.io/docs/concepts/security/pod-security-standards/[Kubernetes Pod Security Standards (PSS)] using a global setting. PSS define policies that can be applied to clusters and namespaces to control and restrict how workloads are executed.

== Background

If you run bare-metal workloads in large multi-tenant environments, you must prevent privilege escalation. One way to do this is to manually apply PSS by following the steps in https://harvesterhci.io/kb/2025/05/08/using-pod-security-standard[this Knowledge Base article]. The new `cluster-pod-security-standard` setting simplifies this setup by allowing cluster-wide enforcement. This setting is disabled by default.

[,json]
----
{
  "enabled":false,
  "whitelistedNamespacesList":"", 
  "privilegedNamespacesList":"",
  "restrictedNamespacesList":""
}
----

The setting includes the following fields:

* `enabled`: When set to `true`, the https://kubernetes.io/docs/concepts/security/pod-security-standards/#baseline[Baseline] PSS profile is enforced on all non-{harvester-product-name} system namespaces. Core {harvester-product-name} features are fully validated to run at this _Baseline_ level. Once you enable this setting, you cannot modify namespace PSS configurations directly. You must make all changes through the {harvester-product-name} UI or API.

* `whitelistedNamespacesList`: Namespaces exempted from PSS enforcement.

* `privilegedNamespacesList`: Namespaces where the https://kubernetes.io/docs/concepts/security/pod-security-standards/#privileged[Privileged] PSS profile is enforced.

* `restrictedNamespacesList`: Namespaces where the https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted[Restricted] PSS profile is enforced.

== Configuring Pod Security Standards

You can apply cluster-wide PSS using the `cluster-pod-security-standard` setting.

[tabs]
======
UI::
+
--
=== Enabling the setting

. Go to *Advanced -> Settings -> `cluster-pod-security-standard`*.

. Select *Edit Setting > Enabled*.

. Use the *Whitelisted Namespaces*, *Privileged Namespaces*, and *Restricted Namespaces* settings to assign Pod Security Standards to specific namespaces. Separate multiple namespaces with a comma.

. Click *Save*.

=== Disabling the setting

. Go to *Advanced -> Settings -> cluster-pod-security-standard*.

. Select *Edit Setting > Disabled*.

. Click *Save*.
--

CLI::
+
--
. Check the current value of the setting.
+
[,shell]
----
kubectl get settings.harvesterhci.io cluster-pod-security-standard
NAME                            VALUE
cluster-pod-security-standard
----

. Update the setting as follows:
+
[,shell]
----
kubectl patch settings.harvesterhci.io cluster-pod-security-standard --type='json' -p='[{"op": "replace", "path": "/value", "value": "{\"enabled\":true,\"whitelistedNamespacesList\":\"default\",\"restrictedNamespacesList\":\"demo,restricted-ns\",\"privilegedNamespacesList\":\"demo2,privileged-ns\"}"}]'
----

. Verify that the setting was applied.
+
[,shell]
----
kubectl get settings.harvesterhci.io cluster-pod-security-standard
NAME                            VALUE
cluster-pod-security-standard   {"enabled":true,"whitelistedNamespacesList":"default","restrictedNamespacesList":"demo,restricted-ns","privilegedNamespacesList":"demo2,privileged-ns"}
----
--
======

== Whitelisted namespaces

The following system namespaces are permanently whitelisted to ensure that {harvester-product-name} functions correctly. Their PSS settings cannot be modified.

* `calico-apiserver`
* `calico-system`
* `cattle-alerting`
* `cattle-csp-adapter-system`
* `cattle-elemental-system`
* `cattle-epinio-system`
* `cattle-externalip-system`
* `cattle-fleet-local-system`
* `cattle-fleet-system`
* `cattle-gatekeeper-system`
* `cattle-global-data`
* `cattle-global-nt`
* `cattle-impersonation-system`
* `cattle-istio`
* `cattle-istio-system`
* `cattle-logging`
* `cattle-logging-system`
* `cattle-monitoring-system`
* `cattle-neuvector-system`
* `cattle-prometheus`
* `cattle-provisioning-capi-system`
* `cattle-resources-system`
* `cattle-sriov-system`
* `cattle-system`
* `cattle-ui-plugin-system`
* `cattle-windows-gmsa-system`
* `cert-manager`
* `cis-operator-system`
* `fleet-default`
* `ingress-nginx`
* `istio-system`
* `kube-node-lease`
* `kube-public`
* `kube-system`
* `longhorn-system`
* `rancher-alerting-drivers`
* `security-scan`
* `tigera-operator`
* `harvester-system`
* `rancher-vcluster`
* `cattle-dashboards`
* `fleet-local`
* `local`
* `forklift`