= Convenciones de documentos
:revdate: 16/07/2025
:page-revdate: {revdate}

== Tipos de lanzamiento

Los términos "Comunidad" y "Prime" se utilizan para diferenciar los lanzamientos destinados a usuarios de la comunidad y clientes de SUSE. "Prime" se refiere a https://www.suse.com/products/rancher[SUSE Rancher Prime], que es la plataforma de gestión de contenedores de SUSE.

|===
| Tipo de lanzamiento | Convención de versionado | Ejemplo | Ciclo de vida del soporte

| Comunidad
| x.y.z
| v1.5.0
| El soporte para cada lanzamiento comunitario finaliza cuando se lanza la versión x.(y+1).1.

| Prime
| x.y.[1-z]
| v1.5.1
| Los lanzamientos Prime reciben 6 meses de soporte activo. A continuación, se ofrece soporte de mantenimiento durante 12 meses, que cubre problemas críticos relacionados con la seguridad.
|===

== Etiquetas de Lanzamiento

La documentación de {harvester-product-name} utiliza las siguientes etiquetas para describir los lanzamientos del software.

* *Dev*: El software está en desarrollo activo y no ha sido probado exhaustivamente. No se admite la actualización desde lanzamientos anteriores o a lanzamientos posteriores. Los lanzamientos "Dev" suelen ocurrir al final de un sprint y pueden ocurrir cuando se cumplen otras definiciones de finalización.
* *Último*: El software ha pasado todas las etapas de verificación y prueba. Todos los problemas conocidos restantes se consideran aceptables.
* *FIN DE VIDA ÚTIL*: El software ha alcanzado el final de su vida útil y no se proporciona más mantenimiento a nivel de código. Puede continuar utilizando el software dentro de los términos del acuerdo de licencia.

== Etiquetas de características

Las características etiquetadas como *Experimental* y *Technical Preview* ofrecen un vistazo a las innovaciones futuras y brindan oportunidades para probar nuevas tecnologías en su entorno.

* *Experimental*: La característica está incompleta, pero su funcionalidad esencial está operativa. Las pruebas en un entorno controlado han demostrado que puede coexistir con características estables existentes. Debido a los componentes faltantes y/o la funcionalidad en evolución, no se recomienda el uso de la característica en entornos de producción.
* *Technical Preview*: La característica está casi completa y no se espera que su funcionalidad cambie significativamente. Las pruebas en un entorno controlado han demostrado que puede coexistir con características estables existentes. Explore la característica a fondo antes de usarla en entornos de producción.

Estas características tienen las siguientes limitaciones:

* Aún en desarrollo y pueden estar funcionalmente incompletas, inestables o de alguna otra manera inadecuadas para su uso en producción.
* No es compatible.
* Puede estar disponible solo para arquitecturas de hardware específicas. Los detalles y la funcionalidad están sujetos a cambios. Como resultado, actualizar a versiones posteriores puede ser imposible y puede requerir una instalación nueva.
* Puede ser eliminada del producto en cualquier momento. Esto puede ocurrir, por ejemplo, si descubrimos que la característica no satisface las necesidades del cliente o del mercado, o no cumple con los estándares empresariales.

[NOTE]
====
Las características *Experimental* y *Technical Preview* suelen estar desactivadas por defecto. La documentación proporciona información sobre cómo puede habilitar y configurar tales características.
====

== Advertencias

Las advertencias son bloques de texto que proporcionan información adicional o importante. Cada bloque de texto está marcado con una etiqueta y un icono especiales. La documentación de {harvester-product-name} utiliza las siguientes convenciones para ayudarle a interpretar la información.

* *Nota*: Información adicional que es útil pero no crítica.
* *Importante*: Información que requiere atención especial, como cambios en el comportamiento del producto.
* *Sugerencia*: Consejos y sugerencias útiles, como los métodos alternativos para completar una tarea.
* *Precaución*: Información que debe considerarse antes de proceder con acciones específicas, como errores que pueden ocurrir.
* *Advertencia*: Información crítica sobre consecuencias perjudiciales, como daños irreversibles y pérdida de datos.