= Glosario
:revdate: 2026-01-27
:page-revdate: {revdate}

== *red de clúster*

Vía de reenvío aislada por tráfico para la transmisión de tráfico de red en el {harvester-product-name} clúster.

== *clúster de invitados* / *clúster de Kubernetes de invitados*

Grupo de máquinas virtuales integradas que se ejecutan sobre un {harvester-product-name} clúster.

Puedes crear clústeres de invitados RKE2 y K3s utilizando las interfaces {harvester-product-name} y {rancher-product-name}. La creación de clústeres de invitados implica obtener imágenes de internet o de un registro privado.

Los clústeres de invitados forman la infraestructura principal para ejecutar cargas de trabajo en contenedores. Ciertas versiones de {harvester-product-name} y {rancher-product-name} te permiten desplegar cargas de trabajo en contenedores xref:integrations/rancher/rancher-integration.adoc#_bare_metal_container_workload_support_experimental[directamente en {harvester-product-name} clústeres] (con algunas limitaciones).

== *nodo de invitados* / *nodo de clúster de invitados*

Máquina virtual que utiliza los recursos del {harvester-product-name} clúster para ejecutar cargas de trabajo en contenedores.

Los nodos de invitados se gestionan a través de un plano de control que controla la actividad relacionada con los pods y mantiene el estado deseado del clúster.

== *{harvester-product-name} clúster*

Grupo de servidores físicos integrados (hosts) en los que está instalado el {harvester-product-name} hipervisor. Estos servidores gestionan colectivamente los recursos de computación, memoria y almacenamiento para proporcionar un entorno para ejecutar máquinas virtuales.

Se requiere un clúster de tres nodos para realizar plenamente las características de múltiples nodos de {harvester-product-name}, particularmente la alta disponibilidad. Las versiones más recientes te permiten crear clústeres con dos nodos de gestión y un xref:hosts/witness-node.adoc[nodo testigo] (y opcionalmente, uno o más nodos de trabajo). También puedes crear xref:installation-setup/single-node-clusters.adoc[clústeres de un solo nodo] que soportan la mayoría de las características (excluyendo alta disponibilidad, soporte multi-replica y migración en vivo).

Los clústeres {harvester-product-name} pueden ser importados y gestionados por {rancher-product-name}. Dentro de este contexto, un clúster {harvester-product-name} importado se conoce como "clúster downstream" o "clúster de usuario descendente" (a menudo abreviado como "clúster descendente"). El término se refiere a cualquier clúster de Kubernetes que esté conectado a un {rancher-product-name} servidor.

Ciertas versiones de {harvester-product-name} y {rancher-product-name} permiten desplegar cargas de trabajo en contenedores directamente en clústeres {harvester-product-name} (con algunas limitaciones). Cuando esta xref:integrations/rancher/rancher-integration.adoc#_bare_metal_container_workload_support_experimental[característica experimental] está habilitada, las cargas de trabajo en contenedores interactúan sin problemas con las cargas de trabajo de máquinas virtuales.

== *{harvester-product-name} hipervisor*

Sistema operativo especializado y xref:introduction/overview.adoc#_architecture[conjunto de software] que se ejecuta en un único servidor físico.

== *{harvester-product-name} ISO*

Imagen de instalación que contiene los componentes del kernel del sistema operativo y todas las imágenes de contenedor requeridas, que se precargan durante la instalación.

== *{harvester-product-name} nodo*

Servidor físico en el que está instalado el {harvester-product-name} hipervisor.

Cada nodo que se une a un {harvester-product-name} clúster debe ser asignado a un xref:hosts/hosts.adoc#_role_management[rol] que determina las funciones que el nodo puede realizar dentro del clúster. Todos los {harvester-product-name} nodos procesan datos, pero no todos pueden almacenar datos.

== *Proveedor de Nube Harvester*

Componente que permite que un clúster downstream ({harvester-product-name}), gestionado por {rancher-short-name}, funcione como un xref:integrations/rancher/cloud-provider.adoc[backend nativo de nube para clústeres Kubernetes invitados]. El Proveedor de Nube Harvester integra el administrador de controladores de nube de Kubernetes (CCM) y el controlador de interfaz de almacenamiento de contenedores (CSI), permitiendo que los clústeres invitados soliciten y gestionen dinámicamente recursos nativos de {harvester-product-name} (balanceador de carga y almacenamiento) sin intervención manual.

== *Controlador CSI de Harvester*

Controlador que xref:integrations/rancher/csi-driver.adoc[proporciona una interfaz estándar de almacenamiento de contenedores (CSI) para clústeres Kubernetes invitados], permitiendo que las cargas de trabajo en contenedores utilicen la solución de almacenamiento integrada con el {harvester-product-name} clúster subyacente. Este componente permite la conexión en caliente de volúmenes a las máquinas virtuales para proporcionar un rendimiento de almacenamiento nativo.

== *Controlador de Nodo Harvester*

Controlador que {rancher-product-name} utiliza para xref:integrations/rancher/node-driver/node-driver.adoc[provisionar máquinas virtuales en un {harvester-product-name} clúster], y para lanzar y gestionar clústeres Kubernetes invitados sobre esas máquinas virtuales.

== *migración en vivo*

Proceso de xref:virtual-machines/live-migration.adoc[mover una máquina virtual en ejecución a otro nodo] dentro del mismo {harvester-product-name} clúster sin interrumpir el sistema operativo invitado y causar tiempo de inactividad en la carga de trabajo. La migración en vivo solo puede ocurrir cuando se cumplen los xref:virtual-machines/live-migration.adoc#_prerequisites[requisitos previos] y cuando las máquinas virtuales afectadas son xref:virtual-machines/live-migration.adoc#_live_migratable_virtual_machines[migrables en vivo].

== *gestión*

Red de clúster que se xref:networking/cluster-network.adoc#_built_in_cluster_network[crea automáticamente] durante la ampliación del {harvester-product-name} clúster y que siempre está habilitada en todos los hosts. {harvester-product-name} utiliza `mgmt` para las comunicaciones intra-clúster y las tareas de gestión del clúster.

== *ISO de instalación de red*

Imagen de instalación que contiene solo los xref:installation-setup/media/net-install.adoc[componentes del kernel {harvester-product-name} del sistema operativo], permitiendo que el instalador arranque y luego instale el sistema operativo en un disco. Después de que se completa la instalación, el sistema operativo descarga todas las imágenes de contenedor requeridas de internet.

== *configuración de red*

Definición de cómo un conjunto de nodos de clúster con especificaciones de red uniformes se conecta a una red de clúster específica.

== *red de superposición*

Red virtual que representa un conmutador virtual de capa 2 que xref:networking/vm-network.adoc#_overlay_network_experimental[encapsula y reenvía el tráfico entre máquinas virtuales]. Las redes de superposición admiten capacidades avanzadas de redes definidas por software (SDN) como nubes privadas virtuales (VPC) y subredes para cargas de trabajo de máquinas virtuales.

== *red de almacenamiento*

Red para xref:networking/storage-network.adoc[aislar el tráfico de replicación de Longhorn] del tráfico intra-clúster en `mgmt` y otras cargas de trabajo a nivel de clúster.

== *red troncal VLAN*

Red virtual que proporciona a una máquina virtual una única interfaz de red que puede transportar tráfico para xref:networking/vm-network.adoc#_vlan_trunk_network[varios rangos de ID de VLAN superpuestos] simultáneamente. Cuando una máquina virtual está conectada a una red troncal VLAN, se permite al sistema operativo invitado y a las aplicaciones enviar y recibir paquetes etiquetados con cualquiera de los ID de VLAN dentro del rango especificado.

== *red de migración de VM*

Red para xref:networking/vm-migration-network.adoc[aislar el tráfico de migración de máquinas virtuales] del tráfico intra-clúster en `mgmt` y otras cargas de trabajo a nivel de clúster.

== *red de VM*

Red virtual vinculada a una red de clúster específica que permite la comunicación entre máquinas virtuales y la red externa.

== *nodo testigo*

xref:hosts/witness-node.adoc[nodo no computacional] utilizado únicamente para mantener el consenso del clúster. Asegura que el sistema pueda alcanzar una decisión mayoritaria (quórum) sobre las actualizaciones del clúster, incluso si un nodo de gestión se vuelve no disponible o ocurre una falla de red.

Los nodos testigos no ejecutan cargas de trabajo ni almacenan datos. Cada {harvester-product-name} clúster puede tener solo un nodo testigo.