= Descripción general
:revdate: 16/07/2025
:page-revdate: {revdate}

{harvester-product-name-tm} es una solución de https://en.wikipedia.org/wiki/Hyper-converged_infrastructure[infraestructura hiperconvergente (HCI)] moderna, abierta e interoperable construida sobre Kubernetes. Es una alternativa de código abierto diseñada para operadores que buscan una solución HCI https://about.gitlab.com/topics/cloud-native/[nativa de nube]. {harvester-product-name} se ejecuta en servidores sin sistema operativo y proporciona capacidades de virtualización integrada y almacenamiento distribuido. Además de las máquinas virtuales tradicionales (VMs), {harvester-product-name} admite entornos en contenedores automáticamente gracias a la integración con https://documentation.suse.com/cloudnative/rancher-manager/v2.11/en/integrations/harvester/harvester.html[{rancher-product-name-tm}]. Ofrece una solución que unifica la infraestructura virtualizada heredada al tiempo que permite la adopción de contenedores tanto desde ubicaciones centrales como periféricas.

== Arquitectura

La arquitectura consiste en tecnologías de código abierto de vanguardia:

* *Linux OS.* https://documentation.suse.com/cloudnative/os-manager/[{elemental-product-name}] para SUSE Linux Enterprise Micro está en el núcleo de {harvester-product-name} y es una distribución de Linux inmutable diseñada para eliminar tanto mantenimiento del sistema operativo como sea posible en un clúster de Kubernetes.
* *Construido sobre Kubernetes.* https://kubernetes.io/[Kubernetes] se ha convertido en el lenguaje de infraestructura predominante en todos los factores de forma, y {harvester-product-name} es una solución HCI con Kubernetes bajo el capó.
* *Gestión de virtualización con KubeVirt.* https://kubevirt.io/[KubeVirt] proporciona gestión de virtualización utilizando KVM sobre Kubernetes.
* *Gestión de almacenamiento con {longhorn-product-name}.* https://documentation.suse.com/cloudnative/storage/1.8/en/longhorn-documentation.html[{longhorn-product-name}] proporciona almacenamiento en bloques distribuido y jerarquización.
* *Observabilidad con Grafana y Prometheus.* https://grafana.com/[Grafana] y https://prometheus.io/[Prometheus] proporcionan monitoreo y registro robustos.

image::architecture.svg[]

== Funciones

{harvester-product-name} es una plataforma de infraestructura lista para empresas y fácil de usar que aprovecha el almacenamiento local, conectado directamente, en lugar de complejos SAN externos. Utiliza la API de Kubernetes como un lenguaje de automatización unificado para cargas de trabajo de contenedores y máquinas virtuales. Algunas características clave incluyen:

* *Fácil de empezar.* Dado que {harvester-product-name} se envía como una imagen de appliance arrancable, puedes instalarlo directamente en un servidor sin sistema operativo con la https://github.com/harvester/harvester/releases[imagen ISO] o instalarlo automáticamente utilizando scripts de xref:../installation-setup/methods/pxe-boot-install.adoc[iPXE].
* *Gestión del ciclo de vida de máquinas virtuales.* Crea, edita, clona y elimina VMs fácilmente, incluyendo inyección de clave SSH, cloud-init y consola de puerto gráfico y serial.
* *Migración en vivo de VMs.* Mueve una VM a un host o nodo diferente sin tiempo de inactividad.
* *Copia de seguridad, instantánea y restauración de VMs.* Realiza copias de seguridad de tus VMs desde servidores NFS, S3 o dispositivos NAS. Utiliza tu copia de seguridad para restaurar una máquina virtual fallida o crear una nueva máquina virtual en un clúster diferente.
* *La gestión del almacenamiento.* {harvester-product-name} soporta almacenamiento en bloques distribuido y jerarquización. Los volúmenes representan almacenamiento; puedes crear, editar, clonar o exportar un volumen fácilmente.
* *La gestión de redes.* Soporta el uso de una IP virtual (VIP) y múltiples tarjetas NIC (NICs). Si tus máquinas virtuales necesitan conectarse a la red externa, crea una VLAN o una red sin etiquetar.
* *Integración con {rancher-product-name}.* Accede a {harvester-product-name} directamente a través de la página de Gestión de Virtualización de {rancher-product-name} y gestiona tus cargas de trabajo de máquinas virtuales junto a tus clústeres de Kubernetes.

== Interfaz de usuario

{harvester-product-name} proporciona una interfaz web potente y fácil de usar para visualizar y gestionar tu infraestructura. Una vez instalado, puedes acceder a la dirección IP de la interfaz de usuario desde la terminal del nodo.

+++++++++<iframe width="99%" height="450" src="https://www.youtube.com/embed/Ngsk7m6NYf4" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">[]++++++</iframe>+++++++++
