= ISO de Instalação pela Rede
:revdate: 2025-05-09
:page-revdate: {revdate}

A ISO de instalação pela rede é uma imagem de instalação mínima que contém apenas os componentes do kernel do sistema operacional, permitindo que o instalador inicialize e, em seguida, instale o sistema operacional em um disco. Após a conclusão da instalação, o sistema operacional baixa todas as imagens de contêiner necessárias da internet (principalmente do Docker Hub).

Você pode usar a ISO de instalação pela rede nas seguintes situações:

* A implementação de mídia virtual em um servidor apresenta falhas ou lentidão. Alguns usuários relataram que a redireção de ISO é muito lenta para pré-carregar todas as imagens em um sistema. Para mais informações, veja https://github.com/harvester/harvester/issues/2651[Problema 2651].
* Você tem um registro privado que contém todas as {harvester-product-name} imagens, bem como o conhecimento e a experiência necessários para configurar espelhos de imagem para o containerd.

[CAUTION]
====
*Você deve sempre usar a ISO completa para inicializar um cluster {harvester-product-name}* (em outras palavras, use a ISO sem o sufixo `-net-install`). A ISO completa contém todas as imagens necessárias, e o instalador pré-carrega essas imagens durante a instalação. Você pode facilmente atingir o https://docs.docker.com/docker-hub/download-rate-limit/[limite de taxa do Docker Hub] ao usar uma ISO de instalação pela rede para inicializar o cluster.
====

== Uso

Baixe a ISO de instalação pela rede da página de https://github.com/harvester/harvester/releases[Releases] do GitHub e, em seguida, inicialize a ISO para instalar {harvester-product-name}. Os nomes de arquivo da ISO de instalação pela rede têm o sufixo `net-install` (por exemplo, https://releases.rancher.com/harvester/v1.3.0/harvester-v1.3.0-amd64-net-install.iso).

== Instalação PXE

Se você decidir usar a ISO de instalação pela rede como fonte de instalação PXE, adicione o seguinte parâmetro ao inicializar o kernel:

----
harvester.install.with_net_images=true
----

Para mais informações, veja xref:../../installation-setup/methods/pxe-boot-install.adoc[Instalação PXE].
