= Convenções de Documentação
:revdate: 2025-07-16
:page-revdate: {revdate}

== Tipos de Lançamento

Os termos "Comunidade" e "Prime" são usados para diferenciar os lançamentos destinados a usuários da comunidade e clientes da SUSE. "Prime" refere-se a https://www.suse.com/products/rancher[SUSE Rancher Prime], que é a plataforma de gerenciamento de contêiner empresarial da SUSE.

|===
| Tipo de Lançamento | Convenção de Versionamento | Exemplo | Ciclo de Vida do Suporte

| Comunidade
| x.y.z
| v1.5.0
| O suporte para cada lançamento da comunidade termina quando a versão x.(y+1).1 é lançada.

| Prime
| x.y.[1-z]
| v1.5.1
| Os lançamentos Prime recebem 6 meses de suporte ativo. Isso é seguido por 12 meses de suporte de manutenção, que cobre questões críticas relacionadas à segurança.
|===

== Rótulos de Lançamento

A documentação {harvester-product-name} usa os seguintes rótulos para descrever os lançamentos do software.

* *Dev*: O software está em desenvolvimento ativo e não foi testado de forma abrangente. A atualização de lançamentos anteriores ou para lançamentos posteriores não é suportada. Os lançamentos "Dev" geralmente ocorrem no final de um sprint e podem ocorrer quando outras definições de pronto são atendidas.
* *Mais Recente*: O software passou por todas as etapas de verificação e testes. Todos os problemas conhecidos restantes são considerados aceitáveis.
* *EOL*: O software atingiu o fim de sua vida útil e nenhuma manutenção adicional a nível de código é fornecida. Você pode continuar a usar o software dentro dos termos do contrato de licença.

== Rótulos de Recursos

Recursos que estão rotulados como *Experimental* e *Prévia Técnica* oferecem vislumbres de inovações futuras e oportunidades para testar novas tecnologias em seu ambiente.

* *Experimental*: O recurso está incompleto, mas sua funcionalidade essencial está operacional. Testes em um ambiente controlado mostraram que ele pode coexistir com recursos estáveis existentes. Devido aos componentes ausentes e/ou funcionalidade em evolução, o recurso não é recomendado para uso em ambientes de produção.
* *Visualização Técnica*: O recurso está quase completo e sua funcionalidade não deve mudar significativamente. Testes em um ambiente controlado mostraram que ele pode coexistir com recursos estáveis existentes. Explore o recurso extensivamente antes de usá-lo em ambientes de produção.

Esses recursos têm as seguintes limitações:

* Ainda em desenvolvimento e pode estar funcionalmente incompleto, instável ou de outras maneiras inadequado para uso em produção.
* Não suportado.
* Pode estar disponível apenas para arquiteturas de hardware específicas. Detalhes e funcionalidade estão sujeitos a alterações. Consequentemente, a atualização para versões subsequentes pode ser impossível e pode exigir uma instalação nova.
* Pode ser removido do produto a qualquer momento. Isso pode ocorrer, por exemplo, se descobrirmos que o recurso não atende às necessidades dos clientes ou do mercado, ou não está em conformidade com os padrões empresariais.

[NOTE]
====
Recursos *Experimental* e *Visualização Técnica* geralmente estão desativados por padrão. A documentação fornece informações sobre como você pode habilitar e configurar tais recursos.
====

== Admoestações

Admoestações são blocos de texto que fornecem informações adicionais ou importantes. Cada bloco de texto é marcado com um rótulo e ícone especiais. A documentação {harvester-product-name} usa as seguintes convenções para ajudá-lo a interpretar as informações.

* *Nota*: Informações adicionais que são úteis, mas não críticas.
* *Importante*: Informações que requerem atenção especial, como mudanças no comportamento do produto.
* *Dica*: Conselhos e sugestões úteis, como métodos alternativos para completar uma tarefa.
* *Cuidado*: Informações que devem ser consideradas antes de prosseguir com ações específicas, como erros que podem ocorrer.
* *Aviso*: Informações críticas sobre consequências prejudiciais, como danos irreversíveis e perda de dados.