= Glossário
:revdate: 2026-01-27
:page-revdate: {revdate}

== *cluster de rede*

Caminho isolado para transmissão de tráfego de rede no {harvester-product-name} cluster.

== *cluster convidado* / *cluster Kubernetes convidado*

Grupo de máquinas virtuais integradas que rodam em um {harvester-product-name} cluster.

Você pode criar clusters convidados RKE2 e K3s usando as interfaces {harvester-product-name} e {rancher-product-name}. Criar clusters convidados envolve baixar imagens da internet ou de um registro privado.

Clusters convidados formam a infraestrutura principal para executar cargas de trabalho em contêineres. Certas versões de {harvester-product-name} e {rancher-product-name} permitem que você implante cargas de trabalho de contêiner xref:integrations/rancher/rancher-integration.adoc#_bare_metal_container_workload_support_experimental[diretamente em {harvester-product-name} clusters] (com algumas limitações).

== *nó convidado* / *nó de cluster convidado*

Máquina virtual que utiliza recursos do {harvester-product-name} cluster para executar cargas de trabalho em contêineres.

Nós convidados são gerenciados através de um plano de controle que controla a atividade relacionada a pods e mantém o estado desejado do cluster.

== *{harvester-product-name} cluster*

Grupo de servidores físicos integrados (hosts) nos quais o {harvester-product-name} hipervisor está instalado. Esses servidores gerenciam coletivamente recursos de computação, memória e armazenamento para fornecer um ambiente para executar máquinas virtuais.

Um cluster de três nós é necessário para aproveitar totalmente os recursos de múltiplos nós do {harvester-product-name}, particularmente alta disponibilidade. As versões mais recentes permitem que você crie clusters com dois nós de gerenciamento e um xref:hosts/witness-node.adoc[nó testemunha] (e opcionalmente, um ou mais nós de trabalho). Você também pode criar xref:installation-setup/single-node-clusters.adoc[clusters de nó único] que suportam a maioria dos recursos (excluindo alta disponibilidade, suporte a múltiplas réplicas e migração em tempo real).

Clusters {harvester-product-name} podem ser importados e gerenciados pelo {rancher-product-name}. Dentro deste contexto, um {harvester-product-name} cluster importado é conhecido como "cluster gerenciado" ou "cluster downstream de usuário" (frequentemente abreviado como "cluster downstream"). O termo refere-se a qualquer cluster do Kubernetes que esteja conectado a um {rancher-product-name} servidor.

Certas versões de {harvester-product-name} e {rancher-product-name} permitem que você implante cargas de trabalho de contêiner diretamente em {harvester-product-name} clusters (com algumas limitações). Quando este xref:integrations/rancher/rancher-integration.adoc#_bare_metal_container_workload_support_experimental[recurso experimental] está habilitado, as cargas de trabalho de contêiner interagem perfeitamente com as cargas de trabalho de máquinas virtuais.

== *{harvester-product-name} hipervisor*

Sistema operacional especializado e xref:introduction/overview.adoc#_architecture[pilha de software] que roda em um único servidor físico.

== *{harvester-product-name} ISO*

Imagem de instalação que contém os componentes principais do sistema operacional e todas as imagens de contêiner necessárias, que são pré-carregadas durante a instalação.

== *{harvester-product-name} nó*

Servidor físico no qual o {harvester-product-name} hipervisor está instalado.

Cada nó que se junta a um {harvester-product-name} cluster deve receber uma xref:hosts/hosts.adoc#_role_management[função] que determina as funções que o nó pode desempenhar dentro do cluster. Todos os {harvester-product-name} nós processam dados, mas nem todos podem armazenar dados.

== *Provedor de Nuvem Harvester*

Componente que permite que um cluster gerenciado por {rancher-short-name} {harvester-product-name} funcione como um xref:integrations/rancher/cloud-provider.adoc[backend nativo de nuvem para clusters Kubernetes convidados]. O Provedor de Nuvem Harvester integra o gerenciador de controladores de nuvem Kubernetes (CCM) e o driver de interface de armazenamento de contêiner (CSI), permitindo que clusters convidados solicitem e gerenciem dinamicamente recursos nativos de {harvester-product-name} (balanceador de carga e armazenamento) sem intervenção manual.

== *Harvester CSI Driver*

Driver que xref:integrations/rancher/csi-driver.adoc[fornece uma interface padrão de armazenamento de contêiner (CSI) para clusters Kubernetes convidados], permitindo que cargas de trabalho de contêiner utilizem a solução de armazenamento integrada com o {harvester-product-name} cluster subjacente. Este componente permite o hot plugging de volumes às máquinas virtuais para fornecer desempenho de armazenamento nativo.

== *Harvester Node Driver*

Driver que {rancher-product-name} usa para xref:integrations/rancher/node-driver/node-driver.adoc[provisionar máquinas virtuais em um {harvester-product-name} cluster], e para iniciar e gerenciar clusters Kubernetes convidados sobre essas máquinas virtuais.

== *migração ao vivo*

Processo de xref:virtual-machines/live-migration.adoc[mover uma máquina virtual em execução para outro nó] dentro do mesmo {harvester-product-name} cluster sem interromper o sistema operacional convidado e causar tempo de inatividade da carga de trabalho. A migração ao vivo pode ocorrer apenas quando os xref:virtual-machines/live-migration.adoc#_prerequisites[pré-requisitos] são atendidos e quando as máquinas virtuais afetadas são xref:virtual-machines/live-migration.adoc#_live_migratable_virtual_machines[migráveis ao vivo].

== *mgmt*

Rede de cluster que é xref:networking/cluster-network.adoc#_built_in_cluster_network[criada automaticamente] durante a {harvester-product-name} implantação do cluster e está sempre habilitada em todos os hosts. {harvester-product-name} usa `mgmt` para comunicações intra-cluster e tarefas de gerenciamento do cluster.

== *imagem ISO de instalação de rede*

Imagem de instalação que contém apenas os xref:installation-setup/media/net-install.adoc[componentes {harvester-product-name} principais do sistema operacional], permitindo que o instalador inicialize e, em seguida, instale o sistema operacional em um disco. Após a conclusão da instalação, o sistema operacional baixa todas as imagens de contêiner necessárias da internet.

== *configuração de rede*

Definição de como um conjunto de nós de cluster com especificações de rede uniformes se conecta a uma rede de cluster específica.

== *rede overlay*

Rede virtual que representa um switch virtual de camada 2 que xref:networking/vm-network.adoc#_overlay_network_experimental[encapsula e encaminha o tráfego entre máquinas virtuais]. Redes overlay suportam capacidades avançadas de rede definida por software (SDN), como nuvens privadas virtuais (VPCs) e sub-redes para cargas de trabalho de máquinas virtuais.

== *rede de armazenamento*

Rede para xref:networking/storage-network.adoc[isolar o tráfego de replicação do Longhorn] do tráfego intra-cluster em `mgmt` e outras cargas de trabalho em todo o cluster.

== *rede trunk VLAN*

Rede virtual que fornece a uma máquina virtual uma única interface de rede que pode transportar tráfego para xref:networking/vm-network.adoc#_vlan_trunk_network[vários intervalos de ID de VLAN sobrepostos] simultaneamente. Quando uma máquina virtual está conectada a uma rede VLAN trunk, o sistema operacional convidado e os aplicativos podem enviar e receber pacotes marcados com qualquer um dos IDs de VLAN dentro do intervalo especificado.

== *rede de migração de VM*

Rede para xref:networking/vm-migration-network.adoc[isolar o tráfego de migração de máquinas virtuais] do tráfego intra-cluster em `mgmt` e outras cargas de trabalho em todo o cluster.

== *rede de VM*

Rede virtual vinculada a uma rede de cluster específica que permite a comunicação entre máquinas virtuais e a rede externa.

== *nó testemunha*

xref:hosts/witness-node.adoc[nó não computacional] utilizado exclusivamente para manter o consenso do cluster. Ele garante que o sistema possa alcançar uma decisão de maioria (quorum) sobre as atualizações do cluster, mesmo que um nó de gerenciamento se torne indisponível ou ocorra uma falha de rede.

Os nós testemunha não executam cargas de trabalho e não armazenam dados. Cada {harvester-product-name} cluster pode ter apenas um nó testemunha.