= Visão Geral
:revdate: 2025-07-16
:page-revdate: {revdate}

{harvester-product-name-tm} é uma solução moderna, aberta, interoperável e https://en.wikipedia.org/wiki/Hyper-converged_infrastructure[hiperconvergente (HCI)] construída sobre o Kubernetes. É uma alternativa de código aberto projetada para operadores que buscam uma solução HCI https://about.gitlab.com/topics/cloud-native/[nativa de nuvem]. {harvester-product-name} opera em servidores bare metal e fornece virtualização integrada e capacidades de armazenamento distribuído. Além das máquinas virtuais (VMs) tradicionais, {harvester-product-name} oferece suporte automático a ambientes conteinerizados por meio da integração com https://documentation.suse.com/cloudnative/rancher-manager/v2.11/en/integrations/harvester/harvester.html[{rancher-product-name-tm}]. Ele oferece uma solução que unifica a infraestrutura virtualizada antiga e, ao mesmo tempo, permite a adoção de contêineres de locais que vão do núcleo à borda.

== Arquitetura

A arquitetura consiste em tecnologias de código aberto de ponta:

* *Sistema Operacional Linux.* https://documentation.suse.com/cloudnative/os-manager/[{elemental-product-name}] para SUSE Linux Enterprise Micro está no núcleo de {harvester-product-name} e é uma distribuição Linux imutável projetada para remover o máximo possível de manutenção do SO em um cluster Kubernetes.
* *Construído sobre o Kubernetes.* https://kubernetes.io/[Kubernetes] se tornou a linguagem de infraestrutura predominante em todos os fatores de forma, e {harvester-product-name} é uma solução HCI com Kubernetes por trás.
* *Gerenciamento de virtualização com KubeVirt.* https://kubevirt.io/[KubeVirt] fornece gerenciamento de virtualização usando KVM sobre o Kubernetes.
* *Gerenciamento de armazenamento com {longhorn-product-name}.* https://documentation.suse.com/cloudnative/storage/1.8/en/longhorn-documentation.html[{longhorn-product-name}] fornece armazenamento em blocos distribuído e gerenciamento de níveis.
* *Observabilidade com Grafana e Prometheus.* https://grafana.com/[Grafana] e https://prometheus.io/[Prometheus] fornecem monitoramento robusto e registro robusto.

image::architecture.svg[]

== Recursos

{harvester-product-name} é uma plataforma de infraestrutura pronta para empresas e fácil de usar, que aproveita o armazenamento local, diretamente conectado, em vez de SANs externas complexas. Utiliza a API do Kubernetes como uma linguagem de automação unificada para cargas de trabalho de contêineres e VMs. Alguns recursos principais incluem:

* *Fácil de começar.* Como {harvester-product-name} é fornecido como uma imagem de appliance inicializável, você pode instalá-lo diretamente em um servidor bare metal com a https://github.com/harvester/harvester/releases[imagem ISO] ou instalá-lo automaticamente usando scripts xref:../installation-setup/methods/pxe-boot-install.adoc[iPXE].
* *Gerenciamento do ciclo de vida da VM.* Crie, edite, clone e exclua VMs facilmente, incluindo injeção de chave SSH, cloud-init e console gráfico e de porta serial.
* *Migração ao vivo da VM.* Mova uma VM para um host ou nó diferente sem tempo de inatividade.
* *Backup, instantâneo e restauração da VM.* Faça backup de suas VMs a partir de servidores NFS, S3 ou dispositivos NAS. Use seu backup para restaurar uma VM que falhou ou criar uma nova VM em um cluster diferente.
* *Gerenciamento de armazenamento.* {harvester-product-name} suporta armazenamento em blocos distribuído e gerenciamento de níveis. Volumes representam armazenamento; você pode facilmente criar, editar, clonar ou exportar um volume.
* *Gerenciamento de rede.* Suporta o uso de um IP virtual (VIP) e múltiplas interfaces de rede (NICs). Se suas VMs precisarem se conectar à rede externa, crie uma VLAN ou uma rede sem marcação.
* *Integração com {rancher-product-name}.* Acesse {harvester-product-name} diretamente pela página de Gerenciamento de Virtualização do {rancher-product-name} e gerencie suas cargas de trabalho de VM junto com seus clusters Kubernetes.

== Interface do usuário

{harvester-product-name} fornece uma interface poderosa e fácil de usar baseada na web para visualizar e gerenciar sua infraestrutura. Uma vez instalado, você pode acessar o endereço IP da interface do usuário a partir do terminal do nó.

+++++++++<iframe width="99%" height="450" src="https://www.youtube.com/embed/Ngsk7m6NYf4" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">[]++++++</iframe>+++++++++
