= ISO d'installation réseau
:revdate: 2025-05-09
:page-revdate: {revdate}

L'ISO d'installation réseau est une image d'installation minimale qui contient uniquement les composants du noyau du système d'exploitation, permettant à l'installateur de démarrer puis d'installer le système d'exploitation sur un disque. Une fois l'installation terminée, le système d'exploitation récupère toutes les images de conteneur requises depuis Internet (principalement depuis Docker Hub).

Vous pouvez utiliser l'ISO d'installation réseau dans les situations suivantes{nbsp}:

* L'implémentation des médias virtuels sur un serveur est boguée ou lente. Certains utilisateurs ont signalé que la redirection ISO est trop lente pour précharger toutes les images sur un système. Pour plus d'informations, voir https://github.com/harvester/harvester/issues/2651[Problème 2651].
* Vous avez un registre privé qui contient toutes {harvester-product-name} les images, ainsi que les connaissances et l'expérience nécessaires pour configurer des miroirs d'images pour containerd.

[CAUTION]
====
*Vous devez toujours utiliser l'ISO complet pour démarrer un cluster {harvester-product-name}* (en d'autres termes, utilisez l'ISO sans le suffixe `-net-install`). L'ISO complet contient toutes les images requises, et l'installateur précharge ces images pendant l'installation. Vous pouvez facilement atteindre la https://docs.docker.com/docker-hub/download-rate-limit/[limite de taux de Docker Hub] lorsque vous utilisez une ISO d'installation réseau pour démarrer le cluster.
====

== Syntaxe

Téléchargez l'ISO d'installation réseau depuis la page https://github.com/harvester/harvester/releases[Releases] de GitHub, puis démarrez l'ISO pour installer {harvester-product-name}. Les noms de fichier ISO d'installation réseau ont le suffixe `net-install` (par exemple, https://releases.rancher.com/harvester/v1.3.0/harvester-v1.3.0-amd64-net-install.iso).)

== Installation PXE

Si vous décidez d'utiliser l'ISO d'installation réseau comme source d'installation PXE, ajoutez le paramètre suivant lors du démarrage du noyau Linux{nbsp}:

----
harvester.install.with_net_images=true
----

Pour plus d'informations, voir xref:../../installation-setup/methods/pxe-boot-install.adoc[Installation de démarrage PXE].
