= NIC Hotplug
:revdate: 2026-01-02
:page-revdate: {revdate}

{harvester-product-name} supports hotplugging and hotunplugging of network interface controllers (NICs) for xref:virtual-machines/live-migration.adoc#_live_migratable_virtual_machines[live-migratable] virtual machines. This feature allows you to add and remove network interfaces from a running virtual machine without requiring a reboot.

[NOTE]
====
You cannot perform NIC hotplugging on virtual machines created in clusters running {harvester-product-name} versions earlier than v1.7.0 _if the network interface's MAC address was not explicitly configured_. To enable this feature, you must restart those virtual machines. Restarting allows the system to automatically save the observed MAC addresses to the virtual machine's configuration.

In addition, virtual machines created using the xref:integrations/rancher/node-driver/node-driver.adoc[Harvester Node Driver] and the xref:integrations/terraform/terraform-provider.adoc[Harvester Terraform Provider] _do not support_ NIC hotplugging and hotunplugging.
====

== Hotplug NICs to a running virtual machine

. On the {harvester-product-name} UI, go to the *Virtual Machines* screen.

. Locate the target virtual machine, and then select *⋮ -> Hotplug Network Interface*.

. Specify a name for the network interface and select a virtual machine network.
+
You can select a xref:networking/vm-network.adoc#_vlan_network[VLAN network], an xref:networking/vm-network.adoc#_untagged_network[untagged network], or a xref:networking/vm-network.adoc#_vlan_trunk_network[VLAN trunk network].

. Click *Apply*.

{harvester-product-name} xref:virtual-machines/live-migration.adoc#_prerequisites[migrates the virtual machine] and the specified interface is connected through bridge binding.

For information about limitations to the number of hotplugged interfaces, see https://kubevirt.io/user-guide/network/hotplug_interfaces/#virtio-limitations[Virtio Limitations] in the KubeVirt documentation.

== Hotunplug NICs from a running virtual machine

[IMPORTANT]
====
You can perform this action only when the following conditions are met:

* The virtual machine has at least two network interfaces. You cannot hotunplug the single remaining interface.
* The target interface is connected through bridge binding.
====

. On the {harvester-product-name} UI, go to the *Virtual Machines* screen.

. Click the name of the target virtual machine, and then go to the *Networks* tab.

. Locate the target interface, and then click *Detach Network Interface*.

{harvester-product-name} xref:virtual-machines/live-migration.adoc#_prerequisites[migrates the virtual machine] and detaches the interface.