= Overview
:revdate: 2026-05-29
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-16
:page-revdate: {revdate}

{harvester-product-name-tm} is a modern, open, interoperable, https://en.wikipedia.org/wiki/Hyper-converged_infrastructure[hyperconverged infrastructure (HCI)] solution built on Kubernetes. It is an open-source alternative designed for operators seeking a https://about.gitlab.com/topics/cloud-native/[cloud-native] HCI solution. {harvester-product-name} runs on bare metal servers and provides integrated virtualization and distributed storage capabilities. In addition to traditional virtual machines (VMs), {harvester-product-name} supports containerized environments automatically through integration with https://documentation.suse.com/cloudnative/rancher-manager/[{rancher-product-name-tm}]. It offers a solution that unifies legacy virtualized infrastructure while enabling the adoption of containers from core to edge locations.

== Architecture

The architecture consists of cutting-edge open-source technologies:

* *Linux operating system*: https://documentation.suse.com/cloudnative/os-manager/[{elemental-product-name}] for SUSE Linux Enterprise Micro is at the core of {harvester-product-name} and is an immutable Linux distribution designed to remove as much operating system maintenance as possible in a Kubernetes cluster.
* *Built on top of Kubernetes*: https://kubernetes.io/[Kubernetes] has become the predominant infrastructure language across all form factors, and {harvester-product-name} is an HCI solution with Kubernetes under the hood.
* *Virtualization management with KubeVirt*: https://kubevirt.io/[KubeVirt] provides virtualization management using KVM on top of Kubernetes.
* *Distributed block storage*: https://documentation.suse.com/cloudnative/storage/[{longhorn-product-name-tm}] is the built-in storage system that provides block device volumes to virtual machines and other pods in the cluster. {harvester-product-name} also supports provisioning of root volumes and data volumes using external https://kubernetes-csi.github.io/docs/introduction.html[Container Storage Interface (CSI)] drivers.
* *Observability with Grafana and Prometheus*: https://grafana.com/[Grafana] and https://prometheus.io/[Prometheus] provide robust monitoring and logging.

image::introduction/architecture.svg[]

== Features

{harvester-product-name} is an enterprise-ready, easy-to-use infrastructure platform that leverages local, direct attached storage instead of complex external SANs. It utilizes Kubernetes API as a unified automation language across container and VM workloads. Some key features include:

* *Easy to get started.* Since {harvester-product-name} ships as a bootable appliance image, you can install it directly on a bare metal server with the xref:installation-setup/methods/iso-install.adoc[ISO image] or automatically install it using xref:installation-setup/methods/pxe-boot-install.adoc[iPXE] scripts.
* *VM lifecycle management.* Easily create, edit, clone, and delete VMs, including SSH-Key injection, cloud-init, and graphic and serial port console.
* *VM live migration.* Move a VM to a different host or node with zero downtime.
* *VM backup, snapshot, and restore.* Back up your VMs from NFS, S3 servers, or NAS devices. Use your backup to restore a failed VM or create a new VM on a different cluster.
* *Storage management.* {harvester-product-name} supports distributed block storage. Volumes represent storage; you can easily create, edit, clone, or export a volume.
* *Network management.* Supports using a virtual IP (VIP) and multiple Network Interface Cards (NICs). If your VMs need to connect to the external network, create a VLAN or untagged network.
* *Integration with {rancher-product-name}.* Access {harvester-product-name} directly through {rancher-product-name}'s Virtualization Management page and manage your VM workloads alongside your Kubernetes clusters.

== User Interface

{harvester-product-name} provides a powerful and easy-to-use web-based interface for visualizing and managing your infrastructure. Once installed, you can access the IP address for the UI from the node's terminal.

+++<div class="text-center">++++++<iframe width="99%" height="450" src="https://www.youtube.com/embed/Ngsk7m6NYf4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">++++++</iframe>++++++</div>+++
