= NICホットプラグ
:revdate: 2026-01-02
:page-revdate: {revdate}

{harvester-product-name}は、xref:virtual-machines/live-migration.adoc#_live_migratable_virtual_machines[ライブマイグレーション可能]な仮想マシンのネットワークインタフェースコントローラ（NIC）のホットプラグおよびホットアンプラグをサポートしています。この機能により、再起動を必要とせずに、実行中の仮想マシンからネットワークインタフェースを追加および削除できます。

[NOTE]
====
ネットワークインタフェースのMACアドレスが明示的に設定されていない場合、{harvester-product-name}バージョン1.7.0より前のクラスタで作成された仮想マシンではNICホットプラグを実行できません。この機能を有効にするには、それらの仮想マシンを再起動する必要があります。再起動により、システムは観測されたMACアドレスを仮想マシンの設定に自動的に保存します。

さらに、xref:integrations/rancher/node-driver/node-driver.adoc[Harvester Node Driver]およびxref:integrations/terraform/terraform-provider.adoc[Harvester Terraform Provider]を使用して作成された仮想マシンは、NICのホットプラグおよびホットアンプラグを_サポートしていません_。
====

== 実行中の仮想マシンにNICをホットプラグする

. {harvester-product-name} UIで、*仮想マシン*画面に移動します。

. 対象の仮想マシンを見つけて、*⋮ -> ネットワークインタフェースのホットプラグ*を選択します。

. ネットワークインタフェースの名前を指定し、仮想マシンネットワークを選択します。
+
xref:networking/vm-network.adoc#_vlan_network[VLANネットワーク]、xref:networking/vm-network.adoc#_untagged_network[タグなしネットワーク]、またはxref:networking/vm-network.adoc#_vlan_trunk_network[VLANトランクネットワーク]を選択できます。

. *適用*をクリックします。

{harvester-product-name} xref:virtual-machines/live-migration.adoc#_prerequisites[仮想マシンを移行します]、指定されたインターフェースはブリッジバインディングを通じて接続されます。

ホットプラグされたインタフェースの数に関する制限については、KubeVirtドキュメントの https://kubevirt.io/user-guide/network/hotplug_interfaces/#virtio-limitations[Virtioの制限]を参照してください。

== 実行中の仮想マシンからNICをホットアンプラグする

[IMPORTANT]
====
このアクションは、次の条件が満たされている場合にのみ実行できます：

* 仮想マシンには少なくとも2つのネットワークインタフェースがあります。残りの1つのネットワークインタフェースをホットアンプラグすることはできません。
* 対象のネットワークインタフェースはブリッジバインディングを通じて接続されています。
====

. {harvester-product-name} UIで、*仮想マシン*画面に移動します。

. 対象の仮想マシンの名前をクリックし、*ネットワーク*タブに移動します。

. ターゲットのネットワークインタフェースを見つけてから、*ネットワークインタフェースを切り離す*をクリックしてください。

{harvester-product-name} xref:virtual-machines/live-migration.adoc#_prerequisites[仮想マシンを移行し]、ネットワークインタフェースを切り離します。