= 仮想マシン1～2台単位
:revdate: 2026-01-08
:page-revdate: {revdate}

次のいずれかの方法を使用して、xref:../virtual-machines/create-vm.adoc[Linux仮想マシン]を作成できます：

* {harvester-product-name} UI：*仮想マシン*画面で、*作成*をクリックし、各タブの設定を構成します。
* Kubernetes API：`VirtualMachine`オブジェクトを作成します。
* xref:../integrations/terraform/terraform-provider.adoc[Harvester Terraform Provider]：`harvester_virtualmachine`リソースブロックを定義します。

UIでxref:../virtual-machines/create-windows-vm.adoc[Windows仮想マシン]を作成するには、若干異なる手順が必要です。{harvester-product-name}は、Windows用のVirtioドライバーを追加したボリュームを備える、`windows-iso-image-base-template`という名前の仮想マシンテンプレートを提供し、構成プロセスを簡素化します。Virtioデバイスが必要ですが、テンプレートを使用しない場合は、正しいハードウェア検出を有効にするために、Windows用の独自のVirtioドライバーを追加する必要があります。

== 検証済みゲストオペレーティングシステム

次のオペレーティングシステムは、{harvester-product-name}仮想マシンで動作することが検証されています：

* SUSE Linux Enterprise Micro 6.0および6.1
* SUSE Linux Enterprise Server 15 SP6および15 SP7
* Red Hat Enterprise Linux 9および10
* Ubuntu 22.04および24.04
* Windows 11
* Windows Server 2025

[NOTE]
====
このリストには、テスト済みのオペレーティングシステムのみが含まれており、網羅的であることを意図していません。他のオペレーティングシステムも{harvester-product-name}仮想マシンで動作する可能性があります。ただし、ゲストオペレーティングシステムは{harvester-product-name}クラスターのホストのアーキテクチャと一致する必要があります。AMDの仮想マシンはAMDクラスター上でのみ実行でき、ARMの仮想マシンはARMクラスター上でのみ実行できます。

あなたは、使用することを決定した商用ソフトウェアのライセンスを取得、アクティブ化、管理する責任があります。{harvester-product-name}は、未テスト、未パッチ、古いオペレーティングシステムの使用によって発生する可能性のある損害やデータの損失について責任を負うことはできません。

この文書の内容は、最新の状況を反映していない可能性があり、予告なしにいつでも変更されることがあります。
====