= Complementos
:revdate: 2025-12-30
:page-revdate: {revdate}

{harvester-product-name} proporciona características opcionales como complementos para mantener una huella de instalación mínima. Este diseño permite habilitar o deshabilitar funcionalidades según tu caso de uso y requisitos. Puedes personalizar la configuración de cada complemento, aunque el nivel de personalización depende del software subyacente.

Los siguientes complementos están disponibles en esta versión:

* xref:add-ons/lvm-local-storage.adoc[csi-driver-lvm] (Experimental)
* xref:add-ons/kubeovn-operator.adoc[kubeovn-operator] (Experimental)
* xref:add-ons/nvidia-driver-toolkit.adoc[nvidia-driver-toolkit]
* xref:add-ons/pcidevices-controller.adoc[pcidevices-controller]
* xref:observability/logging.adoc[rancher-logging]
* xref:observability/monitoring.adoc[rancher-monitoring]
* xref:add-ons/rancher-vcluster.adoc[rancher-vcluster] (Experimental)
* xref:add-ons/harvester-seeder.adoc[seeder] (Experimental)
* xref:add-ons/vm-dhcp-controller.adoc[vm-dhcp-controller] (Experimental)
* xref:add-ons/vm-import-controller.adoc[vm-import-controller]

Puedes habilitar y deshabilitar complementos en la pantalla de *Complementos* de la interfaz de usuario {harvester-product-name}.

|===
| Operación | Acción | Nuevo estado

| Habilitando un complemento
| Selecciona el complemento y luego selecciona *⋮ -> Habilitar*.
| **DeploySuccessful**

| Deshabilitando un complemento
| Selecciona el complemento y luego selecciona *⋮ -> Deshabilitar*.
| *Inhabilitado*
|===

[NOTE]
====
{harvester-product-name} almacena los datos de configuración de los complementos deshabilitados, permitiendo su reutilización inmediata al volver a habilitarlos.
====