= Add-on Development Guide
:revdate: 2025-06-17
:page-revdate: {revdate}

{harvester-product-name} add-ons allow you to enable and disable specific product and third-party components based on your requirements. Add-ons function as a wrapper for the https://documentation.suse.com/cloudnative/rke2/latest/en/helm.html#_using_the_helm_crd[{rke2-product-name} HelmChart resource definition (CRD)].

== Prerequisites

* An existing {harvester-product-name} cluster

== Add-on Specifications

The `Addon` CRD supports the following fields:

[,yaml]
----
apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  name: example-add-on           # Name of add-on
  namespace: example-namespace  # Namespace where the add-on CRD is deployed and where the associated Kubernetes components will be deployed
  labels:                       # Optional add-on labels
    Add-on.harvesterhci.io/experimental: "true" # Predefined label used on the UI to identify add-ons with the "experimental" maturity level
spec:
  enabled: false                # Boolean indicating if an add-on should be enabled or disabled on definition
  repo: https://chartsrepo.com  # Helm chart repository containing the Helm chart managed by the add-on
  version: "v0.19.0"            # Version of the Helm chart to be installed
  chart: mychart                # Name of the Helm chart in the Helm chart repository
  valuesContent: |-             # File (values.yaml) that must be passed to the Helm chart
    contents of values.yaml
    that need to be passed
    to the chart
----

[NOTE]
====
Experimental add-ons are not directly packaged in {harvester-product-name}. An example is the https://github.com/harvester/experimental-addons/blob/main/rancher-vcluster/rancher-vcluster.yaml[`rancher-vcluster`] add-on.
====

== Installation

[,bash]
----
kubectl apply -f /path/to/add-on.yaml
----

== Usage

After creating an `Addon` CRD, you can can toggle the `enabled` field to enable and disable the associated Helm chart.

== Upgrade

Changes to the `repo`, `version`, `chart` or `valueContent` fields will trigger a `helm upgrade`, which forces an upgrade of the existing Helm chart.

== Uninstallation

[,bash]
----
kubectl delete -f /path/to/Add-on.yaml
----
