= 用語集
:revdate: 2026-01-27
:page-revdate: {revdate}

== *クラスタネットワーク*

{harvester-product-name}クラスタ内のネットワークトラフィックを送信するための、トラフィックが分離されたフォワーディングパスです。

== *ゲストクラスタ* / *ゲストKubernetesクラスタ*

{harvester-product-name}クラスタ上で動作する、統合された仮想マシンのグループです。

{harvester-product-name}および{rancher-product-name}インターフェースを使って、RKE2およびK3sゲストクラスタを作成できます。ゲストクラスタの作成には、インターネットまたはプライベートレジストリからのイメージの取得が含まれます。

ゲストクラスタは、コンテナワークロードを実行するための主要なインフラストラクチャを形成します。特定の{harvester-product-name}および{rancher-product-name}のバージョンでは、xref:integrations/rancher/rancher-integration.adoc#_bare_metal_container_workload_support_experimental[直接{harvester-product-name}クラスタに]コンテナワークロードをデプロイできます（いくつかの制限があります）。

== *ゲストノード* / *ゲストクラスタノード*

コンテナワークロードを実行するために{harvester-product-name}クラスタリソースを使用する仮想マシン。

ゲストノードは、ポッド関連の活動を制御し、望ましいクラスタ状態を維持する制御プレーンを通じて管理されます。

== *{harvester-product-name}クラスタ*

{harvester-product-name}ハイパーバイザーがインストールされた、統合された物理サーバー（ホスト）のグループです。これらのサーバーは、仮想マシンを実行するための環境を提供するために、コンピュート、メモリ、ストレージリソースを共同で管理します。

{harvester-product-name}のマルチノード機能、特に高可用性を完全に実現するには、3ノードのクラスタが必要です。最新バージョンでは、2つの管理ノードと1つのxref:hosts/witness-node.adoc[ウィットネスノード]（さらにオプションで1つ以上のワーカーノード）を持つクラスタを作成できます。xref:installation-setup/single-node-clusters.adoc[シングルノードクラスタ]も作成でき、ほとんどの機能をサポートします（高可用性、マルチレプリカサポート、ライブマイグレーションを除く）。

{harvester-product-name}クラスタは{rancher-product-name}にインポートして管理できます。この文脈では、インポートされた{harvester-product-name}クラスタは「管理クラスタ」または「ダウンストリームユーザークラスタ」（しばしば「ダウンストリームクラスタ」と略される）として知られています。この用語は、{rancher-product-name}サーバーに接続された任意のKubernetesクラスタを指します。

特定の{harvester-product-name}および{rancher-product-name}のバージョンでは、{harvester-product-name}クラスタにコンテナワークロードを直接デプロイできます（いくつかの制限があります）。このxref:integrations/rancher/rancher-integration.adoc#_bare_metal_container_workload_support_experimental[実験的機能]が有効になっていると、コンテナワークロードは仮想マシンワークロードとシームレスに相互作用します。

== *{harvester-product-name}ハイパーバイザー*

単一の物理サーバー上で動作する専門のオペレーティングシステムとxref:introduction/overview.adoc#_architecture[ソフトウェアスタック]。

== *{harvester-product-name} ISO*

インストール中にプリロードされるコアオペレーティングシステムコンポーネントとすべての必要なコンテナイメージを含むインストールイメージ。

== *{harvester-product-name}ノード*

{harvester-product-name}ハイパーバイザーがインストールされている物理サーバー。

{harvester-product-name}クラスタに参加する各ノードには、クラスタ内でノードが実行できる機能を決定するxref:hosts/hosts.adoc#_role_management[役割]が割り当てられなければなりません。すべての{harvester-product-name}ノードはデータを処理しますが、すべてがデータを保存できるわけではありません。

== *ハーベスタークラウドプロバイダー*

{rancher-short-name}管理の{harvester-product-name}クラスターがxref:integrations/rancher/cloud-provider.adoc[ゲストKubernetesクラスターのためのネイティブクラウドバックエンド]として機能することを可能にするコンポーネント。ハーベスタークラウドプロバイダーはKubernetesクラウドコントローラーマネージャー（CCM）とコンテナストレージインターフェース（CSI）ドライバーを統合し、ゲストクラスターが手動介入なしに{harvester-product-name}-ネイティブリソース（ロードバランサーとストレージ）を動的に要求し管理できるようにします。

== *ハーベスターCSIドライバー*

xref:integrations/rancher/csi-driver.adoc[ゲストKubernetesクラスタのための標準コンテナストレージインターフェース（CSI）を提供するドライバー]であり、コンテナワークロードが基盤となる{harvester-product-name}クラスタと統合されたストレージソリューションを使用できるようにします。このコンポーネントは、仮想マシンにボリュームをホットプラグすることを可能にし、ネイティブストレージパフォーマンスを提供します。

== *ハーベスター・ノードドライバー*

{rancher-product-name}が使用するドライバーで、xref:integrations/rancher/node-driver/node-driver.adoc[クラスタ内で仮想マシンをプロビジョニングし{harvester-product-name}]、それらの仮想マシン上でゲストKubernetesクラスタを起動および管理します。

== *ライブマイグレーション*

ゲストオペレーティングシステムを中断させず、ワークロードのダウンタイムを引き起こすことなく、同じ{harvester-product-name}クラスタ内の別のノードに実行中の仮想マシンをxref:virtual-machines/live-migration.adoc[移動するプロセス]。ライブマイグレーションは、xref:virtual-machines/live-migration.adoc#_prerequisites[前提条件]が満たされ、影響を受ける仮想マシンがxref:virtual-machines/live-migration.adoc#_live_migratable_virtual_machines[ライブマイグレーション可能]である場合にのみ発生します。

== *mgmt*

クラスタのデプロイメント中にxref:networking/cluster-network.adoc#_built_in_cluster_network[自動的に作成される]クラスタネットワークで、すべてのホストで常に有効です。{harvester-product-name}は、クラスタ内通信とクラスタ管理タスクに`mgmt`を使用します。

== *ネットインストールISO*

インストールイメージは、xref:installation-setup/media/net-install.adoc[コア{harvester-product-name}オペレーティングシステムコンポーネント]のみを含み、インストーラーが起動してからディスクにオペレーティングシステムをインストールできるようにします。インストールが完了すると、オペレーティングシステムはインターネットから必要なすべてのコンテナイメージを取得します。

== *ネットワーク構成*

均一なネットワーク仕様を持つクラスタノードのセットが特定のクラスタネットワークに接続する方法の定義。

== *オーバーレイネットワーク*

仮想マシン間のトラフィックをxref:networking/vm-network.adoc#_overlay_network_experimental[カプセル化して転送する]仮想レイヤー2スイッチを表す仮想ネットワーク。オーバーレイネットワークは、仮想プライベートクラウド（VPC）や仮想マシンのワークロード用のサブネットなど、高度な Software-Defined Networking（SDN）機能をサポートします。

== *ストレージネットワーク*

xref:networking/storage-network.adoc[Longhornのレプリケーショントラフィック]を`mgmt`および他のクラスタ全体のワークロードから隔離するためのネットワーク。

== *VLANトランクネットワーク*

仮想ネットワークは、xref:networking/vm-network.adoc#_vlan_trunk_network[複数の重複するVLAN ID範囲]のトラフィックを同時に運ぶことができる単一のネットワークインターフェースを仮想マシンに提供します。仮想マシンがVLANトランクネットワークに接続されると、ゲストオペレーティングシステムとアプリケーションは、指定された範囲内の任意のVLAN IDでタグ付けされたパケットを送受信できます。

== *VMマイグレーションネットワーク*

xref:networking/vm-migration-network.adoc[仮想マシンのマイグレーショントラフィック]を`mgmt`および他のクラスタ全体のワークロードから隔離するためのネットワーク。

== *VMネットワーク*

特定のクラスタネットワークにリンクされた仮想ネットワークで、仮想マシンと外部ネットワーク間の通信を可能にします。

== *ウィットネスノード*

xref:hosts/witness-node.adoc[非計算ノード]は、クラスタのコンセンサスを維持するためだけに使用されます。これにより、管理ノードが利用できなくなったり、ネットワーク障害が発生した場合でも、システムがクラスタの更新に関して過半数の決定（定足数）に達することができます。

ウィットネスノードはワークロードを実行せず、データを保存しません。各{harvester-product-name}クラスタには、ウィットネスノードが1つだけ存在できます。