= 概要
:revdate: 2025-07-16
:page-revdate: {revdate}

{harvester-product-name-tm}は、Kubernetesを基盤とした最新のオープンで相互運用可能な https://en.wikipedia.org/wiki/Hyper-converged_infrastructure[ハイパーコンバージドインフラストラクチャ(HCI)]ソリューションです。これは、 https://about.gitlab.com/topics/cloud-native/[クラウドネイティブ] HCIソリューションを求めるオペレーター向けに設計されたオープンソースの代替品です。{harvester-product-name}は、ベアメタルサーバー上で動作し、統合された仮想化および分散ストレージ機能を提供します。従来の仮想マシン(VM)に加えて、{harvester-product-name}は https://documentation.suse.com/cloudnative/rancher-manager/v2.11/en/integrations/harvester/harvester.html[{rancher-product-name-tm}]との統合により、コンテナ化された環境を自動的にサポートします。レガシ仮想化インフラストラクチャを統合しながら、コアからエッジロケーションまでコンテナの採用を可能にするソリューションを提供します。

== アーキテクチャ

アーキテクチャは、最先端のオープンソース技術で構成されています：

* *Linux OS.* https://documentation.suse.com/cloudnative/os-manager/[{elemental-product-name}]は、{harvester-product-name}の中心にあり、Kubernetesクラスター内で可能な限りOSメンテナンスを削減するために設計された不変のLinuxディストリビューションです。
* *Kubernetesの上に構築されています。* https://kubernetes.io/[Kubernetes]は、すべてのフォームファクターにおいて主要なインフラストラクチャ言語となり、{harvester-product-name}はその背後にKubernetesを持つHCIソリューションです。
* *KubeVirtによる仮想化管理。* https://kubevirt.io/[KubeVirt]は、Kubernetesの上でKVMを使用した仮想化管理を提供します。
* *ストレージ管理は{longhorn-product-name}によって行われます。* https://documentation.suse.com/cloudnative/storage/1.8/en/longhorn-documentation.html[{longhorn-product-name}]は、分散ブロックストレージと階層化を提供します。
* *GrafanaとPrometheusによる監視。* https://grafana.com/[Grafana]と https://prometheus.io/[Prometheus]は、堅牢な監視とログ記録を提供します。

image::architecture.svg[]

== 機能

{harvester-product-name}は、複雑な外部SANの代わりにローカルの直接接続ストレージを活用した、エンタープライズ向けの使いやすいインフラストラクチャプラットフォームです。これは、コンテナとVMワークロード全体で統一された自動化言語としてKubernetes APIを利用します。いくつかの主要な機能は次のとおりです：

* *簡単に始められます。*{harvester-product-name}はブータブルアプライアンスイメージとして出荷されるため、 https://github.com/harvester/harvester/releases[ISOイメージ]を使用してベアメタルサーバーに直接インストールするか、xref:../installation-setup/methods/pxe-boot-install.adoc[iPXE]スクリプトを使用して自動的にインストールできます。
* *VMライフサイクル管理。*SSHキーの挿入、cloud-init、グラフィックおよびシリアルポートコンソールを含むVMの作成、編集、クローン、削除を簡単に行えます。
* *VMライブマイグレーション。*ダウンタイムゼロでVMを別のホストまたはノードに移動します。
* *VMのバックアップ、スナップショット、および復元。*NFS、S3サーバー、またはNASデバイスからVMをバックアップします。バックアップを使用して、失敗したVMを復元するか、別のクラスターに新しいVMを作成します。
* *ストレージ管理。* {harvester-product-name}は、分散ブロックストレージと階層化をサポートしています。ボリュームはストレージを表し、ボリュームを簡単に作成、編集、クローン、またはエクスポートできます。
* *ネットワーク管理。*仮想IP（VIP）と複数のNICを使用することをサポートしています。VMが外部ネットワークに接続する必要がある場合は、VLANまたはタグなしネットワークを作成します。
* *との統合。{rancher-product-name}*{harvester-product-name}に直接アクセスし、{rancher-product-name}の仮想化管理ページを通じてVMのワークロードをKubernetesクラスターと一緒に管理します。

== ユーザインタフェース

{harvester-product-name}は、インフラストラクチャを視覚化し管理するための強力で使いやすいウェブベースのインターフェースを提供します。インストール後、ノードのターミナルからUIのIPアドレスにアクセスできます。

+++++++++<iframe width="99%" height="450" src="https://www.youtube.com/embed/Ngsk7m6NYf4" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">[]++++++</iframe>+++++++++
