= 单节点集群
:revdate: 2025-07-16
:page-revdate: {revdate}

{harvester-product-name} 支持单节点集群，适用于可以容忍较低弹性或需要最少初始部署资源的实现。您可以使用标准安装方法创建单节点集群（xref:/installation-setup/methods/iso-install.adoc[.iso 映像]、xref:/installation-setup/methods/usb-install.adoc[USB] 和 xref:/installation-setup/methods/pxe-boot-install.adoc[PXE 引导]）。

单节点集群支持大多数 {harvester-product-name} 功能，包括创建 RKE2 集群和节点升级（有一些限制）。然而，这种部署类型有以下主要缺点：

* 没有高可用性：需要重启节点的错误和更新会导致正在运行的虚拟机停机。
* 在升级期间没有实时迁移和零停机支持。

== 先决条件

在开始部署单节点集群之前，请确保满足以下要求。

* 硬件：xref:/installation-setup/requirements.adoc#_hardware_requirements[使用服务器级硬件]，具有足够的资源来运行 {harvester-product-name} 和生产工作负载。不支持笔记本电脑和嵌套虚拟化。
* 网络：请根据虚拟机之间传输的流量类型来xref:/installation-setup/requirements.adoc#_port_requirements_for_nodes[配置端口]。

== 默认 StorageClass 的副本数量

{harvester-product-name} 使用 StorageClasses 来描述 {longhorn-product-name} 如何配置卷。每个 StorageClass 都有一个参数，定义为每个卷创建的副本数量。

默认 StorageClass `harvester-longhorn` 的副本数量值为 *3*，以实现高可用性。如果您在单节点集群中使用 `harvester-longhorn`，则 {longhorn-product-name} 无法创建默认数量的副本，卷在 UI 的 *卷* 屏幕上标记为 _降级_。

为避免此问题，您可以执行以下任一操作：

* 使用 xref:/installation-setup/config/configuration-file.adoc[配置文件] 将 `harvester-longhorn` 的 xref:/installation-setup/config/configuration-file.adoc#_install_harvester_storage_class_replica_count[副本数量] 更改为 *1*。
* xref:/storage/storageclass.adoc#_creating_a_storageclass[创建一个新的 StorageClass]，将 *副本数量* 参数设置为 *1*。创建后，在列表中找到新的 StorageClass，然后选择 *⋮* > *设置为默认*。

== 在具有多个磁盘的节点上使用多个副本

{longhorn-product-name} 每个卷仅创建一个副本，即使节点有多个磁盘，因为默认启用了 *副本硬反亲和性*。当节点上已经存在健康副本时，调度程序将阻止在该节点上调度同一卷的新副本。

在高可用性集群中，*副本硬反亲和性* 确保卷的冗余。然而，这种机制可能导致单节点集群中的卷降级（因为没有其他节点可用于调度新副本）。

如果您希望 {longhorn-product-name} 在具有多个磁盘的节点上创建多个副本，请执行以下步骤：

. 启用 https://documentation.suse.com/cloudnative/storage/1.8/en/longhorn-system/settings.html#_replica_node_level_soft_anti_affinity[`Replica Node Level Soft Anti-Affinity`]：当此设置启用时，{longhorn-product-name} 会在已有同一卷健康副本的节点上调度新副本。
. 禁用 https://documentation.suse.com/cloudnative/storage/1.8/en/longhorn-system/settings.html#_replica_disk_level_soft_anti_affinity[`Replica Disk Level Soft Anti-Affinity`]：当此设置禁用时，{longhorn-product-name} 不会在已有同一卷健康副本的磁盘上调度新副本。禁用此设置为单节点集群中的磁盘提供故障容错能力。
. （可选）xref:../storage/storageclass.adoc#_creating_a_storageclass[创建一个新的 StorageClass] 并指定在卷调度期间必须匹配的磁盘标签。

== 升级和维护

单节点集群不支持 xref:/virtual-machines/live-migration.adoc[实时迁移]，因此在集群升级期间虚拟机将不可用。{harvester-product-name} 在开始升级过程之前强制关闭所有虚拟机。您可以配置 {harvester-product-name} 使用 xref:/installation-setup/config/settings.adoc#_upgrade_config[`upgrade-config`] 设置的 `restoreVM` 选项自动恢复正在运行的虚拟机。

启用 xref:/hosts/hosts.adoc#_node_maintenance[维护模式] 也是不可能的，因为该操作依赖于实时迁移功能，而 {harvester-product-name} 无法将唯一的控制平面置于维护模式。
