= Glossary

== *guest cluster* / *guest Kubernetes cluster*

Group of integrated Kubernetes worker machines that run in VMs on top of a SUSE® Virtualization cluster.

You can create RKE1, RKE2, and K3s guest clusters using the SUSE® Virtualization and Rancher interfaces. Creating guest clusters involves pulling images from either the internet or a private registry.

Guest clusters form the main infrastructure for running container workloads. Certain versions of SUSE® Virtualization and Rancher allow you to deploy container workloads xref:../integrations/rancher/rancher-integration.adoc#_harvester_baremetal_container_workload_support_experimental[directly to SUSE® Virtualization clusters] (with some limitations).

== *guest node* / *guest cluster node*

Kubernetes worker VM that uses guest cluster resources to run container workloads.

Guest nodes are managed through a control plane that controls pod-related activity and maintains the desired cluster state.

== *SUSE® Virtualization cluster*

Group of integrated physical servers (hosts) on which the SUSE® Virtualization hypervisor is installed. These servers collectively manage compute, memory, and storage resources to provide an environment for running VMs.

A three-node cluster is required to fully realize the multi-node features of SUSE® Virtualization, particularly high availability. The latest versions allow you to create clusters with two management nodes and one xref:../hosts/witness-node.adoc[witness node] (and optionally, one or more worker nodes). You can also create xref:../installation-setup/single-node-clusters.adoc[single-node clusters] that support most features (excluding high availability, multi-replica support, and live migration).

SUSE® Virtualization clusters can be imported into and managed by Rancher. Within the Rancher context, an imported SUSE® Virtualization cluster is known as a "managed cluster" or "downstream user cluster" (often abbreviated to "downstream cluster"). The Rancher term refers to any Kubernetes cluster that is connected to a Rancher server.

Certain versions of SUSE® Virtualization and Rancher allow you to deploy container workloads directly to SUSE® Virtualization clusters (with some limitations). When this xref:../integrations/rancher/rancher-integration.adoc#_harvester_baremetal_container_workload_support_experimental[experimental feature] is enabled, container workloads seamlessly interact with VM workloads.

== *SUSE® Virtualization hypervisor*

Specialized operating system and xref:./overview.adoc#_architecture[software stack] that runs on a single physical server.

== *SUSE® Virtualization node*

Physical server on which the SUSE® Virtualization hypervisor is installed.

Each node that joins a SUSE® Virtualization cluster must be assigned a xref:../hosts/hosts.adoc#_role_management[role] that determines the functions the node can perform within the cluster. All SUSE® Virtualization nodes process data but not all can store data.

== Harvester Node Driver*

xref:../integrations/rancher/node-driver/node-driver.adoc[Driver] that Rancher uses to provision VMs in a SUSE® Virtualization cluster, and to launch and manage guest Kubernetes clusters on top of those VMs.
