= Storage
:revdate: 2026-05-12
:page-revdate: {revdate}

{harvester-product-name} supports distributed block storage and tiering.

== Built-in storage

https://www.suse.com/products/rancher/storage/[{longhorn-product-name}], the built-in storage system, provides block device volumes to virtual machines and other pods in a {harvester-product-name} cluster. {longhorn-product-name} creates a dedicated storage controller for each volume and synchronously replicates the volume across nodes.

You can create volumes using virtual machine images or StorageClasses. When using a xref:storage/volumes/create-volume.adoc#_create_an_image_volume[virtual machine image] (qcow2, raw, or ISO file) as your source, you must ensure that the volume size is greater than or equal to the image size. When using a xref:storage/storageclass.adoc[StorageClass] to describe how {longhorn-product-name} must provision volumes, you must ensure that the replica count matches the cluster's configuration.

For optimal results, use a dedicated disk (instead of the root disk) for {longhorn-product-name} volumes and a dedicated xref:networking/storage-network.adoc[storage network] to improve I/O performance and stability.

== Third-party storage

{harvester-product-name} supports provisioning of root volumes and data volumes using xref:storage/csidriver.adoc[external Container Storage Interface (CSI) drivers]. Once the CSI driver is installed and the {harvester-product-name} cluster is configured, you can use an external storage solution to store and manage virtual machine images, store virtual machine disks on volumes provisioned by the CSI driver, and perform other critical storage functions.

Storage vendors can validate their storage appliances with {harvester-product-name} to ensure greater interoperability through the https://www.suse.com/product-certification/suse-certified/virtualization-certification/[SUSE Certified Storage for Virtualization] certification. You can find information about enterprise-grade storage solutions that are certified to be compatible with {harvester-product-name} in the https://www.suse.com/pcsc/home[Partner Certification and Solutions Catalog].
