= 部署高可用性集群
:revdate: 2025-06-10
:page-revdate: {revdate}

需要一个包含三个或更多节点的{harvester-product-name}集群，以充分实现高可用性等多节点功能。最新版本允许您创建包含两个管理节点和一个xref:/hosts/witness-node.adoc[witness node]（或者可选地一个或多个工作节点）的集群。您还可以创建支持大多数功能（不包括高可用性、多副本支持和实时迁移）的xref:/installation-setup/single-node-clusters.adoc[单节点集群]。

本指南将引导您完成部署*高可用性集群*和能够承载来宾集群并运行自定义工作负载的虚拟机（VM）的步骤。

== 1.验证是否满足最低硬件和网络要求。

{harvester-product-name}是为使用企业级开源软件组件的裸机服务器构建的。安装程序会自动检查硬件，并在未满足最低xref:/installation-setup/requirements.adoc[要求]时显示警告消息。

== 2.根据您想要使用的安装方法准备安装文件。

您可以从 https://github.com/harvester/harvester/releases[发布]页面下载安装文件。发布说明的*下载*部分包含ISO文件和相关工件的链接。提供了以下类型的ISO文件：

* *完整ISO*：包含核心操作系统组件和所有必需的容器镜像，这些镜像在安装期间预加载。在防火墙或代理后安装{harvester-product-name}时，以及在没有互联网连接的环境中，必须使用完整ISO。
* xref:/installation-setup/media/net-install.adoc[*网络安装ISO*]：仅包含核心操作系统组件。安装完成后，操作系统会从互联网（主要来自Docker Hub）拉取所有必需的容器镜像。

|===
| 方法 | 所需安装文件 | 其他要求

| xref:/installation-setup/methods/iso-install.adoc[ISO]
| ISO
| 不适用

| xref:/installation-setup/methods/usb-install.adoc[USB]
| ISO
| U 盘；实用程序，如 https://etcher.balena.io/[balenaEtcher]或 Linux 的 https://man7.org/linux/man-pages/man1/dd.1.html[dd 命令]

| xref:/installation-setup/methods/pxe-boot-install.adoc[PXE]
| ISO，Linux 内核镜像（vmlinuz），initrd，SquashFS 镜像
| HTTP服务器上的目录（用于提供启动文件）；iPXE启动脚本（用于自动安装）；DHCP服务器配置
|===

== 3.准备集群配置要求。

* 集群词元：节点在加入集群时使用的ASCII字符串
* 每个节点的固定IP地址：可以静态分配或使用DHCP（主机保留）
* 用于集群管理地址的固定虚拟IP地址（VIP）：节点在加入集群时指向的VIP，以及在集群部署后执行管理任务时连接的VIP
* DNS服务器、NTP服务器和代理服务器的地址（如有必要）

== 4.部署第一个集群节点。

部署涉及在主机上安装操作系统和其他组件，然后在安装完成后重启。部署第一个节点会创建集群，默认情况下，第一个节点被分配为管理节点。

在安装过程中，您必须配置节点设置，定义集群管理地址（VIP）和集群词元，并指定其他信息。如有必要，您可以使用一个xref:/installation-setup/config/configuration-file.adoc[配置文件]配置更多设置。

安装完成后，节点将重启，随后显示控制台。控制台显示有关集群（管理URL和状态）和节点（主机名、IP地址和状态）的信息。在集群初始化并且所有服务开始运行后，集群状态会更改为*就绪*。

== 5.为默认`admin`用户配置一个强密码。

一旦集群状态更改为*就绪*，您可以使用控制台上显示的管理URL访问xref:/installation-setup/authentication.adoc[UI]。

== 6.部署其他节点并将其加入集群。

部署涉及在主机上安装操作系统和其他组件，然后在安装完成后重启。所有其他节点加入在第一个节点部署时创建的集群。

在安装过程中，您必须配置节点设置，并指定集群管理地址（虚拟IP）和您之前定义的集群词元。如有必要，您可以使用一个xref:/installation-setup/config/configuration-file.adoc[配置文件]配置更多设置。

当集群有三个或更多节点时，添加到第一个节点后的两个节点会自动提升为管理节点，以形成高可用性（HA）集群。

== 7.创建自定义集群网络（可选）和虚拟机网络（必需）。

网络涉及三个主要概念：

* xref:/networking/cluster-network.adoc#_cluster_network[*集群网络*]：用于在{harvester-product-name}集群中传输网络流量的流量隔离转发路径。
+
在部署过程中，会为集群内部通信创建一个名为xref:/networking/cluster-network.adoc#_built_in_cluster_network[`mgmt`]的集群网络。`mgmt`允许虚拟机从基础设施网络（集群外部）访问，每个节点通过管理网卡连接以进行集群管理。{harvester-product-name}还允许您创建xref:/networking/cluster-network.adoc#_custom_cluster_network[自定义集群网络]，可专用于虚拟机流量。

* xref:/networking/cluster-network.adoc#_network_configuration[*网络配置*]：定义集群节点如何连接到特定集群网络。
+
每个网络配置对应一组具有统一网络规格的节点。只有被网络配置覆盖的节点才能访问相关的集群网络。这种安排为您在配置异构集群时提供了灵活性，特别是当每个节点的网络接口名称不同。

* xref:/networking/cluster-network.adoc#_vm_network[*虚拟机网络*]：虚拟机用于与其他虚拟机和外部基础设施网络通信的虚拟网络。
+
每个虚拟机网络链接到特定的集群网络，用于传输虚拟机流量。您可以根据需求创建xref:/networking/vm-network.adoc#_vlan_network[VLAN网络]或xref:/networking/vm-network.adoc#_untagged_network[无标签网络]，例如流量隔离、网络分段、管理便利性或与外部网络环境的对齐。

在创建虚拟机之前，请创建必要的网络。如果每个集群节点附加了多个网络接口，请考虑xref:/networking/cluster-network.adoc#_create_a_new_cluster_network[创建自定义集群网络]和网络配置以实现更好的流量隔离。否则，您只能使用管理网络来传输 VM 流量。接下来，xref:/networking/vm-network.adoc#_create_a_vm_network[创建一个 VM 网络]，该网络链接到 `mgmt` 或您创建的任何自定义集群网络。

== 8.导入 VM 镜像。

在 UI 上，您可以通过从本地文件系统上传镜像，或指定可以从集群访问的镜像 URL，来导入 ISO、qcow2 和 raw xref:/virtual-machines/vm-images/upload-image.adoc[镜像]。

== 9.导入 SSH 密钥。（建议方法）

您可以将 SSH 公钥存储在 {harvester-product-name} 中。当 VM 启动时，可以将存储的密钥 xref:/virtual-machines/access-vm.adoc#_ssh_access[注入] 到 VM 中，以允许通过 SSH 进行安全访问。已验证的密钥显示在 UI 上的 *SSH 密钥* 屏幕上。

== 10.创建 VMs。

您可以使用以下方法之一创建 xref:/virtual-machines/create-vm.adoc[Linux VMs]：

* UI：在 *虚拟机* 屏幕上，单击 *创建* 并配置每个选项卡上的设置。
* Kubernetes API：创建一个 `VirtualMachine` 对象。
* xref:/integrations/terraform/terraform-provider.adoc[Terraform 提供者]：定义一个 `harvester_virtualmachine` 资源块。

在 UI 上创建 xref:/virtual-machines/create-windows-vm.adoc[Windows VMs] 涉及稍微不同的步骤。{harvester-product-name} 提供一个名为 `windows-iso-image-base-template` 的 VM 模板，该模板添加了带有 Virtio 驱动程序的卷，以简化 VM 配置过程。如果您需要 Virtio 设备但选择不使用模板，则必须为 Windows 添加自己的 Virtio 驱动程序，以启用正确的硬件检测。

== 下一步怎么办？

以下部分提供了指南，指导您如何备份和恢复 VMs、管理主机以及如何将 {rancher-product-name} 与 {harvester-product-name} 一起使用。

* xref:/virtual-machines/backup-restore.adoc[VM 备份、快照和恢复]
* xref:/hosts/hosts.adoc[主机管理]
* xref:/integrations/rancher/rancher-integration.adoc[{rancher-product-name} 集成]
