= 词汇表
:revdate: 2026-01-27
:page-revdate: {revdate}

== *集群网络*

用于在{harvester-product-name}集群中传输网络流量的流量隔离转发路径。

== *来宾集群* / *来宾Kubernetes集群*

在{harvester-product-name}集群上运行的一组集成虚拟机。

您可以使用{harvester-product-name}和{rancher-product-name}接口创建RKE2和K3s来宾集群。创建来宾集群涉及从互联网或私有注册表中拉取镜像。

来宾集群构成运行容器工作负载的主要基础设施。某些版本的{harvester-product-name}和{rancher-product-name}允许您将容器工作负载xref:integrations/rancher/rancher-integration.adoc#_bare_metal_container_workload_support_experimental[直接部署到{harvester-product-name}集群]（有一些限制）。

== *来宾节点* / *来宾集群节点*

使用{harvester-product-name}集群资源运行容器工作负载的虚拟机。

来宾节点通过控制平面进行管理，该控制平面控制与Pod相关的活动并维护所需的集群状态。

== *{harvester-product-name}集群*

安装了{harvester-product-name}超级管理程序的一组集成物理服务器（主机）。这些服务器共同管理计算、内存和存储资源，以提供运行虚拟机的环境。

需要一个三节点集群才能充分实现{harvester-product-name}的多节点功能，特别是高可用性。最新版本允许您创建具有两个管理节点和一个xref:hosts/witness-node.adoc[见证节点]的集群（可选地，一个或多个工作节点）。您还可以创建xref:installation-setup/single-node-clusters.adoc[单节点集群]，支持大多数功能（不包括高可用性、多副本支持和实时迁移）。

{harvester-product-name}集群可以导入并由{rancher-product-name}管理。在此上下文中，导入的{harvester-product-name}集群被称为“托管集群”或“下游用户集群”（通常缩写为“下游集群”）。该术语指的是任何连接到{rancher-product-name}服务器的Kubernetes集群。

某些版本的{harvester-product-name}和{rancher-product-name}允许您将容器工作负载直接部署到{harvester-product-name}集群（有一些限制）。当启用此xref:integrations/rancher/rancher-integration.adoc#_bare_metal_container_workload_support_experimental[实验特性]时，容器工作负载与虚拟机工作负载无缝交互。

== *{harvester-product-name}超级管理程序*

在单个物理服务器上运行的专用操作系统和xref:introduction/overview.adoc#_architecture[软件栈]。

== *{harvester-product-name} ISO*

包含核心操作系统组件和所有必需容器镜像的安装映像，这些镜像在安装期间预加载。

== *{harvester-product-name}节点*

安装了{harvester-product-name}超级管理程序的物理服务器。

每个加入{harvester-product-name}集群的节点必须被分配一个xref:hosts/hosts.adoc#_role_management[角色]，以确定该节点在集群中可以执行的功能。所有{harvester-product-name}节点处理数据，但并非所有节点都可以存储数据。

== *Harvester云提供商*

使{rancher-short-name}管理的{harvester-product-name}集群能够作为xref:integrations/rancher/cloud-provider.adoc[来宾Kubernetes集群的本地云后端]运行的组件。Harvester云提供商集成了Kubernetes云控制器管理器（CCM）和容器存储接口（CSI）驱动程序，允许来宾集群动态请求和管理{harvester-product-name}-本地资源（负载均衡器和存储），无需人工干预。

== *Harvester CSI驱动程序*

为来宾Kubernetes集群xref:integrations/rancher/csi-driver.adoc[提供标准容器存储接口（CSI）]的驱动程序，允许容器工作负载使用与底层{harvester-product-name}集成的存储解决方案。此组件支持将卷热插拔到虚拟机，以提供本地存储性能。

== *Harvester节点驱动程序*

{rancher-product-name}用于xref:integrations/rancher/node-driver/node-driver.adoc[在{harvester-product-name}集群中部署虚拟机]的驱动程序，并在这些虚拟机上启动和管理来宾Kubernetes集群。

== *实时迁移*

xref:virtual-machines/live-migration.adoc[将正在运行的虚拟机迁移到]同一{harvester-product-name}集群中的另一个节点的过程，而不会中断来宾操作系统并导致工作负载停机。仅在满足xref:virtual-machines/live-migration.adoc#_prerequisites[先决条件]并且受影响的虚拟机是xref:virtual-machines/live-migration.adoc#_live_migratable_virtual_machines[可实时迁移的]时，才能进行实时迁移。

== *mgmt*

集群网络在xref:networking/cluster-network.adoc#_built_in_cluster_network[集群部署时自动创建]{harvester-product-name}，并始终在所有主机上启用。{harvester-product-name}使用`mgmt`进行集群内部通信和集群管理任务。

== *网络安装ISO*

安装映像仅包含xref:installation-setup/media/net-install.adoc[内核{harvester-product-name}操作系统组件]，允许安装程序启动并在磁盘上安装操作系统。安装完成后，操作系统从互联网拉取所有所需的容器映像。

== *网络配置*

定义一组具有统一网络规范的集群节点如何连接到特定的集群网络。

== *覆盖网络*

表示虚拟层2交换机的虚拟网络，xref:networking/vm-network.adoc#_overlay_network_experimental[封装并转发虚拟机之间的流量]。覆盖网络支持高级软件定义网络（SDN）功能，如虚拟私有云（VPC）和虚拟机工作负载的子网。

== *存储网络*

用于xref:networking/storage-network.adoc[隔离Longhorn复制流量]与`mgmt`和其他集群范围工作负载之间的内部流量的网络。

== *VLAN干道网络*

提供虚拟机单个网络接口的虚拟网络，可以同时承载xref:networking/vm-network.adoc#_vlan_trunk_network[多个重叠的VLAN ID范围]的流量。当虚拟机连接到VLAN干道网络时，来宾操作系统和应用程序可以发送和接收带有指定范围内任何VLAN ID标记的数据包。

== *虚拟机迁移网络*

用于xref:networking/vm-migration-network.adoc[隔离虚拟机迁移流量]与`mgmt`和其他集群范围工作负载之间的内部流量的网络。

== *虚拟机网络*

与特定集群网络连接的虚拟网络，允许虚拟机与外部网络之间的通信。

== *见证节点*

xref:hosts/witness-node.adoc[非计算节点]仅用于维护集群共识。它确保系统能够在集群更新时达成多数决策（法定人数），即使管理节点不可用或发生网络故障。

见证节点不运行工作负载，也不存储数据。每个{harvester-product-name}集群只能有一个见证节点。